using Avalonia.Controls;
using ReactiveUI;
using System.Collections.Generic;
using System.Linq;
using System.Reactive;
using System.Reactive.Linq;

namespace TaymadeEntities.ViewModels
{
    /// <summary>
    /// 
    /// </summary>
    /// <seealso cref="TaymadeEntities.ViewModels.ViewModelBase" />
    /// <autogeneratedoc />
    public class DialogModelBase : ViewModelBase
    {

        #region Public Fields

        /// <summary>
        /// Defines the resultButton.
        /// </summary>
        public Models.DialogResultButton? resultButton;

        #endregion Public Fields

        #region Private Fields

        /// <summary>
        /// Defines the caller.
        /// </summary>
        private Window? caller;

        #endregion Private Fields

        #region Public Constructors

        public DialogModelBase()
        {
            Accept = ReactiveCommand.Create(DoAccept);
            Cancel = ReactiveCommand.Create(DoCancel);
        }

        #endregion Public Constructors

        #region Public Properties

        /// <summary>
        /// Gets or sets the accept.
        /// </summary>
        /// <value>
        /// The accept.
        /// </value>
        /// <autogeneratedoc />
        public ReactiveCommand<Unit, Unit>? Accept { get; set; }

        /// <summary>
        /// Gets or sets the cancel.
        /// </summary>
        /// <value>
        /// The cancel.
        /// </value>
        /// <autogeneratedoc />
        public ReactiveCommand<Unit, Unit>? Cancel { get; set; }

        #endregion Public Properties



        #region Properties

        /// Gets or sets the Caller.
        /// </summary>
        /// <summary>
        /// Gets or sets the Caller.
        /// </summary>
        public Window Caller { get => caller; set => caller = value; }

        public Models.DialogResultButton ResultButton { get => resultButton; set => resultButton = value; }


        

        public ReactiveCommand<Unit, Unit> AddCancelCommand()
        {
            ReactiveCommand<Unit, Unit> myCommand = ReactiveCommand.Create(() =>
            {

                if (this != null)
                {
                    this.DoCancel();
                }

            });

            return myCommand;
        }

        // public Movies CurrentMovie { get => currentMovie; set => this.RaiseAndSetIfChanged(ref currentMovie, value); }

        public void SetOkCancelPanelCommands(TaymadeControls.Buttons.OKCancelPanel oKCancelPanel)
        {
            if (oKCancelPanel != null)
            {
                if (oKCancelPanel.OkButton != null) oKCancelPanel.OkButton.Command = AddOKCommand();
                if (oKCancelPanel.CancelButton != null) oKCancelPanel.CancelButton.Command = AddCancelCommand();
            }
        }

        public ReactiveCommand<Unit, Unit> AddOKCommand()
        {
            ReactiveCommand<Unit, Unit> myCommand = ReactiveCommand.Create(() =>
            {

                if (this != null)
                {
                    this.DoAccept();
                }

            });

            return myCommand;
        }

        #endregion
        #region Methods

        /// <summary>
        /// The DoAccept.
        /// </summary>
        internal void DoAccept()
        {

            if (Caller != null)
            {
                // returned to dialog's view model
                resultButton = new Models.DialogResultButton();

                // Caller.Close(resultButton);
                 if (!(Caller is Views.MainWindow)) Caller.Close();
            }
        }


        /// <summary>
        /// The DoCancel.
        /// </summary>
        internal void DoCancel()
        {
            if (Caller != null)
            {
                resultButton = new Models.DialogResultButton();
                resultButton.Result = Models.DialogResultButton.ResultType.Cancel;

                Caller.Close(resultButton);
        //        Caller.Close();
            }
        }
        #endregion

    }
}
