//-----------------------------------------------------------------------
// <copyright file="MovieViewModel.cs" company="Taymade Software Services">
//     Copyright (c) Taymade Software Services. All rights reserved.
// </copyright>
// <created>27/04/2022 13:41:27 27/04/2022 13:41:27 </created>
// <author>Doug Taylor</author>
//-----------------------------------------------------------------------

namespace TaymadeEntities.ViewModels
{
    using Avalonia.Media;

    //using Avalonia.Controls;
    using TaymadeEntities.Models;
    using TaymadeEntities.Support;
    using Microsoft.EntityFrameworkCore;
    using ReactiveUI;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Reactive;
    using System.Windows.Input;
    using Avalonia.Controls;

    //using TaymadeEntities.Views;

    /// <summary>
    /// Defines the <see cref="MovieViewModel" />.
    /// </summary>
    public class MovieViewModel : MovieViewModelBase
    {
        #region Fields

        /// <summary>
        /// Defines the directorList.
        /// </summary>
        private List<Models.Director>? directorList = Models.DataController.DirectorList;

        /// <summary>
        /// Defines the foundMovie.
        /// </summary>
        private TaymadeEntities.Support.MovieBase? foundMovie;

        /// <summary>
        /// Defines the progressPercent.
        /// </summary>
        private int progressPercent = 0;

        /// <summary>
        /// Defines the setChapterColour.
        /// </summary>
        private Brush setChapterColour = new SolidColorBrush(Color.FromRgb(156, 156, 156));

        private Bookmark currentBookmark;
        private Cast currentCastMember;
        private int year;
        private string movieTitle = "title";

        // private ObservableCollection<Movies>? movieList;

        #endregion Fields

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="MovieViewModel"/> class.
        /// </summary>
        public MovieViewModel()
        {

            this.SetupCommands();

            //this.AddSeasonCommand = ReactiveCommand.Create(() =>
            //{
            //    SeriesViewModel svm = new SeriesViewModel();
            //    svm.SeasonEntity = this.NewSeason;
            //    svm.EpisodeEntity = this.Episode;
            //    return svm;
            //});

            int? lastMovieId = DataController.MovieProperties.LastMoveID;

            this.CurrentMovie = DataController.SandboxEntities.Movies.Find(lastMovieId);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MovieViewModel"/> class.
        /// </summary>
        /// <param name="movie">The movie<see cref="Models.Movies"/>.</param>
        public MovieViewModel(Models.Movies movie) : this()
        {
            //this.Movie = movie;
            CurrentMovie = movie;
        }

        #endregion Constructors

        #region Properties

        public string MovieTitle
        {
            get => movieTitle; set => this.RaiseAndSetIfChanged(ref movieTitle, value);

        }

        // Property Year
        /// <summary>
        /// Gets or sets the year.
        /// </summary>
        /// <value>
        /// The year.
        /// </value>
        /// <autogeneratedoc />
        public int Year { get => year; set => this.RaiseAndSetIfChanged(ref year, value); }

        public bool ShowCommandPanel { get; set; } = true;

        /// <summary>
        /// Gets the AddSeasonCommand.
        /// </summary>
        //public ReactiveCommand<Unit, SeriesViewModel> AddSeasonCommand { get; }

        /// <summary>
        /// Gets or sets the Chapters.
        /// </summary>
        public ReactiveCommand<Unit, Unit>? Chapters { get; set; }

        /// <summary>
        /// Gets or sets the Create.
        /// </summary>
        public ReactiveCommand<Unit, Unit>? Create { get; set; }

        /// <summary>
        /// Gets or sets the DirectorList.
        /// </summary>
       // public List<Models.Director>? DirectorList { get => this.directorList; set => this.directorList = value; }

        /// <summary>
        /// Gets or sets the Edit.
        /// </summary>
        public ReactiveCommand<Unit, Unit>? Edit { get; set; }

        /// <summary>
        /// Gets or sets the FoundMovie.
        /// </summary>
        public MovieBase? FoundMovie { get => this.foundMovie; set => this.foundMovie = value; }

        /// <summary>
        /// Gets or sets the MetaData.
        /// </summary>
        public ReactiveCommand<Unit, Unit>? MetaData { get; set; }

        /// <summary>
        /// Gets or sets the ProgressPercent.
        /// </summary>
        // public int ProgressPercent { get => this.progressPercent; set => this.RaiseAndSetIfChanged(ref this.progressPercent, value); }

        /// <summary>
        /// Gets or sets the Search.
        /// </summary>
        //public ReactiveCommand<Unit, Unit>? Search { get; set; }

        /// <summary>
        /// Gets the SeriesList.
        /// </summary>
        // public List<Models.Series>? SeriesList => Models.DataController.SeriesList;

        #endregion Properties

        #region Methods

        //public void DelBookmark()
        //{
        //    if (this.CurrentBookmark != null && this.CurrentMovie != null)
        //    {
        //        if (this.CurrentMovie.DeleteBookmark(this.CurrentBookmark))
        //        {
        //            this.CurrentBookmark = null;
        //        }
        //    }
        //}

        public void PlayMovieFile()
        {
            if (this.CurrentMovie != null)
            {
                string moviePath = this.CurrentMovie.MoviePath;

                if (!string.IsNullOrEmpty(moviePath))
                {
                    FFMpegSupport.PlayMovie(moviePath);
                }
            }
        }

        //public void PlayBookmark()
        //{
        //    if (this.CurrentBookmark != null && this.CurrentMovie != null)
        //    {
        //        string moviePath = this.CurrentMovie.MoviePath;

        //        if (!string.IsNullOrEmpty(moviePath))
        //        {
        //            FFMpegSupport.PlayMovie(moviePath, this.CurrentBookmark);
        //        }
        //    }
        //}

        //public async void NewCastMember()
        //{
        //    Cast returnedValue = await ViewModelSupport.AddCastMember(this.CurrentMovie);
        //}

        //public void RepeatLast()
        //{
        //    ViewModelSupport.DoRepeatLast(this.CurrentMovie, this.CurrentBookmark, this);
        //}

        //public void NewPoster()
        //{
        //    ViewModelSupport.AddPoster(this.CurrentMovie, this);
        //}

        //public async void NewBookmark()
        //{
        //    double time = 1;
        //    int mId = this.CurrentMovie.Id;
        //    Bookmark bookmark = new Bookmark()
        //    {
        //        Name = "<new>",
        //        Time = time,
        //        MovieID = mId,
        //        Type = "BOOKMARK"
        //    };

        //    await ViewModelSupport.NewBookmark(bookmark, this.CurrentMovie, this);
        //}

        //public void OtherMovies()
        //{
        //    ViewModelSupport.OtherMovieList(this.CurrentMovie);
        //}

        //public void ReloadBookmarks()
        //{
        //    ViewModelSupport.DoReloadBookmarks(this.CurrentMovie);
        //}

        //public void PlayFromLast()
        //{
        //    if (this.CurrentMovie != null && this.CurrentMovie.Bookmarks.Count > 0)
        //    {
        //        Bookmark bookmark = this.CurrentMovie.Bookmarks.Last();
        //        string moviePath = this.CurrentMovie.MoviePath;

        //        if (!string.IsNullOrEmpty(moviePath))
        //        {
        //            FFMpegSupport.PlayMovie(moviePath, bookmark);
        //        }
        //    }
        //}

        //public async void EditBookmark()
        //{
        //    this.CurrentBookmark = await ViewModelSupport.EditTheBookmark(this.CurrentBookmark, this, this.CurrentMovie);
        //}

        //public async void EditActor()
        //{
        //    ViewModelSupport.EditCastMember(this.CurrentCastMember);
        //}

        public void SetMovie(Movies inMovie)
        {
            this.CurrentMovie = inMovie;
        }

        /// <summary>
        /// The GetCast.
        /// </summary>
        /// <param name="foundMovie">The foundMovie<see cref="MovieBase?"/>.</param>
        /// <param name="movie">The movie<see cref="Movies"/>.</param>
        public async void GetCast(MovieBase? foundMovie, Movies movie)
        {
            iMovie iMovie = await TmdbSupport.GetMovieData(foundMovie.ID);
            //GetCastData(movie, iMovie);
        }

        /// <summary>
        /// The DoCreate.
        /// </summary>
        private async void DoCreate()
        {
            this.CurrentMovie = new Movies();
            DataController.SandboxEntities.Movies.Add(this.CurrentMovie);
            DataController.SandboxEntities.SaveChanges();

            Window? main = Support.GetMainWindow();
            if (main != null)
                await this.CurrentMovie.EditMovie(main);
        }

        /// <summary>
        /// The DoEdit.
        /// </summary>

        /// <summary>
        /// The DoMetadata.
        /// </summary>
        private void DoMetadata()
        {
            if (this.CurrentMovie != null && !string.IsNullOrEmpty(this.CurrentMovie.MoviePath))
            {
                {
                    //   FFMpegSupport mpegSupport = new FFMpegSupport();

                    this.MpegSupport.GetMapDataFile(this.CurrentMovie.MoviePath);
                }
            }
        }

        /// <summary>
        /// The MpegSupport_CliWrapCompleted.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="CliWrapCompletedEventArgs" /> instance containing the event data.</param>
        //private void MpegSupport_CliWrapCompleted(object sender, CliWrapCompletedEventArgs e)
        //{
        //    if (e.Result == 0)
        //    {
        //        if (e.TaskName == "SetChapters" || e.TaskName == "METADATA")
        //        {
        //            this.CurrentMovie.HasChapters = true;
        //            this.CurrentMovie.Save();
        //            this.IsBusy = false;
        //            this.Progress = "Set Chapters Completed";
        //            if (!string.IsNullOrEmpty(this.CurrentMovie.ErrorText)) this.Progress += " Error: " + this.CurrentMovie.ErrorText;
        //        }
        //    }
        //}

        /// <summary>
        /// The MpegSupport_CliWrapErrored.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="CliWrapErrorEventArgs"/>.</param>
        //private void MpegSupport_CliWrapErrored(object sender, CliWrapErrorEventArgs e)
        //{
        //    if (e.TaskName == "SetChapters")
        //    {
        //        this.CurrentMovie.HasChapters = false;
        //        this.CurrentMovie.Save();
        //        this.IsBusy = false;
        //        this.Progress = "Set Chapters Error";
        //        if (e.Exception != null) this.Progress += " Error: " + e.Exception.Message;
        //    }
        //}

        /// <summary>
        /// The MpegSupport_CliWrapProgress.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="CliWrapProgressEventArgs"/>.</param>
        //private void MpegSupport_CliWrapProgress(object sender, CliWrapProgressEventArgs e)
        //{
        //    if (e != null)
        //    {
        //        this.Progress = e.Progress;
        //        this.ProgressPercent = e.ProgressPercentage;
        //    }
        //}

        /// <summary>
        /// The SetupCommands.
        /// </summary>
        private void SetupCommands()
        {
            this.Accept = ReactiveCommand.Create(DoAccept);
            this.Edit = ReactiveCommand.Create(DoEdit);
            this.Cancel = ReactiveCommand.Create(DoCancel);
            //this.Search = ReactiveCommand.Create(DoSearch);
            this.MetaData = ReactiveCommand.Create(DoMetadata);
            this.Chapters = ReactiveCommand.Create(DoChapters);

            this.Create = ReactiveCommand.Create(DoCreate);
        }

        /// <summary>
        /// The TaskCompleted.
        /// </summary>
        /// <param name="state">The state<see cref="object"/>.</param>
        private void TaskCompleted(object state)
        {
        }

        #endregion Methods
    }
}