using Avalonia;
using Avalonia.Controls;
using Avalonia.Media.Imaging;
using Avalonia.Threading;
using ExCSS;
using LibVLCSharp.Shared;
using ReactiveUI;
using NAudio.Wave;
using NAudio.WaveFormRenderer;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using TaymadeEntities.Models;
using TaymadeEntities.Views;
using System.Diagnostics;

namespace TaymadeEntities.ViewModels
{
    public class PlayerViewModel : MovieViewModelBase
    {

        #region Private Fields

        private LibVLC? _libVlc = null;
        private List<string>? autoCompleteList;
        private Album? currentAlbum;
        private Bookmark? currentBookmark;
        private new Movies? currentMovie;
        private float currentSpeed;
        private AlbumTrack? currentTrack;
        private bool? disposedValue;
        private bool fullScreen = false;
        private bool hasBookmarks;
        private bool hasTracks = true;
        private Bitmap? imageBMP;
        private bool isMusic = true;
        private string? labelContent;
        private int paneWidth = 400;
        private bool paused = false;
        private string? percent = "0 %";
        private int playerHeight = 10;
        private int playerWidth = 800;
        private bool playing = false;
        private double progress = 0;
        private double progressBar = 1.0;
        private int screenHeight = 800;

        /// <summary>
        /// The screen width
        /// </summary>
        /// <autogeneratedoc />
        private int screenWidth = 1200;

        /// <summary>
        /// The screen width list
        /// </summary>
        /// <autogeneratedoc />
        private List<int>? screenWidthList;

        private string? selectedBookmark;
        private ObservableCollection<string>? usedBookmarks;
        private int volume;
        private bool isTrackOnly = false;
        private int progressInt;
        private int imageHeight = 900;
        private int imageWidth = 1800;

        #endregion Private Fields

        #region Public Constructors

        public PlayerViewModel()
        {
            InitialseViewModel();
        }



        public PlayerViewModel(string? currentMovie, bool autoPlay = false)
        {
            InitialseViewModel();
            MoviePath = currentMovie;
            AutoPlay = autoPlay;
            MediaPlayerFull = MediaPlayer;
            IsMusic = false;

            // build used bookmarks list
            //if (CurrentMovie != null && CurrentMovie.Bookmarks != null)
            //{
            //    UsedBookmarks = new ObservableCollection<string>();
            //    foreach (Bookmark bookmark in CurrentMovie.Bookmarks)
            //    {
            //        string stub = Trimnumbersoff(bookmark.Name);
            //        if (UsedBookmarks.IndexOf(stub) < 0)
            //        {
            //            UsedBookmarks.Add(stub);
            //        }
            //    }
            //}
        }

        public PlayerViewModel(Album currentAlbum, bool autoPlay)
        {
            InitialseViewModel();
            MediaPlayerMusic = MediaPlayer;
            IsMusic = true;
            IsTrackOnly = false;
            HasTracks = true;
            AutoPlay = autoPlay;
            Volume = 60;
            this.MediaPlayer.EndReached += MediaPlayer_EndReached;

            this.CurrentAlbum = currentAlbum;

            MoviePath = Support.Support.FixImagePath(CurrentAlbum.AlbumPath);

            List<string>? xspfFiles = Directory.EnumerateFiles(MoviePath, "*.xspf").ToList();
            SetAlbumPath(currentAlbum, xspfFiles);
        }

        public PlayerViewModel(AlbumTrack currentTrack, bool autoPlay)
        {
            InitialseViewModel();
            MediaPlayerMusic = MediaPlayer;
            IsMusic = true;
            IsTrackOnly = true;
            CurrentTrack = currentTrack;
            AutoPlay = autoPlay;
            Volume = 60;
            this.MediaPlayer.EndReached += MediaPlayer_EndReached;

            MoviePath = Support.Support.FixImagePath(CurrentTrack.TrackPath);


        }

        public PlayerViewModel(Movies? currentMovie, bool autoPlay = false, bool full = false)
        {
            InitialseViewModel();
            IsMusic = false;
            if (!full)
            {
                MediaPlayerPlus = MediaPlayer;
                FullScreen = full;
                ScreenHeight = 800;
                ScreenWidth = 1200;
            }
            else
            {
                MediaPlayerFull = MediaPlayer;
                FullScreen = full;
            }
            CurrentMovie = currentMovie;
            MoviePath = currentMovie.MoviePath;
            AutoPlay = autoPlay;

            // build used bookmarks list
            if (CurrentMovie != null && CurrentMovie.Bookmarks != null)
            {
                if (CurrentMovie.Bookmarks.Count == 0) CurrentMovie.Bookmarks = new ObservableCollection<Bookmark>(
                        DataController.BookmarkController.GetBookmarksByMovieId(CurrentMovie.Id)
                        );
                HasBookmarks = true;
                UsedBookmarks = new ObservableCollection<string>();
                foreach (Bookmark bookmark in CurrentMovie.Bookmarks)
                {
                    string stub = Trimnumbersoff(bookmark.Name);
                    if (UsedBookmarks.IndexOf(stub) < 0)
                    {
                        UsedBookmarks.Add(stub);
                    }
                }
            }
        }

        #endregion Public Constructors

        #region Public Properties

        public new int Volume
        {
            get => volume;
            set
            {
                this.RaiseAndSetIfChanged(ref volume, value);
                this.SetVolume(value);
            }
        }
        public AutoCompleteBox? AutoCompleteBox { get; set; }
        public List<string>? AutoCompleteList
        {
            get
            {
                if (autoCompleteList == null)
                    autoCompleteList = DataController.AutoCompleteList;
                return autoCompleteList;
            }

            set => this.RaiseAndSetIfChanged(ref autoCompleteList, value);
        }

        public bool AutoPlay { get; private set; }
        public Bookmark? Bookmark { get; set; }
        public Album? CurrentAlbum
        {
            get => currentAlbum;
            set => this.RaiseAndSetIfChanged(ref currentAlbum, value);
        }

        //public string BookmarkName { get; private set; }
        public float CurrentSpeed
        {
            get => currentSpeed;
            set
            {
                this.RaiseAndSetIfChanged(ref currentSpeed, value);
                this.SetSpeed(value);
            }
        }

        public AlbumTrack? CurrentTrack
        {
            get => currentTrack;
            set => this.RaiseAndSetIfChanged(ref currentTrack, value);
        }

        public int FrameHeight { get; set; } = 480;
        public int FrameWidth { get; set; } = 640;
        public bool FullScreen
        {
            get => fullScreen;
            set => this.RaiseAndSetIfChanged(ref fullScreen, value);
        }

        public bool HasBookmarks
        {
            get => hasBookmarks;
            set => this.RaiseAndSetIfChanged(ref hasBookmarks, value);
        }

        public bool HasTracks
        {
            get => hasTracks;
            set => this.RaiseAndSetIfChanged(ref hasTracks, value);
        }

        public Bitmap? ImageBMP
        {
            get => imageBMP;
            set => this.RaiseAndSetIfChanged(ref imageBMP, value);
        }

        public bool IsMusic
        {
            get => isMusic;
            set => this.RaiseAndSetIfChanged(ref isMusic, value);
        }
        public bool IsTrackOnly
        {
            get => isTrackOnly;
            set => this.RaiseAndSetIfChanged(ref isTrackOnly, value);
        }
        public string? LabelContent
        {
            get => labelContent;
            set => this.RaiseAndSetIfChanged(ref labelContent, value);
        }

        public MediaPlayer? MediaPlayer { get; internal set; }
        public MediaPlayer? MediaPlayerFull { get; internal set; }
        public MediaPlayer? MediaPlayerPlus { get; internal set; }
        public MediaPlayer? MediaPlayerMusic { get; internal set; }


        public new int MusicPlayerHeight { get => playerHeight; set => this.RaiseAndSetIfChanged(ref playerHeight, value); }
        public int MusicPlayerWidth { get => playerWidth; set => this.RaiseAndSetIfChanged(ref playerWidth, value); }
        public int PaneWidth
        {
            get => paneWidth;
            set
            {
                this.RaiseAndSetIfChanged(ref paneWidth, value);
            }
        }

        public string? Percent
        {
            get => percent;
            set => this.RaiseAndSetIfChanged(ref percent, value);
        }

        public bool PlayFromBookmark { get; set; } = false;
        public bool PlayFromLastBookmark { get; private set; }
        //public Movies? Movies { get; internal set; }
        public new double Progress
        {
            get => progress;
            set
            {
                this.RaiseAndSetIfChanged(ref progress, value);
                this.SetPosition((float)value);
            }
        }

        //    public Thickness ProgressMargin =>
        //new Thickness(Progress *18,0, 0, 0 );

        public double ProgressX => Progress * 18;
        public int ProgressInt
        {
            get => progressInt;
            set => this.RaiseAndSetIfChanged(ref progressInt, value);
        }

        public new int ScreenHeight { get => screenHeight; set => this.RaiseAndSetIfChanged(ref screenHeight, value); }
        public List<int>? ScreenSizelist { get; private set; }
        public new int ScreenWidth { get => screenWidth; set => this.RaiseAndSetIfChanged(ref screenWidth, value); }
        public string? SelectedBookmark
        {
            get => selectedBookmark;
            set => this.RaiseAndSetIfChanged(ref selectedBookmark, value);
        }

        public List<float>? SpeedList { get; private set; }
        public DataGrid? TrackGrid { get; set; }

        public ObservableCollection<string>? UsedBookmarks
        {
            get => usedBookmarks;
            set => this.RaiseAndSetIfChanged(ref usedBookmarks, value);
        }

        #endregion Public Properties

        #region Public Methods

        public static Bitmap? GetBMP(string fileName)
        {
            Bitmap? retBMP = null;

            if (System.IO.File.Exists(fileName))// && GetOS() == "WinNT")
            {
                System.Drawing.Bitmap sBitmap = new System.Drawing.Bitmap(System.Drawing.Image.FromFile(fileName));

                using (System.IO.MemoryStream memory = new System.IO.MemoryStream())
                {
                    sBitmap.Save(memory, System.Drawing.Imaging.ImageFormat.Bmp);
                    memory.Position = 0;

                    retBMP = new Bitmap(memory);
                }
            }
            return retBMP;
        }

        public static string Trimnumbersoff(string name)
        {
            int i = name.Length - 1;

            int j = name.Length - 1;

            while (i > 0 && char.IsDigit(name[i]))
            {
                i -= 1;
            }

            name = name.Substring(0, i + 1);
            return name;
        }

        public void AddActualBookmark(Bookmark bookmark)
        {
            if (CurrentMovie != null)
            {
                CurrentMovie.Bookmarks.Add(bookmark);
                DataController.SandboxEntities.Bookmarks.Add(bookmark);
                DataController.SandboxEntities.SaveChanges();
                CurrentMovie.ModifiedOn = DateTime.Now;
                CurrentMovie.ImagesCount = CurrentMovie.Bookmarks.Count;
                CurrentMovie.Save();

                Bookmark = bookmark;
                Bookmark = bookmark;

                CurrentBookmark = bookmark;
            }
        }

        public void AddMark(string bookmarkName)
        {
            if (CurrentMovie != null && CurrentMovie.Bookmarks != null)
            {
                Bookmark oldBookmark = CurrentMovie.GetLastBookmark();

                bookmarkName = DoAutoComplete(bookmarkName);

                double time = 1;

                if (MediaPlayer != null)
                {
                    if (MediaPlayer.IsPlaying)
                    {
                        time = MediaPlayer.Length * MediaPlayer.Position / 1000;
                    }
                    else if (!MediaPlayer.IsPlaying && paused)
                    {
                        time = MediaPlayer.Length * MediaPlayer.Position / 1000;
                    }
                    else if (oldBookmark != null && oldBookmark.Time != null)
                    {
                        time = oldBookmark.Time.Value + 10;
                    }

                    //BookmarkName = bookmarkName;
                    //MovieName = CurrentMovie.MovieName;

                    int mId = CurrentMovie.Id;
                    Bookmark bookmark = new Bookmark()
                    {
                        Name = bookmarkName,
                        Time = time,
                        MovieID = mId,
                        Type = "BOOKMARK"
                    };

                    AddActualBookmark(bookmark);

                    Bookmark = bookmark;
                    CurrentBookmark = bookmark;
                }
            }
        }

        public void CloseApp()
        {
            if (Caller != null)
            {
                Caller.Close();
            }
        }

        public void DecVolume()
        {
            if (MediaPlayer != null)
            {
                this.SetVolume(MediaPlayer.Volume + 1);
            }
        }

        public new void Dispose()
        {
            MediaPlayer?.Dispose();
            _libVlc?.Dispose();
            ImageBMP?.Dispose();
            base.Dispose();
        }

        public void Grab()
        {
            if (!MediaPlayer.IsPlaying)
            {
                AddBookmark();
                GrabBookmarkImage();
                SetPercent();
            }
        }

        public async void GrabBookmarkImage(
            TaymadeEntities.Models.Movies Movie,

            int offset = 0
        )
        {
            if (Movie != null && Bookmark != null && Bookmark.Time != null)
            {
                string ffmpegFilePath = @"C:\Program Files\FFMpeg\bin\ffmpeg.exe";

                long Medialengthms = MediaPlayer.Length;

                double posms = Medialengthms * MediaPlayer.Position;

                TimeSpan ts = TimeSpan.FromMilliseconds(posms);

                string ffmpegCommand = "-i " + '"' + Movie.MoviePath + '"' + " -ss " + ts.ToString() + " -frames:v 1 ";
                //    string? ffprobeFilePath = null;
                var videoPath = Support.Support.FixImagePath(Movie.MoviePath);

                //float pos = MediaPlayer.Position;
                double tempTime = ts.TotalSeconds;

                string winThumbnailpath =
                    System.IO.Path.GetDirectoryName(Movie.MoviePath)
                    + @"\"
                    + System.IO.Path.GetFileNameWithoutExtension(Movie.MoviePath)
                    + tempTime.ToString("0.######").Trim()
                    + ".BMP";

                Bookmark.Time = tempTime;
                Bookmark.ImagePath = winThumbnailpath;

                uint width = (uint)FrameWidth;
                uint height = (uint)FrameHeight;

                if (ImageBMP != null)
                {
                    width = (uint)ImageBMP.Size.Width;
                    height = (uint)ImageBMP.Size.Height;
                }

                MediaPlayer.NextFrame();
                bool success = MediaPlayer.TakeSnapshot(0, winThumbnailpath, width, height);
                while (!success)
                {
                    success = MediaPlayer.TakeSnapshot(0, winThumbnailpath, width, height);
                }

                Bookmark.Save();
                //    // temporarily add 2 to time
                //    string dirSep = @"\";
                //    //if (Support.GetOS() != "WinNT")
                //    //{
                //    //    ffmpegFilePath = @"/usr/bin/ffmpeg";
                //    //    ffprobeFilePath = @"/usr/bin/ffprobe";
                //    //    dirSep = "/";
                //    //}
                //    string thumbnailPath = Support.FixImagePath(
                //        System.IO.Path.GetDirectoryName(videoPath)
                //            + dirSep
                //            + System.IO.Path.GetFileNameWithoutExtension(videoPath)
                //            + tempTime.ToString().Trim()
                //            + ".BMP"
                //    );
                //    try
                //    {
                //        tempTime = tempTime + offset;
                //        var serviceProvider = new ServiceCollection()
                //            .AddMediaToolkit(ffmpegFilePath, ffprobeFilePath)
                //            .BuildServiceProvider();
                //        // Get metadata
                //        var service = serviceProvider.GetService<IMediaToolkitService>();
                //        var metadataTask = new FfTaskGetMetadata(videoPath);
                //        if (service != null)
                //        {
                //            var metadataResult = await service.ExecuteAsync(metadataTask);
                //            var saveThumbnailTask = new FfTaskSaveThumbnail(
                //                videoPath,
                //                thumbnailPath,
                //                TimeSpan.FromSeconds(tempTime)
                //            );

                //            await service.ExecuteAsync(saveThumbnailTask);
                //            bookmark.ImagePath = Support.FixPathBack(winThumbnailpath);
                //            bookmark.Save();
                //            Bitmap? temp = bookmark.ImageBMP;

                //            string info =
                //                "Bookmark Image Id="
                //                + bookmark.Id.ToString()
                //                + "|path="
                //                + bookmark.ImagePath;
                //            Console.Out.WriteLine(info);

                //            ImageBMP = temp;

                //        }
                //    }
                //    catch (Exception ex)
                //    {
                //        Console.WriteLine(ex.ToString());
                //    }
            }
        }

        public void IncVolume()
        {
            if (MediaPlayer != null)
            {
                this.SetVolume(MediaPlayer.Volume / 100 + .05);
            }
        }

        public void Minus0p5()
        {
            MoveBy(-0.50);
        }

        public void Minus1()
        {
            MoveBy(-1.0);
        }

        public void Minus10()
        {
            MoveBy(-10.0);
        }

        public void Minus5()
        {
            MoveBy(-5.0);
        }

        //public PlayerControl? Player { get; internal set; }
        public void MoveByValue()
        {
            Window? main = Support.Support.GetMainWindow();

            if (main != null)
            {
                //VideoPlayer vp = main.FindControl<VideoPlayer>("VideoPlay");
                //if (vp != null)
                //{
                //    string moveValue = vp.moveTxt.Text;
                //    double dbValue = Double.Parse(moveValue);
                //    MoveBy(dbValue);
                //}
            }
        }

        public void NextBookmark()
        {
            if (IsMusic)
            {
                NextAlbumTrack();
            }
            else
                if (CurrentBookmark != null)
                {
                    int index = CurrentMovie.Bookmarks.IndexOf(CurrentBookmark);
                    if (index < CurrentMovie.Bookmarks.Count - 1)
                    {
                        CurrentBookmark = CurrentMovie.Bookmarks.ToList()[index + 1]; ;
                        DoGotoBookmark();
                    }
                }
        }

        /// <summary>
        /// Pauses this instance.
        /// </summary>
        /// <autogeneratedoc />
        public void Pause()
        {
            if (MediaPlayer.IsPlaying)
            {
                MediaPlayer.Pause();
                paused = true;
            }
            else
            {
                MediaPlayer.Play();
                paused = false;
            }
        }

        public void Play()
        {
            if (Design.IsDesignMode)
            {
                return;
            }

            Media? media = null;

            if (!string.IsNullOrEmpty(MoviePath) && _libVlc != null && MediaPlayer != null)
            {
                if (!playing)
                {
                    if (string.IsNullOrEmpty(MoviePath))
                    {
                        media = new Media(_libVlc, new Uri("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"));
                        MediaPlayer.Play(media);
                    }
                    else
                    {
                        media = new Media(_libVlc, new Uri(MoviePath));

                        if (CurrentBookmark != null)
                        {
                            //CurrentBookmark = Bookmark;
                            DoGotoBookmark(media);
                        }
                        else MediaPlayer.Play(media);

                        MediaPlayer.Mute = false;
                        MediaPlayer.Volume = Volume;

                        new DispatcherTimer(TimeSpan.FromMilliseconds(60), DispatcherPriority.Normal, TimerTick).Start();
                    }
                    paused = false;
                    playing = true;
                }
                else
                    Pause();
            }
        }

        public void Plus1()
        {
            MoveBy(1.0);
        }

        public void Plus10()
        {
            MoveBy(10.0);
        }

        public void Plus20()
        {
            MoveBy(20.0);
        }

        public void Plus5()
        {
            MoveBy(5.0);
        }

        public void PrevBookmark()
        {
            if (IsMusic)
            {
                PrevAlbumTrack();
            }
            else
                if (CurrentBookmark != null)
                {
                    int index = CurrentMovie.Bookmarks.IndexOf(CurrentBookmark);
                    if (index > 0)
                    {
                        CurrentBookmark = CurrentMovie.Bookmarks.ToList()[index - 1];
                        DoGotoBookmark();
                    }
                }
        }

        public void SeekCurrentBookmark()
        {
            if (CurrentBookmark != null && CurrentBookmark.Time != null)
            {
                //CurrentBookmark.SetImageBMP();
                MediaPlayer.SeekTo(TimeSpan.FromSeconds(CurrentBookmark.Time.Value));
                SetPercent();
            }
        }

        public void SetSpeed(int speedIndex)
        {
            if (SpeedList != null && speedIndex >= 0 && speedIndex < SpeedList.Count)
            {
                float speed = SpeedList[speedIndex];
                MediaPlayer?.SetRate(speed);
                LabelContent = "Speed: " + speed.ToString();
            }
        }

        public void SetSpeed(float speed)
        {
            MediaPlayer?.SetRate(speed);
            LabelContent = "Speed: " + speed.ToString();
        }

        public void SetVolume(double? value)
        {
            if (value != null && MediaPlayer != null)
            {
                if (value < 0) value = 0;
                if (value > 1) value = 1;
                MediaPlayer.Volume = (int)(value * 100);
                //Volume = MediaPlayer.Volume;
            }
        }

        public void SetVolume(int value)
        {
            if (MediaPlayer != null)
            {
                MediaPlayer.Volume = value;
                //Volume = MediaPlayer.Volume;
            }
        }

        public void Stop()
        {
            MediaPlayer.Stop();
            playing = false;
        }

        #endregion Public Methods

        #region Internal Methods

        internal void MoveBy(double moveBy)
        {
            double time = 0;
            if (MediaPlayer != null)
            {
                if (MediaPlayer.IsPlaying)
                {
                    time = MediaPlayer.Length * MediaPlayer.Position;
                }
                else if (!MediaPlayer.IsPlaying && paused)
                {
                    time = MediaPlayer.Length * MediaPlayer.Position;
                }

                time += moveBy * 1000;

                if (time > MediaPlayer.Length) time = MediaPlayer.Length - 5000;

                MediaPlayer.SeekTo(TimeSpan.FromMilliseconds(time));

                //MainWindowViewModel? vm = GetMainWindowViewModel();
                SetPercent();

                Console.Out.WriteLine("Percent=" + Percent);
            }
        }

        internal void MoveToStart()
        {
            MediaPlayer?.SeekTo(TimeSpan.FromMilliseconds(0));
        }

        internal void OnDialogOpened()
        {
            // check to see if CurrentMovie exists and if so, play it
            if ((CurrentMovie != null || !string.IsNullOrEmpty(MoviePath)) && MediaPlayer != null && AutoPlay)
            {
                if (PlayFromBookmark && CurrentBookmark != null)
                {
                    DoGotoBookmark();
                }
                Play();
            }

            if ((CurrentAlbum != null || !string.IsNullOrEmpty(MoviePath)) && MediaPlayer != null && AutoPlay)
            {
                Play();
            }
        }

        /// <summary>
        /// Speeds the changed.
        /// </summary>
        /// <param name="speed">The speed.</param>
        /// <autogeneratedoc />
        internal void SpeedChanged(float speed)
        {
            MediaPlayer.SetRate(speed);
            LabelContent = "Speed: " + speed.ToString();
        }

        internal void VolumeDown()
        {
            SetVolume(MediaPlayer?.Volume - 0.1);
        }

        internal void VolumeUp()
        {
            SetVolume(MediaPlayer?.Volume + 0.1);
        }

        #endregion Internal Methods

        #region Private Methods

        private void AddBookmark()
        {
            string bookmarkName = "<new>";

            Window? main = Support.Support.GetMainWindow();

            if (main != null)
            {
                if (AutoCompleteBox != null && !string.IsNullOrEmpty(AutoCompleteBox.Text))
                {
                    bookmarkName = AutoCompleteBox.Text;
                }

                AddMark(bookmarkName);

                string stub = Trimnumbersoff(bookmarkName);
                if (UsedBookmarks == null) UsedBookmarks = new ObservableCollection<string>();

                if (UsedBookmarks.IndexOf(stub) < 0)
                {
                    UsedBookmarks.Add(stub);
                    UsedBookmarks = new ObservableCollection<string>(UsedBookmarks.OrderBy(x => x));
                }

                AutoCompleteBox.Text = stub;

                Bookmark bk = CurrentMovie.Bookmarks.Where(x => bookmarkName == stub).FirstOrDefault();
                SelectedBookmark = stub;
            }
            //DoSelectBookmark();

            //MainWindow? main = Support.Support.GetWindow() as MainWindow;
            //if (main != null)
            //{
            //    ComboBox? usedBooks = main.FindControl<ComboBox>("UsedBooks");
            //    if (usedBooks != null)
            //        usedBooks.SelectedItem = stub;

            //    // DoSelectBookmark();
            //    AutoComplete.Text = stub;
            //}
        }

        private string DoAutoComplete(string bookmarkName)
        {
            string? oldText = bookmarkName;
            if (CurrentMovie != null)
            {
                //MainWindowViewModel? vm = GetMainWindowViewModel();

                List<Bookmark> found = CurrentMovie.Bookmarks
                    .ToList()
                    .FindAll(
                        b =>
                            b.Name.ToLower().Contains(oldText.ToLower())
                            && b.Name.ToLower().IndexOf(bookmarkName.ToLower()) == 0
                    );

                if (found != null && found.Count > 0)
                {
                    oldText += (found.Count).ToString();
                }
            }
            return oldText;
        }

        private void DoGotoBookmark(Media media = null)
        {
            if (CurrentBookmark != null)
            {
                if (MediaPlayer != null && CurrentBookmark.Time != null)
                {
                    //CurrentBookmark.SetImageBMP();
                    if (media != null) MediaPlayer.Play(media);
                    else MediaPlayer.Play();

                    MediaPlayer.SeekTo(TimeSpan.FromSeconds(CurrentBookmark.Time.Value));
                    SetPercent();
                    Console.Out.WriteLine("Playing from Bookmark : " + CurrentBookmark.Name);
                }
            }
        }

        private void GetAvaloniaBMP()
        {
            if (!string.IsNullOrEmpty(Support.Support.FixImagePath(CurrentBookmark.ImagePath)))
            {
                string fileName = Support.Support.FixImagePath(CurrentBookmark.ImagePath);
                if (System.IO.File.Exists(fileName))
                {
                    ImageBMP = GetBMP(fileName);
                }
            }
        }

        private void GetAvaloniaBMP(Bookmark bookmark)
        {
            if (!string.IsNullOrEmpty(Support.Support.FixImagePath(bookmark.ImagePath)))
            {
                string fileName = Support.Support.FixImagePath(bookmark.ImagePath);
                if (System.IO.File.Exists(fileName))
                {
                    ImageBMP = GetBMP(fileName);
                }
            }
        }

        private void GrabBookmarkImage()
        {
            if (CurrentMovie != null && Bookmark != null)
            {
                GrabBookmarkImage(CurrentMovie, 0);
                System.Threading.Thread.Sleep(1000);
                var bmp = Bookmark.ImageBMP;
                Bookmark.SetImageBMP();

                Bookmark.Save();
                CurrentBookmark = Bookmark;
                GetAvaloniaBMP(Bookmark);
                Console.Out.WriteLine("New Bookmark=" + Bookmark.Id.ToString());
            }
        }

        private void InitialseViewModel()
        {
            _libVlc = new LibVLC(new[]
{
    "--verbose=2"
});

            //_libVlc.Log += (s, e) =>
            //{
            //    Debug.WriteLine($"{e.Level}: {e.Message}");
            //};

            MediaPlayer = new MediaPlayer(_libVlc);

            ScreenSizelist = new List<int>() { 400, 800, 1200, 1400, 1600, 1800 };

            SpeedList = new List<float>() { 0.1F, 0.2F, 0.5F, 1, 1.5F, 2, 3, 4 };
            CurrentSpeed = 1;
        }


        private void MediaPlayer_EndReached(object? sender, EventArgs e)
        {
            if (IsMusic && CurrentAlbum != null && CurrentTrack != null)
            {
                NextAlbumTrack();
            }
        }

        public int ImageHeight
        {
            get => imageHeight;
            set => this.RaiseAndSetIfChanged(ref imageHeight, value);
        }

        public int ImageWidth
        {
            get => imageWidth;
            set => this.RaiseAndSetIfChanged(ref imageWidth, value);
        }

        public Bitmap? RenderBitMap(int width = 1800, int topHeight = 450, int bottomHeight = 450)
        {
            var myRendererSettings = new StandardWaveFormRendererSettings();
            myRendererSettings.Width = width;
            myRendererSettings.TopHeight = topHeight;
            myRendererSettings.BottomHeight = bottomHeight;

            var myPeakProvider = new AveragePeakProvider(4); // e.g. 4
            var renderer = new WaveFormRenderer();
            var audioFileReader = new AudioFileReader(
                Support.Support.FixImagePath(CurrentTrack.TrackPath)
                );
            System.Drawing.Image image = renderer.Render(audioFileReader, myPeakProvider, myRendererSettings);

            Bitmap? imageAv = Support.Support.GetBMPFromBitmap(image);
            return imageAv;
        }

        private void NextAlbumTrack()
        {
            if (CurrentAlbum == null && CurrentTrack.Album == null) return;
            CurrentAlbum = CurrentTrack.Album;
            int index = CurrentAlbum.AlbumTracks.IndexOf(CurrentTrack);
            if (index < CurrentAlbum.AlbumTracks.Count - 1)
            {
                CurrentTrack = CurrentAlbum.AlbumTracks[index + 1];
                ImageHeight = 500;
                ImageWidth = 1800;
                ImageBMP = RenderBitMap(ImageWidth, ImageHeight / 2, ImageHeight / 2);
                if (!string.IsNullOrEmpty(CurrentTrack.TrackPath))
                {
                    if (CurrentTrack.TrackPath.Contains("file://"))
                    {
                        // is a uri
                        Uri mrl = new Uri(CurrentTrack.TrackPath);
                        CurrentTrack.TrackPath = mrl.LocalPath;
                    }
                    MoviePath = Support.Support.FixImagePath(CurrentTrack.TrackPath);
                    if (File.Exists(MoviePath))
                    {
                        if (AutoPlay)
                        {
                            if (MediaPlayer.Media != null) MediaPlayer.Media.Dispose();
                            playing = false;
                            Avalonia.Threading.Dispatcher.UIThread.Post(() =>
                            {
                                Media? media = null;
                                media = new Media(_libVlc, new Uri(MoviePath));
                                MediaPlayer.Media = media;

                                MediaPlayer.Play();
                                playing = true;
                                MediaPlayer.Position = 0;
                                if (TrackGrid != null)
                                {
                                    TrackGrid.ScrollIntoView(CurrentTrack, null);
                                }
                            });
                        }
                    }
                }
            }
            else CurrentTrack = null;
        }

        private async Task<Media> ParseMedia()
        {
            Media media = new Media(_libVlc, new Uri(MoviePath));
            await media.Parse(MediaParseOptions.ParseNetwork);
            var mp = media.SubItems.First();
            return mp;
        }

        private void PrevAlbumTrack()
        {
            int index = CurrentAlbum.AlbumTracks.IndexOf(CurrentTrack);
            if (index > 0)
            {
                CurrentTrack = CurrentAlbum.AlbumTracks[index - 1];
                MoviePath = Support.Support.FixImagePath(CurrentTrack.TrackPath);
                if (AutoPlay)
                {
                    playing = false;
                    Play();
                }
            }
            else CurrentTrack = null;
        }

        private async void SetAlbumPath(Album currentAlbum, List<string> xspfFiles)
        {
            AutoPlay = false;
            if (xspfFiles != null && xspfFiles.Count > 0)
            {
                MoviePath = xspfFiles.First();
                Media? mp = await ParseMedia();
                if (mp != null && mp.SubItems.Count > 0)
                {
                    Media? track = mp.SubItems[0];
                    Uri mrl = new Uri(track.Mrl);
                    MoviePath = Support.Support.FixImagePath(mrl.LocalPath);
                    CurrentTrack = CurrentAlbum.AlbumTracks.First();
                }
                AutoPlay = true;
            }
            else if (currentAlbum != null)
            {
                CurrentTrack = CurrentAlbum.AlbumTracks.First();
                MoviePath = Support.Support.FixImagePath(CurrentTrack.TrackPath);
            }
            ImageHeight = 500;
            ImageWidth = 1800;
            ImageBMP = RenderBitMap(ImageWidth, ImageHeight / 2, ImageHeight / 2);
            AutoPlay = true;
        }
        private void SetPercent()
        {
            if (!playing) return;
            long movieLengtthMsecs = MediaPlayer.Time;

            double percent = MediaPlayer.Position * 100;
            progress = percent;
            ProgressInt = (int)percent;
            this.RaisePropertyChanged(nameof(Progress));
            this.RaisePropertyChanged(nameof(ProgressX));

            // get movie current time msecs

            TimeSpan elapsedTime = TimeSpan.FromMilliseconds(movieLengtthMsecs);

            Percent = elapsedTime.ToString(@"hh\:mm\:ss") + " - " + (percent).ToString("0.00") + "%";
        }

        private void SetPosition(float position)
        {
            // position is the percentage along film track

            MediaPlayer.Position = position / 100;
        }
        /// <summary>
        /// Timers the tick.
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="e">The <see cref="EventArgs"/> instance containing the event data.</param>
        /// <autogeneratedoc />
        private void TimerTick(object sender, EventArgs e)
        {
            SetPercent();
        }

        #endregion Private Methods
    }
}