//-----------------------------------------------------------------------
// <copyright file="FFMpegSupport.cs" company="Taymade Software Services">
//     Copyright (c) Taymade Software Services. All rights reserved.
// </copyright>
// <created>14/05/2022 14:53:01 14/05/2022 14:53:01 </created>
// <author>Doug Taylor</author>
//-----------------------------------------------------------------------

using System.ComponentModel;

namespace TaymadeEntities.Support
{
    /// <summary>
    /// Defines the <see cref="CliWrapProgressEventArgs" />.
    /// </summary>
    public class CliWrapProgressEventArgs : System.ComponentModel.ProgressChangedEventArgs
    {
        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="CliWrapProgressEventArgs"/> class.
        /// </summary>
        /// <param name="progressPercentage">The progressPercentage<see cref="int"/>.</param>
        /// <param name="userState">The userState<see cref="object?"/>.</param>
        public CliWrapProgressEventArgs(int progressPercentage, object? userState) : base(progressPercentage, userState)
        {
            TaskName = string.Empty;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the Progress.
        /// </summary>
        public string? Progress { get;  set; }

        /// <summary>
        /// Gets or sets the TaskName.
        /// </summary>
        public string TaskName { get;  set; }

        #endregion
    }

    /// <summary>
    /// 
    /// </summary>
    /// <seealso cref="System.ComponentModel.ProgressChangedEventArgs" />
    /// <autogeneratedoc />
    public class MovieProgressEventargs : ProgressChangedEventArgs
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MovieProgressEventargs"/> class.
        /// </summary>
        /// <param name="progressPercentage">The percentage of an asynchronous task that has been completed.</param>
        /// <param name="userState">A unique user state.</param>
        /// <autogeneratedoc />
        public MovieProgressEventargs(int progressPercentage, object? userState) : base(progressPercentage, userState)
        {

        }

        /// <summary>
        /// Gets or sets the information.
        /// </summary>
        /// <value>
        /// The information.
        /// </value>
        /// <autogeneratedoc />
        public string Info { get; set; }

        public new int ProgressPercentage { get; set; }
    }

    /// <summary>
    /// 
    /// </summary>
    /// <seealso cref="System.EventArgs" />
    /// <autogeneratedoc />
    public class MissingFileInfoArgs : System.EventArgs
    {
        public string? Info { get; set; }

        public double? Progress { get; set; }
    }
}
