using Avalonia;
using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.Markup.Xaml;
using ReactiveUI;

//using ImageViewer.ViewModels;
using System;
using System.IO;
using System.Threading.Tasks;
using TaymadeEntities.Dialogs;
using TaymadeEntities.Models;
using TaymadeEntities.Support;
using TaymadeEntities.ViewModels;

namespace TaymadeEntities.Controls;

public partial class ImageSetControl : UserControl
{
    #region Public Fields

    /// <summary>
    /// Defines the imageSetViewModel.
    /// </summary>
    public ImageSetViewModel? imageSetViewModel;

    #endregion Public Fields

    #region Public Constructors

    public ImageSetControl()
    {
        InitializeComponent();
        if (DataContext == null || DataContext is not ImageSetViewModel) DataContext = new ImageSetViewModel();

        imageSetViewModel = DataContext as ImageSetViewModel;

        this.Initialized += ImageSetControl_Initialized;
    }

    private void ImageSetControl_Initialized(object? sender, EventArgs e)
    {
        if (imageSetViewModel != null)
            imageSetViewModel.PlayButton = this.btnPlayContent;
    }

    #endregion Public Constructors

    #region Private Methods



    /// <summary>
    /// Handles the ActionCompleted event of the Support control.
    /// </summary>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">The <see cref="MovieCompletedEventArgs"/> instance containing the event data.</param>
    /// <autogeneratedoc />
    private void Support_ActionCompleted(object sender, MovieCompletedEventArgs e)
    {
        imageSetViewModel.MissingInfo = e.Result.ToString();
    }

    /// <summary>
    /// Supports the progress information.
    /// </summary>
    /// <param name="sender">The sender.</param>
    /// <param name="e">The e.</param>
    /// <autogeneratedoc />
    private void Support_ProgressInformation(object sender, MovieProgressEventargs e)
    {
        //imageSetViewModel.MissingInfo = e.Info;
        //if (e.ProgressPercentage > 0) imageSetViewModel.MovieProgress = e.ProgressPercentage;
    }

    private void dgImageFolders_SelectionChanged(object? sender, SelectionChangedEventArgs e)
    {
        // there is a new CurrentImageFolder so select the first SubFolder in its list if it has one
        //if (e.AddedItems[0] != null && e.AddedItems[0] is MovieImage && this.IsInitialized)
        //{
        //    MovieImage? movieImage = e.AddedItems[0] as MovieImage;
        //    if (movieImage != null)
        //    {
        //        if (imageSetViewModel.CurrentImageFolder.Id == movieImage.Id)
        //        {
        //            return;
        //        }

        //        if (movieImage.SubDirectoryList == null || movieImage.SubDirectoryList.Count == 0)
        //        {
        //            // get new list

        //        }

        //        if (movieImage.SubDirectoryList != null &&
        //            movieImage.SubDirectoryList.Count >= 0)
        //        {
        //            if (imageSetViewModel != null)
        //            {
        //                imageSetViewModel.RootFolder?.CurrentSubFolder = movieImage.SubDirectoryList[0];
        //                imageSetViewModel.RootFolder?.LastId = imageSetViewModel.RootFolder?.CurrentSubFolder.Id;
        //                imageSetViewModel.RootFolder.Save();
        //            }
        //        }
        //    }
        //}
    }

    

    private void dgItemImages_SelectionChanged(object? sender, SelectionChangedEventArgs e)
    {
        if (imageSetViewModel.RootFolder?.CurrentSubFolder?.ImageItems != null
            || imageSetViewModel.RootFolder.CurrentSubFolder.ImageItems.IsPlaying != null)
            return;
        // set CurrentSubFolder folder lastimagename to this item
        if (e.AddedItems.Count >= 1 && e.AddedItems[0] != null && e.AddedItems[0] is ImageItem)
        {
            if (imageSetViewModel != null && imageSetViewModel.RootFolder != null)
            {
                ImageItem? imageItem = e.AddedItems[0] as ImageItem;
                imageSetViewModel.RootFolder.CurrentSubFolder.LastImageName = imageItem.ImageName;
                imageSetViewModel.RootFolder.CurrentSubFolder.Save();
            }
        }
    }

    private void TabControl_SelectionChanged(object? sender, SelectionChangedEventArgs e)
    {
        // see if the viewModel and rootfolder are present
        if (imageSetViewModel != null && imageSetViewModel.RootFolder != null)
        {
            // if the currentsubfolder is not null set RootFolder Last Id
            if (imageSetViewModel.RootFolder.CurrentImageFolder != null)
            {
                imageSetViewModel.RootFolder.LastId = imageSetViewModel.RootFolder.CurrentImageFolder.Id;

                if (imageSetViewModel.RootFolder.CurrentSubFolder != null)
                {
                    if (imageSetViewModel.RootFolder.CurrentSubFolder.Movies != null || imageSetViewModel.RootFolder.CurrentSubFolder.MovieId > 0)
                    {
                        imageSetViewModel.RootFolder.HasMovieEntity = true;
                        if (imageSetViewModel.RootFolder.CurrentSubFolder.Movies == null)
                        {
                            imageSetViewModel.RootFolder.CurrentSubFolder.Movies = DataController.SandboxEntities.Movies.Find(
                                imageSetViewModel.RootFolder.CurrentSubFolder.MovieId);
                        }
                        imageSetViewModel.RootFolder.CurrentMovie = imageSetViewModel.RootFolder.CurrentSubFolder.Movies;
                    }
                }
                imageSetViewModel.RootFolder.Save();
            }
        }
    }

    private void Reloadpictures_Click(object? sender, RoutedEventArgs e)
    {
        if (DataContext != null && DataContext is ImageSetViewModel vm)
        {
            vm.DoReloadPictures();
            vm.ImageSetControl = this;
            vm.SetImageRow();
        }
    }

    private void MenuItem_Click(object? sender, RoutedEventArgs e)
    {
        if (imageSetViewModel != null)
        {
            if (imageSetViewModel.RootFolder != null && imageSetViewModel.RootFolder.CurrentImageItem != null)
            {
                EntryDialogModel dialogModel = new EntryDialogModel();
                // get an entry dialog
                //EntryDialogInfo info = new EntryDialogInfo()
                //{
                dialogModel.EntryTypeValue = EntryDialogModel.EntryType.Text;
                dialogModel.EntryText = imageSetViewModel.RootFolder.CurrentImageItem.ImagePath;
                dialogModel.MaxStringLength = 150;
                //};
                //dialogModel.Info = info;
                // create dialog
                EntryDialog entryDialog = new TaymadeEntities.Dialogs.EntryDialog(dialogModel);
                //entryDialog.Info = dialogModel;
                //dialogModel.Caller = entryDialog;

                //Visual? main = TaymadeEntities.Support.Support.GetMainWindow();

                ShowEntryDialog(entryDialog, dialogModel);
            }
        }


    }

    private async void ShowEntryDialog(EntryDialog entryDialog, EntryDialogModel dialogModel)
    {
        // show dialog and process if ok
        Window? main = Support.Support.GetMainWindow() as Window;
        bool result = await entryDialog.ShowDialog<bool>(main);

        if (result != null)
        {
            string? oldname = imageSetViewModel.RootFolder.CurrentImageItem.ImagePath;
            string? newName = dialogModel.EntryText;
            if (!string.IsNullOrEmpty(newName) && !string.IsNullOrEmpty(oldname) && !File.Exists(newName))
            {
                File.Move(oldname, newName);
                imageSetViewModel.RootFolder.CurrentImageItem.ImagePath = newName;
                //RootFolder.CurrentImageItem.Save();
                imageSetViewModel.RootFolder.ReloadPictures();
            }
        }
    }
    #endregion Private Methods

    /// <summary>
}