//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaymadeEntities.Models
{
    //using DocumentFormat.OpenXml.Wordprocessing;
    using Microsoft.EntityFrameworkCore;
    using ReactiveUI;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Xml.Linq;

#nullable enable
    /// <summary>
    /// Defines the <see cref="Actor" />.
    /// </summary>
    [Table("Actor")]
    public partial class Actor : ModelBase, IDisposable
    {
        #region Fields

        /// <summary>
        /// Defines the adult.
        /// </summary>
        private bool? adult = false;

        /// <summary>
        /// Defines the dob1.
        /// </summary>
        private DateTime? dob1;

        /// <summary>
        /// Defines the gender.
        /// </summary>
        private int? gender;

        /// <summary>
        /// Defines the info.
        /// </summary>
        private string? info;

        /// <summary>
        /// Defines the name.
        /// </summary>
        private string? name = "";

        /// <summary>
        /// Defines the placeOfBirth.
        /// </summary>
        private string? placeOfBirth;

        /// <summary>
        /// Defines the tMDBID.
        /// </summary>
        private int? tMDBID;
        private string? aliases;
        private ICollection<Cast>? casts;
        private DateTime? deathDay;
        private string? filmGroup;
        private string? imagePath;
        private string? iMDB;
        private string? sortName;
        private string? wIKIPageID;
        private string? thumb;
        private bool? mergeItem = false;
        private bool? mergeSource = false;
        private bool dirty;
        private bool disposedValue;

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="Actor"/> class.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actor()
        {
            // this.Casts = new HashSet<Cast>();

            this.PropertyChanged += Actor_PropertyChanged;
        }

        private void Actor_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            string name = e.PropertyName;

            if (!(name == "MergeItem" || name == "MergeSource" || name == "Casts" || name == "BMPVisible" || name == "GenderDisplay" || name == "GenderValue"
                || name == "ImageBMP" || name == "Movies" || name == "TmpRole"))
            {
                Dirty = true;
                if (!string.IsNullOrEmpty(ChangedFields)) ChangedFields += ",";
                ChangedFields += name;
            }

        }



        /// <summary>
        /// Initializes a new instance of the <see cref="Actor"/> class.
        /// </summary>
        /// <param name="actorId">The actorId<see cref="int"/>.</param>
        public Actor(int actorId) : base()
        {
            var actor = DataController.ActorController.GetActorById(actorId);
            this.Casts = new HashSet<Cast>();


            if (actor != null)
            {
                Id = actor.Id;
                Name = actor.Name;
                Info = actor.Info;
                ImagePath = actor.ImagePath;
                DOB = actor.DOB;
                FilmGroup = actor.FilmGroup;
                TMDBID = actor.TMDBID;
                IMDB = actor.IMDB;
                Aliases = actor.Aliases;
                PlaceOfBirth = actor.PlaceOfBirth;
                Adult = actor.Adult;
                Gender = actor.Gender;
                DeathDay = actor.DeathDay;
                WIKIPageID = actor.WIKIPageID;
                SortName = actor.SortName;
                Casts = actor.Casts;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Actor"/> class.
        /// </summary>
        /// <param name="actor">The actor<see cref="XElement"/>.</param>
        public Actor(XElement actor) : base()
        {
            XElement name = actor.Element("name");
            if (name != null)
            {
                this.GetActorFromName(name.Value, "Movies");
            }

            name = actor.Element("role");
            if (name != null)
            {
                this.TmpRole = name.Value;
            }
        }

        #endregion

        #region Properties

        [NotMapped]

        public string? DeathDayString { get; set; }

        [NotMapped]
        public bool? MergeItem { get => mergeItem; set => this.RaiseAndSetIfChanged(ref mergeItem, value); }

        [NotMapped]
        public bool? MergeSource { get => mergeSource; set => this.RaiseAndSetIfChanged(ref mergeSource, value); }

        

        /// <summary>
        /// Gets or sets the Adult.
        /// </summary>
        public bool? Adult { get => adult; set => this.RaiseAndSetIfChanged(ref adult, value); }

        /// <summary>
        /// Gets or sets the Aliases.
        /// </summary>
        public string? Aliases { get => aliases; set => this.RaiseAndSetIfChanged(ref aliases, value); }

        /// <summary>
        /// Gets or sets the Casts.
        /// </summary>
        public virtual ICollection<Cast>? Casts
        {
            get
            {
                if (casts == null)
                {
                    casts = DataController.SandboxEntities.Casts.Where(x => x.ActorId == this.Id).ToList();
                }
                return casts;
            }
            set => this.RaiseAndSetIfChanged(ref casts, value);
        }

        /// <summary>
        /// Gets or sets the DeathDay.
        /// </summary>
        public DateTime? DeathDay { get => deathDay; set => this.RaiseAndSetIfChanged(ref deathDay, value); }

        /// <summary>
        /// Gets or sets the dob.
        /// </summary>
        public DateTime? DOB { get => dob1; set => this.RaiseAndSetIfChanged(ref dob1, value); }

        /// <summary>
        /// Gets or sets the FilmGroup.
        /// </summary>
        public string? FilmGroup { get => filmGroup; set => this.RaiseAndSetIfChanged(ref filmGroup, value); }

        [NotMapped]
        internal bool Dirty { get => dirty; set => dirty = value; }

        [NotMapped]
        private string? ChangedFields { get; set; }

        /// <summary>
        /// Gets or sets the Gender.
        /// </summary>
        public int? Gender
        {
            get
            {
                if (gender == null) gender = 0;

                genderValue = DataController.GenderList.Find(x => x.Order == gender);

                return gender;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref gender, value);
                GenderDisplay = SetGenderDisplay();
            }
        }

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        [Key]
        public new int Id { get; set; }

        /// <summary>
        /// Gets or sets the ImagePath.
        /// </summary>
        public string? ImagePath
        {
            get
            {
                if (!string.IsNullOrEmpty(imagePath))
                {
                    SetImageBMP();
                }
                return imagePath;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref imagePath, value);
                if (!string.IsNullOrEmpty(value))
                {
                    SetImageBMP();
                }
                else NullImageBMP();
            }
        }

        /// <summary>
        /// Gets or sets the IMDB.
        /// </summary>
        public string? IMDB { get => iMDB; set => this.RaiseAndSetIfChanged(ref iMDB, value); }

        /// <summary>
        /// Gets or sets the Info.
        /// </summary>
        public string? Info
        {
            get => info;
            set
            {
                if (!string.IsNullOrEmpty(value) && value.Length > 600) value = value.Substring(0, 600);
                this.RaiseAndSetIfChanged(ref info, value);
            }
        }

        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        public string? Name
        {
            get
            {
                if (string.IsNullOrEmpty(name)) name = "Blank";
                return name;
            }
            set => this.RaiseAndSetIfChanged(ref name, value);
        }

        /// <summary>
        /// Gets or sets the PlaceOfBirth.
        /// </summary>
        public string? PlaceOfBirth { get => placeOfBirth; set => this.RaiseAndSetIfChanged(ref placeOfBirth, value); }

        /// <summary>
        /// Gets or sets the SortName.
        /// </summary>
        public string? SortName { get => sortName; set => this.RaiseAndSetIfChanged(ref sortName, value); }


        public string? Thumb { get => thumb; set => this.RaiseAndSetIfChanged(ref thumb, value); }

        /// <summary>
        /// Gets or sets the TMDBID.
        /// </summary>
        public int? TMDBID { get => tMDBID; set => this.RaiseAndSetIfChanged(ref tMDBID, value); }

        /// <summary>
        /// Gets or sets the WIKIPageID.
        /// </summary>
        public string? WIKIPageID { get => wIKIPageID; set => this.RaiseAndSetIfChanged(ref wIKIPageID, value); }

        #endregion

        #region Methods

        /// <summary>
        /// The ToXMLElement.
        /// </summary>
        /// <returns>The <see cref="XElement"/>.</returns>
        public XElement ToXMLElement()
        {
            XElement element = new XElement("Actor");

            element.Add(new XElement("Name", this.Name));

            element.Add(new XElement("Role", this.TmpRole));
            element.Add(new XElement("DOB", this.DOB));
            return element;
        }

        public override string ToString()
        {
            return Name;
        }

        /// <summary>
        /// The GetActorFromName.
        /// </summary>
        /// <param name="name">The name<see cref="string"/>.</param>
        /// <param name="filmGroup">The filmGroup<see cref="string"/>.</param>
        private void GetActorFromName(string name, string filmGroup)
        {
            Actor? temp = DataController.ActorController.GetActorByName(name);

            if (temp != null)
            {
                this.name = temp.Name;
                this.Adult = temp.Adult;
                this.Aliases = temp.Aliases;
                this.DeathDay = temp.DeathDay;
                this.DOB = temp.DOB;
                this.FilmGroup = temp.FilmGroup;
                this.Gender = temp.gender;
                this.Id = temp.Id;
                this.ImagePath = temp.ImagePath;
                this.IMDB = temp.IMDB;
                this.Info = temp.Info;
                this.PlaceOfBirth = temp.PlaceOfBirth;
                this.TMDBID = temp.TMDBID;
                this.WIKIPageID = temp.WIKIPageID;
            }
        }

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    imageBMP?.Dispose();
                }

                // TODO: free unmanaged resources (unmanaged objects) and override finalizer
                // TODO: set large fields to null
                disposedValue = true;
            }
        }

        // // TODO: override finalizer only if 'Dispose(bool disposing)' has code to free unmanaged resources
        // ~Actor()
        // {
        //     // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
        //     Dispose(disposing: false);
        // }

        public void Dispose()
        {
            // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }

        #endregion
    }
}
