//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonMVVM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    using ReactiveUI;


    [Table("AlbumTracks")]
    public partial class AlbumTrack : ModelBase
    {
        private string trackPath;
        private string imagePath;
        private string trackName;
        private string comment;

        [Key]
        public new int Id { get; set; }
        public int AlbumID { get; set; }
        public string TrackName { get => trackName; set => this.RaiseAndSetIfChanged(ref trackName, value); }
        public string TrackPath { get => trackPath; set => this.RaiseAndSetIfChanged(ref trackPath, value); }
        public Nullable<int> TrackNo { get; set; }
        public Nullable<int> Duration { get; set; }
        public string ImagePath { get => imagePath; set => this.RaiseAndSetIfChanged(ref imagePath, value); }
        public string Comment { get => comment; set => this.RaiseAndSetIfChanged(ref comment, value); }
        public Nullable<decimal> Rating { get; set; }
        public string MusicBrainzID { get; set; }
        public string PlexKey { get; set; }
        public string DiscogsID { get; set; }
        public string TrackPosition { get; set; }

        [ForeignKey("AlbumID")]
        public virtual Album Album { get; set; }
    }
}
