//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaymadeEntities.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    using ReactiveUI;


    [Table("AlbumTracks")]
    public partial class AlbumTrack : ModelBase
    {
        private string trackPath;
        private string imagePath;
        private string trackName;
        private string comment;
        private int? duration;
        private int? trackNo;
        private string musicBrainzID;
        private string musicBrainzTrackID;

        [Key]
        public new int Id { get; set; }
        public int AlbumID { get; set; }
        public string TrackName { get => trackName; set => this.RaiseAndSetIfChanged(ref trackName, value); }
        public string TrackPath
        {
            get
            {
                if (trackPath.Contains("file://"))
                {
                    // is a uri
                    Uri mrl = new Uri(trackPath);
                    trackPath = mrl.LocalPath;
                }
                return trackPath;
            }

            set => this.RaiseAndSetIfChanged(ref trackPath, value);
        }
        public int? TrackNo { get => trackNo; set => this.RaiseAndSetIfChanged(ref trackNo, value); }
        public int? Duration { get => duration; set => this.RaiseAndSetIfChanged(ref duration, value); }
        public string ImagePath { get => imagePath; set => this.RaiseAndSetIfChanged(ref imagePath, value); }
        public string Comment { get => comment; set => this.RaiseAndSetIfChanged(ref comment, value); }
        public decimal? Rating { get; set; }
        public string? MusicBrainzID { get => musicBrainzID; set => this.RaiseAndSetIfChanged(ref musicBrainzID, value); }

        public string? MusicBrainzTrackID { get => musicBrainzTrackID; set => this.RaiseAndSetIfChanged(ref musicBrainzTrackID, value); }
        public string PlexKey { get; set; }
        public string DiscogsID { get; set; }
        public string TrackPosition { get; set; }

        [ForeignKey("AlbumID")]
        public virtual Album Album { get; set; }
    }
}
