//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaymadeEntities.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ReactiveUI;

    [Table("Album")]
    public partial class Album : ModelBase
    {
        private string albumName;
        private string albumPhotPath;
        private string playListPath;
        private string comment;
        private string albumPath;
        private List<AlbumTrack> albumTracks;
        private List<ArtistAlbum> artistAlbums;
        private List<ArtistVideo> artistVideos;
        private string musicBrainzReleaseGroupID1;

        public Album()
        {
            this.AlbumTracks = new List<AlbumTrack>();
            this.ArtistAlbums = new List<ArtistAlbum>();
            this.ArtistVideos = new List<ArtistVideo>();
        }


        public new int Id { get; set; }
        public string AlbumName { get => albumName; set => this.RaiseAndSetIfChanged(ref albumName, value); }
        public string AlbumPhotPath { get => albumPhotPath; set => this.RaiseAndSetIfChanged(ref albumPhotPath , value); }
        public string PlayListPath { get => playListPath; set => this.RaiseAndSetIfChanged(ref playListPath , value); }
        public Nullable<int> Year { get; set; }
        public string Comment { get => comment; set => this.RaiseAndSetIfChanged(ref comment , value); }
        public Nullable<decimal> Rating { get; set; }
        public string MusicBrainzID { get; set; }
        public string Genre { get; set; }
        public string musicBrainzReleaseGroupID
        { get => musicBrainzReleaseGroupID1; 
            set => this.RaiseAndSetIfChanged(ref musicBrainzReleaseGroupID1, value); 
        }
        public Nullable<int> PrimaryArtistID { get; set; }
        public string PlexKey { get; set; }
        public string AlbumPath { get => albumPath; set => this.RaiseAndSetIfChanged(ref albumPath , value); }
        public Nullable<int> DiscNo { get; set; }
        public string WIKIPageID { get; set; }
        public string DiscogsID { get; set; }
        public string DiscogsReleaseID { get; set; }

        public virtual List<AlbumTrack> AlbumTracks
        {
            get
            {
                if (albumTracks == null || albumTracks.Count == 0)
                {
                    albumTracks = DataController.MusicController.GetAlbumTracksByAlbumId(this.Id);
                }

                return albumTracks;
            }

            set => this.RaiseAndSetIfChanged(ref albumTracks, value);
        }
        public virtual List<ArtistAlbum> ArtistAlbums
        {
            get
            {
                if (artistAlbums == null || artistAlbums.Count == 0)
                {
                    artistAlbums = DataController.MusicController.GetArtistAlbumsByAlbumId(this.Id);
                }
                return artistAlbums;
            }

            set => this.RaiseAndSetIfChanged(ref artistAlbums, value);
        }
        public virtual List<ArtistVideo> 
            ArtistVideos 
        { 
            get => artistVideos; 
            set => this.RaiseAndSetIfChanged(ref artistVideos, value); 
        }
    }
}
