//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonMVVM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ReactiveUI;

    [Table("Album")]
    public partial class Album : ModelBase
    {
        private string albumName;
        private string albumPhotPath;
        private string playListPath;
        private string comment;
        private string albumPath;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.AlbumTracks = new HashSet<AlbumTrack>();
            this.ArtistAlbums = new HashSet<ArtistAlbum>();
            this.ArtistVideos = new HashSet<ArtistVideo>();
        }


        public new int Id { get; set; }
        public string AlbumName { get => albumName; set => this.RaiseAndSetIfChanged(ref albumName, value); }
        public string AlbumPhotPath { get => albumPhotPath; set => this.RaiseAndSetIfChanged(ref albumPhotPath , value); }
        public string PlayListPath { get => playListPath; set => this.RaiseAndSetIfChanged(ref playListPath , value); }
        public Nullable<int> Year { get; set; }
        public string Comment { get => comment; set => this.RaiseAndSetIfChanged(ref comment , value); }
        public Nullable<decimal> Rating { get; set; }
        public string MusicBrainzID { get; set; }
        public string Genre { get; set; }
        public string musicBrainzReleaseGroupID { get; set; }
        public Nullable<int> PrimaryArtistID { get; set; }
        public string PlexKey { get; set; }
        public string AlbumPath { get => albumPath; set => this.RaiseAndSetIfChanged(ref albumPath , value); }
        public Nullable<int> DiscNo { get; set; }
        public string WIKIPageID { get; set; }
        public string DiscogsID { get; set; }
        public string DiscogsReleaseID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumTrack> AlbumTracks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtistAlbum> ArtistAlbums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtistVideo> ArtistVideos { get; set; }
    }
}
