//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaymadeEntities.Models
{
    using ReactiveUI;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// Defines the <see cref="ArtistAlbum" />.
    /// </summary>
    [Table("ArtistAlbums")]
    public partial class ArtistAlbum : ModelBase
    {
        #region Fields

        /// <summary>
        /// Defines the album.
        /// </summary>
        private Album album;

        /// <summary>
        /// Defines the albumID.
        /// </summary>
        private int albumID;

        /// <summary>
        /// Defines the artist.
        /// </summary>
        private Artist artist;

        /// <summary>
        /// Defines the artistID.
        /// </summary>
        private int artistID;

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the Album.
        /// </summary>
        public virtual Album Album { get => album; set => this.RaiseAndSetIfChanged(ref album, value); }

        /// <summary>
        /// Gets or sets the AlbumID.
        /// </summary>
        public int AlbumID { get => albumID; set => this.RaiseAndSetIfChanged(ref albumID, value); }

        /// <summary>
        /// Gets or sets the Artist.
        /// </summary>
        public virtual Artist Artist
        {
            get
            {
                if (artist == null && ArtistID > 0)
                {
                    artist = DataController.MusicController.GetArtistById(ArtistID);
                }
                return artist;
            }

            set => this.RaiseAndSetIfChanged(ref artist, value);
        }

        /// <summary>
        /// Gets or sets the ArtistID.
        /// </summary>
        public int ArtistID { get => artistID; set => this.RaiseAndSetIfChanged(ref artistID, value); }

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        public new int Id { get; set; }

        #endregion
    }
}
