//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonMVVM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using ReactiveUI;

    [Table("Artist")]
    public partial class Artist : ModelBase
    {
        private readonly List<Artist> groupArtists = new List<Artist>();
        private readonly List<Artist> artistGroups = new List<Artist>();
        private ICollection<GroupMembers> groupMembers;
        private ICollection<ArtistAlbum> artistAlbums;
        private string name;
        private string photoPath;
        private string musicBrainzID;
        private string plexKey;
        private string artistType;
        private string artistPath;
        private string gender;
        private DateTime? birthDate;
        private DateTime? deathDate;
        private bool? soloist;
        private string wIKIPageID;
        private string discogsID;
        private string comment;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artist()
        {
            this.ArtistAlbums = new HashSet<ArtistAlbum>();
            this.GroupMembers = new HashSet<GroupMembers>();
            //this.GroupMembers1 = new HashSet<GroupMember>();
            this.ArtistVideos = new HashSet<ArtistVideo>();
        }

        public new int  Id { get; set; }
        public string Name { get => name; set => this.RaiseAndSetIfChanged(ref  name , value); }
        public string PhotoPath { get => photoPath; set => this.RaiseAndSetIfChanged(ref photoPath , value); }
        public string MusicBrainzID { get => musicBrainzID; set => this.RaiseAndSetIfChanged(ref musicBrainzID , value); }
        public string PlexKey { get => plexKey; set => this.RaiseAndSetIfChanged(ref plexKey , value); }
        public string ArtistPath { get => artistPath; set => this.RaiseAndSetIfChanged(ref artistPath , value); }
        public string Gender { get => gender; set => this.RaiseAndSetIfChanged(ref gender , value); }
        public string ArtistType { get => artistType; set => this.RaiseAndSetIfChanged(ref artistType , value); }
        public Nullable<System.DateTime> BirthDate { get => birthDate; set => this.RaiseAndSetIfChanged(ref birthDate , value); }
        public Nullable<System.DateTime> DeathDate { get => deathDate; set => this.RaiseAndSetIfChanged(ref deathDate , value); }
        public Nullable<bool> Soloist { get => soloist; set => this.RaiseAndSetIfChanged(ref soloist , value); }
        public string WIKIPageID { get => wIKIPageID; set => this.RaiseAndSetIfChanged(ref wIKIPageID , value); }
        public string DiscogsID { get => discogsID; set => this.RaiseAndSetIfChanged(ref discogsID , value); }
        public string Comment { get => comment; set => this.RaiseAndSetIfChanged(ref comment , value); }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtistAlbum> ArtistAlbums
        {
            get => artistAlbums;


            set => artistAlbums = value;

        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [NotMapped]
        public List<Artist> GroupArtists => groupArtists;

        [NotMapped]
        public List<Artist> ArtistGroups => artistGroups;

        [NotMapped]
        public virtual ICollection<GroupMembers> GroupMembers
        {
            get
            {
                InitialiseGroups();
                return groupMembers;
            }

            set => this.RaiseAndSetIfChanged(ref groupMembers , value);
        }

        internal void RefreshGroups()
        {
            GroupMembers.Clear();
            GroupArtists.Clear();
            ArtistGroups.Clear();
            InitialiseGroups();
        }

        internal void InitialiseGroups()
        {
            if (groupMembers != null && groupMembers.Count >= 0)
            {
                if (ArtistType == "Group")
                {
                    GroupArtists.Clear();
                    groupMembers = DataController.MusicEntitiesContext.GroupMembers.Where(g => g.GroupId == Id).ToList();
                    foreach (GroupMembers item in groupMembers)
                    {
                        groupArtists.Add(item.Artist);
                    }
                }

                else
                {
                    ArtistGroups.Clear();
                    groupMembers = DataController.MusicEntitiesContext.GroupMembers.Where(g => g.ArtistId == Id).ToList();
                    foreach (GroupMembers item in groupMembers)
                    {
                        ArtistGroups.Add(item.ArtistGroup);
                    }
                }

                //if (groupMembers.Count == 0) groupMembers = null;
            }
        }

        [NotMapped]
        public bool IsGroup => (ArtistType == "Group");

        [NotMapped]
        public bool IsPerson => (ArtistType == "Person");


        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<GroupMember> GroupMembers1 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtistVideo> ArtistVideos { get; set; }
    }
}
