//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace TaymadeEntities.Models
{
    using System;
    using System.Collections.Generic;
    using ReactiveUI;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    using Microsoft.EntityFrameworkCore;
    using System.Linq;

    [Table("ArtistVideo")]
    public partial class ArtistVideo : ModelBase
    {
        private Movies? movy;
        private int movieId;
        private int artistID;
        private int? albumId;
        private Artist? artist;
        private Album? album;

        [Key]
        public new int Id { get; set; }
        public int MovieId { get => movieId; set => this.RaiseAndSetIfChanged(ref movieId, value); }
        public int ArtistID { get => artistID; set => this.RaiseAndSetIfChanged(ref artistID, value); }
        public Nullable<int> AlbumId { get => albumId; set => this.RaiseAndSetIfChanged(ref albumId, value); }

        [ForeignKey("ArtistID")]
        public virtual Artist Artist { get => artist; set => this.RaiseAndSetIfChanged(ref artist, value); }

        [ForeignKey("MovieId")]
        public virtual Movies? Movy
        {
            get
            {
                if (movy == null)
                {
                    movy = DataController.SandboxEntities.Movies.Find(MovieId);
                }

                return movy;
            }
            set => this.RaiseAndSetIfChanged(ref movy, value);
        }

        [NotMapped]
        public virtual Album? Album { get => album; set => this.RaiseAndSetIfChanged(ref album, value); }

        public void Delete()
        {
            DataController.MusicController.DeleteArtistVideo(this);
        }

        public void Insert()
        {
            DataController.MusicController.AddArtistVideo(this);
            
        }

        public void Save()
        {
            DataController.MusicController.UpdateArtistVideo(this);
        }
    }
}
