//-----------------------------------------------------------------------
// <copyright file="Author.cs" company="Taymade Software Services">
//     Copyright (c) Taymade Software Services. All rights reserved.
// </copyright>
// <created>03/01/2023 22:38:57 03/01/2023 22:38:57 </created>
// <author>Doug Taylor</author>
//-----------------------------------------------------------------------

namespace TaymadeEntities.Models
{
    using DocumentFormat.OpenXml.InkML;
    using Microsoft.EntityFrameworkCore;
    using ReactiveUI;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    /// <summary>
    /// Defines the <see cref="Author" />.
    /// </summary>
    public class Author : ModelBase
    {
        #region Private Fields

        /// <summary>
        /// The name
        /// </summary>
        /// <autogeneratedoc />
        private string? name;
        
        /// <summary>
        /// The story path
        /// </summary>
        /// <autogeneratedoc />
        private string? storyPath;
        private List<Story> storyList;

        #endregion Private Fields

        #region Properties

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        public new int Id { get; set; }

        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        public string? Name { get => name; set => this.RaiseAndSetIfChanged(ref name, value); }

        /// <summary>
        /// Gets or sets the StoryList.
        /// </summary>
        [NotMapped]
        public List<Story> StoryList
        {
            get
            {
                var query = from Stories in DataController.SandboxEntities.Set<Story>()
                            join StoryAuthor in DataController.SandboxEntities.Set<StoryAuthor>()
                                on Stories.Id equals StoryAuthor.StoryId
                            where StoryAuthor.AuthorId == Id
                            select new { Stories}  ;
                storyList = query.Select(s => s.Stories).ToList(); 

                return storyList;
            }

            set => storyList = value;
        }

        /// <summary>
        /// Gets or sets the story path.
        /// </summary>
        /// <value>
        /// The story path.
        /// </value>
        /// <autogeneratedoc />
        public string? StoryPath 
        {
            get => storyPath;
            set
            {
                this.RaiseAndSetIfChanged(ref storyPath, value);
                Save();
            }
        }
        #endregion

        #region Methods

        /// <summary>
        /// The ToString.
        /// </summary>
        /// <returns>The <see cref="string"/>.</returns>
        public override string ToString()
        {
            return Name;
        }

        public void Save()
        {
            try
            {
                if (Id == 0) DataController.StoryController.AddAuthor(this);
                DataController.StoryController.Save();
            }
            catch (Exception)
            {

            }
        }

        #endregion
    }
}
