//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaymadeEntities.Models
{
    using ReactiveUI;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// Defines the <see cref="Bookmark" />.
    /// </summary>
    [Table("Bookmarks")]
    public partial class Bookmark : ModelBase,IDisposable
    {
        #region Fields

        /// <summary>
        /// Defines the comment.
        /// </summary>
        private string? comment = string.Empty;

        /// <summary>
        /// Defines the imagePath.
        /// </summary>
        private string? imagePath = string.Empty;

        /// <summary>
        /// Defines the name.
        /// </summary>
        private string? name = string.Empty;

        /// <summary>
        /// Defines the time.
        /// </summary>
        private double? time = 0;

        /// <summary>
        /// Defines the type.
        /// </summary>
        private string? type = string.Empty;
        private bool disposedValue;

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="Bookmark"/> class.
        /// </summary>
        public Bookmark()
        {
            bookmarkTime = this.WhenAnyValue(x => x.FormattedTime).ToProperty(this, x => x.BookmarkTime);
        }

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the Comment.
        /// </summary>
        public string? Comment { get => comment; set => this.RaiseAndSetIfChanged(ref comment, value); }

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        [Key]
        public new int Id { get; set; }

        /// <summary>
        /// Gets or sets the ImagePath.
        /// </summary>
        public string? ImagePath
        {
            get => imagePath;
            set
            {
                this.RaiseAndSetIfChanged(ref imagePath, value);
                if (!string.IsNullOrEmpty(value))
                {
                    SetImageBMP();
                }
            }
        }

        /// <summary>
        /// Gets or sets the MovieID.
        /// </summary>
        [ForeignKey("Movies")]
        public int MovieID { get; set; }

        /// <summary>
        /// Gets or sets the Movies.
        /// </summary>
        [NotMapped]
        public virtual Movies Movies { get; set; }

        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        public string? Name
        {
            get
            {
                if (name == null) name = string.Empty;
                return name;
            }

            set => this.RaiseAndSetIfChanged(ref name, value);
        }

        /// <summary>
        /// Gets or sets the Time.
        /// </summary>
        public Nullable<double> Time
        {
            get
            {
                return time;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref time, value);
                SetFormattedTime();
            }
        }

        /// <summary>
        /// Gets the TruncTime.
        /// </summary>
        public Nullable<double> TruncTime
        {
            get
            {
                if (Time != null)
                    return Math.Truncate(Time.Value);
                else return 0;
            }
        }

        /// <summary>
        /// Gets or sets the Type.
        /// </summary>
        public string? Type { get => type; set => this.RaiseAndSetIfChanged(ref type, value); }

        #endregion

        public override string ToString()
        {
            string returnVal = this.Name ;
            if (Time != null && time.Value > 0) returnVal += "-" + Time.ToString();
            return returnVal;
        }

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    ImageBMP?.Dispose();
                }

                // TODO: free unmanaged resources (unmanaged objects) and override finalizer
                // TODO: set large fields to null
                disposedValue = true;
            }
        }

        // // TODO: override finalizer only if 'Dispose(bool disposing)' has code to free unmanaged resources
        // ~Bookmark()
        // {
        //     // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
        //     Dispose(disposing: false);
        // }

        public void Dispose()
        {
            // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }
    }
}
