//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaymadeEntities.Models
{
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using ReactiveUI;

#nullable enable

    /// <summary>
    /// Defines the <see cref="Cast" />.
    /// </summary>
    [Table("Cast")]
    public partial class Cast : ModelBase
    {
        #region Fields

        /// <summary>
        /// Defines the actor.
        /// </summary>
        private Actor? actor;
        private int? actorId;
        private int? castId;
        private string? credit_id1;
        private int id;
        private int? movieID;
        private Movies? movies;
        private string? role;
        private bool actorChanged;

        #endregion

        #region Properties

        [NotMapped]

        public bool ActorChanged
        {
            get => actorChanged;
            set
            {
                this.RaiseAndSetIfChanged(ref actorChanged, value);
                if (value)
                {
                    Actor?.SetGenderDisplay();
                }
            }
        }

        /// <summary>
        /// Gets or sets the Actor.
        /// </summary>
        [NotMapped]
        public virtual Actor? Actor
        {
            get
            {
                if (actor == null)
                {
                    //actor = new Actor(ActorId);
                    actor = DataController.SandboxEntities.Actors.Find(ActorId);

                }
                if (actor != null) actor.SetGenderDisplay();
                return actor;
            }

            set => this.RaiseAndSetIfChanged(ref actor, value);
        }

        /// <summary>
        /// Gets or sets the ActorId.
        /// </summary>
        [ForeignKey("Actor")]
        public int? ActorId { get => actorId; set => this.RaiseAndSetIfChanged(ref actorId, value); }

        /// <summary>
        /// Gets or sets the CastId.
        /// </summary>
        public int? CastId { get => castId; set => this.RaiseAndSetIfChanged(ref castId, value); }

        /// <summary>
        /// Gets or sets the credit_id.
        /// </summary>
        public string credit_id { get => credit_id1; set => this.RaiseAndSetIfChanged(ref credit_id1, value); }

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        [Key]
        public new int Id { get => id; set => this.RaiseAndSetIfChanged(ref id, value); }

        /// <summary>
        /// Gets or sets the MovieID.
        /// </summary>
        [ForeignKey("Movies")]
        public int? MovieID { get => movieID; set => this.RaiseAndSetIfChanged(ref movieID, value); }

        /// <summary>
        /// Gets or sets the Movies.
        /// </summary>
        [NotMapped]
        public Movies? Movies { get => movies; set => this.RaiseAndSetIfChanged(ref movies, value); }

        /// <summary>
        /// Gets or sets the Role.
        /// </summary>
        public string? Role { get => role; set => this.RaiseAndSetIfChanged(ref role, value); }

        #endregion

        #region Methods

        /// <summary>
        /// The Save.
        /// </summary>
        internal void Save()
        {
            try
            {

                var local = DataController.SandboxEntities.Set<Cast>().Local.FirstOrDefault(entry => entry.Id.Equals(Id));

                // check if local is not null 
                if (local != null)
                {
                    // detach
                    DataController.SandboxEntities.Entry(local).State = EntityState.Detached;
                }
                // set Modified flag in your entry
                DataController.SandboxEntities.Entry(this).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                DataController.SandboxEntities.SaveChanges();

                //if (Actor != null)
                //{
                //    Actor.Save();
                //    //DataController.SandboxEntities.Entry(Actor).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                //    //DataController.SandboxEntities.SaveChanges();


                //}
            }
            catch (Exception)
            {
                // throw;
            }

        }

        
        /// <summary>
        /// Add a new Cast entity into database 
        /// </summary>
        internal void Insert()
        {

            if (this.Id < 10)
            {
                DataController.SandboxEntities.Casts.Add(this);
                DataController.SandboxEntities.SaveChanges();
            }

        }

        /// <summary>
        ///  Delete Entity from database
        /// </summary>
        internal void Delete()
        {
            this.Movies = null;
            var local = DataController.SandboxEntities.Set<Cast>().Local.FirstOrDefault(entry => entry.Id.Equals(Id));

            // check if local is not null
            if (local != null)
            {
                // detach
                DataController.SandboxEntities.Entry(local).State = EntityState.Detached;
            }

            DataController.SandboxEntities.Casts.Remove(this);
            DataController.SandboxEntities.SaveChanges();
        }

        #endregion
    }
}
