//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaymadeEntities.Models
{
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using ReactiveUI;

#nullable enable

    /// <summary>
    /// Defines the <see cref="Cast" />.
    /// </summary>
    [Table("Cast")]
    public partial class Cast : ModelBase, IDisposable
    {
        #region Fields

        /// <summary>
        /// Defines the actor.
        /// </summary>
        private Actor? actor;
        private int? actorId;
        private int? castId;
        private string? credit_id1;
        private int id;
        private int? movieID;
        private Movies? movies;
        private string? role;
        private bool actorChanged;
        private bool disposedValue;

        #endregion

        #region Properties

        [NotMapped]

        public bool ActorChanged
        {
            get => actorChanged;
            set
            {
                this.RaiseAndSetIfChanged(ref actorChanged, value);
                if (value)
                {
                    Actor?.SetGenderDisplay();
                }
            }
        }

        /// <summary>
        /// Gets or sets the Actor.
        /// </summary>
        [NotMapped]
        public virtual Actor? Actor
        {
            get
            {
                if (actor == null)
                {
                    //actor = new Actor(ActorId);
                    actor = DataController.ActorController.GetActorById(Id);

                }
                if (actor != null) actor.SetGenderDisplay();
                return actor;
            }

            set => this.RaiseAndSetIfChanged(ref actor, value);
        }

        /// <summary>
        /// Gets or sets the ActorId.
        /// </summary>
        [ForeignKey("Actor")]
        public int? ActorId { get => actorId; set => this.RaiseAndSetIfChanged(ref actorId, value); }

        /// <summary>
        /// Gets or sets the CastId.
        /// </summary>
        public int? CastId { get => castId; set => this.RaiseAndSetIfChanged(ref castId, value); }

        /// <summary>
        /// Gets or sets the credit_id.
        /// </summary>
        public string? credit_id { get => credit_id1; set => this.RaiseAndSetIfChanged(ref credit_id1, value); }

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        [Key]
        public new int Id { get => id; set => this.RaiseAndSetIfChanged(ref id, value); }

        /// <summary>
        /// Gets or sets the MovieID.
        /// </summary>
        [ForeignKey("Movies")]
        public int? MovieID { get => movieID; set => this.RaiseAndSetIfChanged(ref movieID, value); }

        /// <summary>
        /// Gets or sets the Movies.
        /// </summary>
        [NotMapped]
        public Movies? Movies { get => movies; set => this.RaiseAndSetIfChanged(ref movies, value); }

        /// <summary>
        /// Gets or sets the Role.
        /// </summary>
        public string? Role { get => role; set => this.RaiseAndSetIfChanged(ref role, value); }

        #endregion

        #region Methods

        /// <summary>
        /// The Save.
        /// </summary>
        internal void Save()
        {
            try
            {

                var local = DataController.SandboxEntities.Set<Cast>().Local.FirstOrDefault(entry => entry.Id.Equals(Id));

                // check if local is not null 
                if (local != null)
                {
                    // detach
                    DataController.SandboxEntities.Entry(local).State = EntityState.Detached;
                }
                // set Modified flag in your entry
                DataController.SandboxEntities.Entry(this).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                DataController.SandboxEntities.SaveChanges();

                //if (Actor != null)
                //{
                //    Actor.Save();
                //    //DataController.SandboxEntities.Entry(Actor).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                //    //DataController.SandboxEntities.SaveChanges();


                //}
            }
            catch (Exception)
            {
                // throw;
            }

        }


        /// <summary>
        /// Add a new Cast entity into database 
        /// </summary>
        public async Task InsertAsync()
        {

            if (this.Id < 10)
            {
                Cast? temp = DataController.CastController.GetOrCreateCast(this.MovieID.Value, this.ActorId.Value);
                
                int? newId = null;
                if (temp == null)
                {
                    newId = await DataController.SandboxEntities.CreateCastAsync(this);
                }
                if (newId != null) this.Id = temp.Id;
            }

        }

        /// <summary>
        /// Inserts this instance.
        /// </summary>
        public void Insert()
        {
            try
            {
                if (this.Id <= 0)
                {
                    // using an EF context here is not ideal, but it is the only way to get the new ID back from the database
                    using var ctx = DataController.SandboxEntities;
                    // a synchronous version of the method 
                    Cast? temp = ctx.CreateCast(this);
                    if (temp != null) this.Id = temp.Id;
                }

            }
            catch (Exception ex)
            {
                string msg = "error inserting  cast : " + Id.ToString();
                Support.Support.Logger.Error(ex, msg);
            }
        }

        /// <summary>
        ///  Delete Entity from database
        /// </summary>
        public void Delete()
        {
            this.Movies = null;
            this.Actor = null;
            bool success = DataController.SandboxEntities.DeleteCastMember(this.Id);

            //int gone = DataController.SandboxEntities.SaveChanges();
        }

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    if (Actor != null)
                    {
                        Actor.Dispose();
                        Actor = null;
                    }
                }

                // TODO: free unmanaged resources (unmanaged objects) and override finalizer
                // TODO: set large fields to null
                disposedValue = true;
            }
        }

        // // TODO: override finalizer only if 'Dispose(bool disposing)' has code to free unmanaged resources
        // ~Cast()
        // {
        //     // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
        //     Dispose(disposing: false);
        // }

        public void Dispose()
        {
            // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }

        #endregion
    }
}
