//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonMVVM.Models
{
    using Avalonia.Media;
    using AvalonMVVM.Support;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Diagnostics;
    using ReactiveUI;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    /// <summary>
    /// Defines the <see cref="Director" />.
    /// </summary>
    [Table("Director")]
    public partial class Director : ModelBase
    {
        #region Fields

        /// <summary>
        /// Defines the id.
        /// </summary>
        private int id;

        /// <summary>
        /// Defines the info.
        /// </summary>
        private string info;

        /// <summary>
        /// Defines the movies.
        /// </summary>
        private ICollection<Movies> movies;

        /// <summary>
        /// Defines the name.
        /// </summary>
        private string name;
        private string imagePath;
        private bool dirty;
        private ISolidColorBrush backColour = Avalonia.Media.Brushes.GhostWhite;

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="Director"/> class.
        /// </summary>
        public Director()
        {
            this.Movies = new HashSet<Movies>();

            this.PropertyChanged += Director_PropertyChanged;
        }

        private void Director_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            string name = e.PropertyName;

            Dirty = true;
            if (!string.IsNullOrEmpty(ChangedFields)) ChangedFields += ",";
            ChangedFields += name;
        }

        #endregion

        #region Properties

        [NotMapped]
        public Avalonia.Media.ISolidColorBrush BackColour { get => backColour; set => this.RaiseAndSetIfChanged(ref backColour, value); }

        [NotMapped]
        public bool Selected { get; set; }

        [NotMapped]
        internal bool Dirty { get => dirty; set => dirty = value; }

        [NotMapped]
        private string? ChangedFields { get; set; }

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        [Key]
        public new int Id { get => id; set => this.RaiseAndSetIfChanged(ref id, value); }

        /// <summary>
        /// Gets or sets the ImagePath.
        /// </summary>
        public string ImagePath { get => imagePath; set => this.RaiseAndSetIfChanged(ref imagePath, value); }

        /// <summary>
        /// Gets or sets the Info.
        /// </summary>
        public string Info { get => info; set => this.RaiseAndSetIfChanged(ref info, value); }

        /// <summary>
        /// Gets or sets the Movies.
        /// </summary>
        public virtual ICollection<Movies> Movies { get => movies; set => this.RaiseAndSetIfChanged(ref movies, value); }

        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        public string Name { get => name; set => this.RaiseAndSetIfChanged(ref name, value); }

        #endregion

        #region Methods

        /// <summary>
        /// The ToString.
        /// </summary>
        /// <returns>The <see cref="string"/>.</returns>
        public override string ToString()
        {
            return Name;
        }

        public void Save()
        {
            //if (!Dirty)
            //{
                try
                {
                    //var local = DataController.SandboxEntities.Set<Director>().Local.FirstOrDefault(entry => entry.Id.Equals(Id));

                    //if (local != null)
                    //{
                    //    // detach
                    //    DataController.SandboxEntities.Entry(local).State = EntityState.Detached;
                    //}

                    DataController.SandboxEntities.Entry(this).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                    DataController.SandboxEntities.SaveChanges();

                    LogMessage("Saved " + ChangedFields);
                    ChangedFields = string.Empty;
                    Dirty = false;                  // clear modified flag; 

                }
                catch (System.Exception ex)
                {
                    string msg = "error Saving director : " + Id.ToString() + " : " + Name;
                    Support.Logger.Error(ex, msg);
                }

            //}
        }

        /// <summary>Logs the message.</summary>
        /// <param name="action">The action.</param>
        internal void LogMessage(string action)
        {
            Support.GenerateInfoAndLogMessage(action, "Director", Id, Name);
        }

        internal void Delete()
        {
            DataController.SandboxEntities.Directors.Remove(this);
            DataController.SandboxEntities.SaveChanges();
        }

        #endregion
    }
}
