using TaymadeEntities.Support;
using TaymadeEntities.ViewModels;
using DocumentFormat.OpenXml.Spreadsheet;
using ReactiveUI;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using Newtonsoft;
using static TaymadeEntities.Support.MissingFileFinder;
using Newtonsoft.Json;
using System.Web;
using Microsoft.EntityFrameworkCore;
using DynamicData;
using DocumentFormat.OpenXml.Presentation;
using Avalonia.Controls;

namespace TaymadeEntities.Models
{
    /// <summary>
    /// 
    /// </summary>
    /// <seealso cref="TaymadeEntities.Models.ModelBase" />
    /// <autogeneratedoc />
    public class MovieImage : ModelBase
    {
        private const string cstImageList = "ImageList";

        #region Fields
        private string playButtonContent = "Play";


        /// <summary>
        /// The path
        /// </summary>
        /// <autogeneratedoc />
        private string? path;
        /// <summary>
        /// The speed
        /// </summary>
        /// <autogeneratedoc />
        private double? speed;
        /// <summary>
        /// The name
        /// </summary>
        /// <autogeneratedoc />
        private string? name;
        private ImageItemsCollection imageItems;
        private bool commandIsVisible = false;
        private string info;
        private ObservableCollection<MovieImage> subDirectoryList;
        private string folderType;
        //private FolderProperties properties;
        private string? comments = null;
        private int? movieId;
        private bool? selected;
        private Movies? movies;
        #endregion

        #region Constructors
        /// <summary>
        /// Initializes a new instance of the <see cref="Images"/> class.
        /// </summary>
        /// <autogeneratedoc />
        public MovieImage()
        {
            PlayButtonContent = "Play";
            PropertyChanged += Images_PropertyChanged;

        }

        private void Images_PropertyChanged(object? sender, PropertyChangedEventArgs e)
        {
            this.Save();
        }
        #endregion

        #region Properties

        [NotMapped]
        public bool? Selected { get => selected; set => this.RaiseAndSetIfChanged(ref selected, value); }


        //public MainWindowViewModel MVVM { get; internal set; }

        public int? ParentId { get; set; }

        public int? LastId { get; set; }

        public string? LastImageName { get; set; }
        public int? MovieId
        {
            get
            {
                if (movieId == null)
                { }
                else


                {
                    Movies = DataController.SandboxEntities.Movies.Find(movieId);
                }

                return movieId;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref movieId, value);
                if (FolderType == cstImageList && value != null)
                {
                    //Properties.MovieId = movieId;

                    if (Id == 0) this.Insert(); else this.Save();
                }
            }
        }

        [NotMapped]
        public Movies? Movies
        {
            get => movies;
            set
            {
                this.RaiseAndSetIfChanged(ref movies, value);

                if (value != null)
                {
                    movieId = value.Id;

                }
                else
                {
                    movieId = null;

                }
            }
        }

        public string? Comments
        {
            get
            {

                return comments;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref comments, value);

            }
        }



        [NotMapped]
        public string PlayButtonContent
        {
            get => playButtonContent; set
            {
                this.RaiseAndSetIfChanged(ref playButtonContent, value);

            }
        }

        public string FolderType { get => folderType; set => this.RaiseAndSetIfChanged(ref folderType, value); }

        /// <summary>
        /// Gets or sets the path.
        /// </summary>
        /// <value>
        /// The path.
        /// </value>
        /// <autogeneratedoc />
        public string? Path
        {
            get => path;
            set
            {
                string? oldPath = path;
                this.RaiseAndSetIfChanged(ref path, value);
                if (!string.IsNullOrEmpty(value) && !string.IsNullOrEmpty(oldPath) &&
                    oldPath.ToLower() != value.ToLower() && ImageItems != null)
                {
                    this.ImageItems.Clear();
                    this.ImageItems.ReloadImageItems(value);
                }
            }
        }

        /// <summary>
        /// Gets or sets the speed.
        /// </summary>
        /// <value>
        /// The speed.
        /// </value>
        /// <autogeneratedoc />
        public double? Speed
        {
            get
            {
                return speed;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref speed, value);


                if (ImageItems != null)
                {
                    imageItems.Speed = value;
                }
            }
        }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>
        /// The name.
        /// </value>
        /// <autogeneratedoc />
        public string? Name
        {
            get => name;
            set
            {
                string oldName = name;
                this.RaiseAndSetIfChanged(ref name, value);

                if (FolderType == cstImageList)
                {
                    // if last character of path = . or .. it is a parent folder;

                    string dir = System.IO.Path.GetDirectoryName(Path);
                    int len = dir.Length;
                    string pathFolder = Path.Substring(len + 1);
                    if (pathFolder == "." || pathFolder == "..")
                    {
                        // new folder add name to folder
                        Path = pathFolder + Name;
                        if (Directory.Exists(Path))
                        {

                        }
                        else
                        {
                            Directory.CreateDirectory(Path);
                        }
                        this.ImageItems.Clear();
                        this.ImageItems.ReloadImageItems(value);
                    }
                    else
                    {
                        // changing the name 
                        string newPath = dir + @"\" + name;
                        if (!Directory.Exists(newPath) && Directory.Exists(Path))
                        {
                            // we can move
                            if (Path.ToLower() != newPath.ToLower())
                                Directory.Move(Path, newPath);
                            else Directory.CreateDirectory(Path);
                            this.ImageItems.Clear();
                            this.ImageItems.ReloadImageItems(value);
                        }

                        Path = newPath;
                        Save();
                    }
                }
            }
        }

        [NotMapped]
        public ImageItemsCollection ImageItems
        {
            get
            {
                if (imageItems == null)
                {
                    if (this.FolderType == null) FolderType = cstImageList;
                    imageItems = new ImageItemsCollection(Path, this);
                    ;
                    //imageItems.ImageChanged += ImageItems_PropertyChanged;
                    if (speed == null) speed = 5;
                    //if (!string.IsNullOrEmpty(path))
                    //    Properties = new FolderProperties(Path);
                }
                return imageItems;
            }

            set => this.RaiseAndSetIfChanged(ref imageItems, value);
        }

        [NotMapped]
        public ObservableCollection<MovieImage> SubDirectoryList
        {
            get
            {
                if (subDirectoryList == null) subDirectoryList = new ObservableCollection<MovieImage>();
                if (subDirectoryList.Count == 0)
                {
                    if (Id > 0)
                    {
                        List<MovieImage>? tempList = DataController.MovieImageEntity.MovieImage.Where(i => i.ParentId == Id).OrderBy(x => x.Name).ToList();
                        if (tempList != null)
                        {
                            subDirectoryList = new ObservableCollection<MovieImage>(tempList);
                        }
                    }

                }

                return subDirectoryList;
            }

            set => this.RaiseAndSetIfChanged(ref subDirectoryList, value);
        }

        [NotMapped]
        public bool CommandIsVisible { get => commandIsVisible; set => this.RaiseAndSetIfChanged(ref commandIsVisible, value); }

        [NotMapped]
        public string Info { get => info; set => this.RaiseAndSetIfChanged(ref info, value); }

        #endregion

        #region Methods



        internal void Insert()
        {
            if (Id == 0)
            {
                DataController.MovieImageEntity.MovieImage.Add(this);
                DataController.MovieImageEntity.SaveChanges();
            }
        }
        public void Save()
        {
            if (Id == 0) Insert();
            try
            {
                DataController.MovieImageEntity.SaveChanges();

            }
            catch (Exception ex)
            {
                string msg = "error Saving movie Image : " + Id.ToString() + " : " + Name;
                Support.Support.Logger.Error(ex, msg);

                MVMLogs logs = new MVMLogs(ex, "database", "Error", "Downloads");

            }
        }

        internal void Delete()
        {
            DataController.MovieImageEntity.Remove(this);
            DataController.MovieImageEntity.SaveChanges();

        }
        #endregion
    }

    public class RootFolder : MovieImage
    {
        #region fields

        private MovieImage? currentImageItem;
        private ImageItem? currentImageItem1;
        private MovieImage? currentSubFolder;
        private ObservableCollection<MovieImage>? currentSubDirectoryList;

        #endregion

        #region Constructors
        public RootFolder()
        {
            this.BuildSubFolders();
        }

        public void BuildSubFolders()
        {
            MovieImage? images = DataController.MovieImageEntity.MovieImage.Where(i => i.FolderType == "Root").FirstOrDefault();
            // get subfolders
            if (images != null)
            {
                LastId = images.LastId;
                Id = images.Id;
                FolderType = images.FolderType;

                // get an ordered list of sub folders
                SubDirectoryList = new ObservableCollection<MovieImage>(DataController.MovieImageEntity.MovieImage.Where(i => i.ParentId == Id).OrderBy(d => d.Name.ToLower()).ToList());

                if (LastId != null)
                {
                    // get an ordered list of images
                    images = SubDirectoryList.Where(f => f.Id == LastId).OrderBy(i => i.Name).FirstOrDefault();
                    if (images != null)
                    {
                        CurrentImageFolder = images;
                        // see if we can find sub folder
                        if (CurrentImageFolder.LastId != null)
                        {
                            images = CurrentImageFolder.SubDirectoryList.Where(f => f.Id == CurrentImageFolder.LastId).FirstOrDefault();
                            CurrentSubFolder = images;

                            if (images != null && images.ImageItems.Count > 0 && !string.IsNullOrEmpty(images.LastImageName))
                            {
                                CurrentImageItem = images.ImageItems.Where(it => it.ImageName == images.LastImageName).FirstOrDefault();
                                MainSupport.ScrollItemImagesIntoView(CurrentImageItem);
                            }
                        }
                    }
                }
                else CurrentImageFolder = SubDirectoryList.FirstOrDefault();


            }
        }
        #endregion

        #region Properties 
        /// <summary>
        /// Gets or sets the current image folder.
        /// </summary>
        /// <value>
        /// The current image folder.
        /// </value>
        /// <autogeneratedoc />
        public Models.MovieImage CurrentImageFolder
        {
            get
            {

                return currentImageItem;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref currentImageItem, value);
                if (value != null)
                {
                    this.LastId = value.Id;
                    // CurrentImageFolder.ImageItems.ImageChanged += ImageItems_ImageChanged;
                    this.Save();
                }
            }
        }

        public ObservableCollection<MovieImage> CurrentSubDirectoryList
        {
            get
            {
                if (currentSubDirectoryList == null)
                {
                    currentSubDirectoryList = new ObservableCollection<MovieImage>();
                }
                return new ObservableCollection<MovieImage>(currentSubDirectoryList.OrderBy(x => x.Name));
            }

            set => this.RaiseAndSetIfChanged(ref currentSubDirectoryList, value);
        }


        /// <summary>
        /// Gets or sets the current sub folder.
        /// </summary>
        /// <value>
        /// The current sub folder.
        /// </value>
        /// <autogeneratedoc />
        public MovieImage CurrentSubFolder
        {
            get => currentSubFolder;
            set
            {
                this.RaiseAndSetIfChanged(ref currentSubFolder, value);
                if (currentSubFolder != null)
                {
                    currentSubFolder.ImageItems.ImageChanged += ImageItems_ImageChanged;
                    if (CurrentImageFolder != null)
                    {
                        CurrentImageFolder.LastId = value.Id;
                        CurrentImageFolder.Save();
                    }
                }
            }
        }

        private void ImageItems_ImageChanged(object sender, ImageChangedEventArgs e)
        {
            if (e.Action == "Play")
            {
                CurrentImageItem = e.ImageItem;
            }
        }

        /// <summary>
        /// Gets or sets the current image item.
        /// </summary>
        /// <value>
        /// The current image item.
        /// </value>
        /// <autogeneratedoc />
        public ImageItem CurrentImageItem
        {
            get => currentImageItem1;
            set
            {
                if (currentImageItem1 != null) currentImageItem1.Selected = false;
                this.RaiseAndSetIfChanged(ref currentImageItem1, value);
                if (value != null)
                {
                    value.Selected = true;
                    if (CurrentSubFolder != null && !ImageItems.IsPlaying)
                    {
                        CurrentSubFolder.LastImageName = value.ImageName;
                        CurrentSubFolder.Save();
                    }

                }
            }
        }




        public Movies CurrentMovie
        {
            get => currentMovie;
            set => this.RaiseAndSetIfChanged(ref currentMovie, value);
        }

        public MainWindowViewModel MVVM { get; set; }

        #endregion

        #region Methods

        public string TempDirectory()
        {
            if (currentSubFolder != null)
            {
                string outputDirectory = CurrentSubFolder.Path + @"\temp";
                return outputDirectory;
            }
            else return "";

        }

        public string MoviePath()
        {
            string outputFileName = CurrentSubFolder.Path + @"\" + System.IO.Path.GetFileNameWithoutExtension(CurrentSubFolder.Path) + ".mp4";
            return outputFileName;
        }

        public string OutputMoviePath()
        {
            string outputFileName = TempDirectory() + @"\" + System.IO.Path.GetFileNameWithoutExtension(CurrentSubFolder.Path) + ".mp4";
            return outputFileName;
        }
        public void DoDeletePicture()
        {
            if (CurrentImageItem != null)
            {
                File.Delete(CurrentImageItem.ImagePath);
                int idx = CurrentSubFolder.ImageItems.IndexOf(CurrentImageItem);
                CurrentSubFolder.ImageItems.Remove(CurrentImageItem);

                if (idx > -1 && idx < CurrentSubFolder.ImageItems.Count)
                {
                    CurrentImageItem = CurrentSubFolder.ImageItems[idx];
                    CurrentImageItem.Selected = true;
                }
                else
                {
                    CurrentImageItem = CurrentSubFolder.ImageItems[idx - 1];
                    CurrentImageItem.Selected = true;
                }
            }
        }

        private bool hasMovieEntity = false;
        public bool HasMovieEntity
        {
            get
            {
                return hasMovieEntity;
            }
            set => this.RaiseAndSetIfChanged(ref hasMovieEntity, value);
        }
        public Movies? HasMovie()
        {
            string outputDirectory = CurrentSubFolder.Path + @"\";
            string outputfile = outputDirectory + System.IO.Path.GetFileNameWithoutExtension(CurrentSubFolder.Path) + ".mp4";

            string movieName = System.IO.Path.GetFileNameWithoutExtension(outputfile);
            Movies? movies = DataController.SandboxEntities.Movies.Where(m => m.MovieName == movieName && m.FilmGroup.ToLower().Contains("image")).FirstOrDefault();
            Movies = movies;
            HasMovieEntity = (movies != null);
            return movies;
        }

        public string MovieInfo
        {
            get
            {
                return movieInfo;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref movieInfo, value);
            }
        }

        private bool hasMp4;
        private string movieInfo = string.Empty;
        private Movies currentMovie;

        public bool HasMP4
        {
            get
            {
                // getTemporaryFolder for image files
                string outputfile = OutputMoviePath();
                hasMp4 = File.Exists(outputfile);
                HasMovieEntity = hasMp4;
                return hasMp4;
            }
            set
            {
                this.RaiseAndSetIfChanged(ref hasMp4, value);
            }
        }

        //public DataGrid DgItemImages { get; internal set; }

        public void ImageFolderSelectionChanged(object? e)
        {
            //if (CurrentImageFolder != null && CurrentImageFolder.ImageItems != null)
            //CurrentImageFolder.ImageItems.DiscardBitmaps();

            CurrentImageFolder = e as MovieImage;

            if (CurrentImageFolder != null && CurrentImageFolder.ImageItems.Count > 0)
            {
                if (!string.IsNullOrEmpty(CurrentImageFolder.LastImageName))
                {
                    CurrentImageItem = CurrentImageFolder.ImageItems.Find(i => i.ImageName == CurrentImageFolder.LastImageName);
                }
                else
                    CurrentImageItem = CurrentImageFolder.ImageItems.FirstOrDefault();
                CurrentImageFolder.Info = "Images/Folders : " + CurrentImageFolder.ImageItems.Count.ToString();

            }

            if (CurrentImageFolder.SubDirectoryList != null)
            {
                CurrentSubDirectoryList = new ObservableCollection<MovieImage>(CurrentImageFolder.SubDirectoryList.OrderBy(x => x.Name));
                CurrentSubFolder = CurrentImageFolder.SubDirectoryList.Where(f => f.Id == CurrentImageFolder.LastId).FirstOrDefault();
            }
            else

                CurrentSubFolder = null;
        }

        public void SubSelectionChanged(MainWindowViewModel? mvvm, object? e)
        {
            if (mvvm != null && e != null)
            {

                CurrentSubFolder = e as MovieImage;
                //.CurrentSubFolder.Properties.Load();

                if (CurrentSubFolder != null)
                {

                    CurrentImageFolder.LastId = CurrentSubFolder.Id;
                    CurrentImageFolder.Save();

                    if (CurrentSubFolder.ImageItems.Count > 0)
                    {

                        if (!string.IsNullOrEmpty(CurrentSubFolder.LastImageName))
                        {
                            CurrentImageItem = CurrentSubFolder.ImageItems.Find(i => i.ImageName == CurrentSubFolder.LastImageName);
                        }
                        else
                            CurrentImageItem = CurrentSubFolder.ImageItems.FirstOrDefault();
                        if (CurrentImageItem != null) CurrentImageItem.Selected = true;
                        CurrentImageFolder.Info = "Images : " + CurrentSubFolder.ImageItems.Count.ToString();

                        HasMP4 = false;
                        HasMovieEntity = false;
                        Movies? movie = HasMovie();

                        mvvm.HasMovie = movie != null;
                        MVVM = mvvm;
                        CurrentMovie = movie;

                        if (movie != null)
                        {
                            CurrentSubFolder.Movies = movie;
                            CurrentSubFolder.MovieId = movie.Id;
                            HasMovieEntity = true;
                            MovieInfo = movie.ToString();
                        }
                        else
                        {
                            CurrentSubFolder.Movies = null;
                            MovieInfo = "No Movie Found";
                        }



                        string outputDirectory = CurrentSubFolder.Path + @"\temp\";
                        string outputfile = outputDirectory + System.IO.Path.GetFileNameWithoutExtension(CurrentSubFolder.Path) + ".mp4";


                    }
                }
                //if (.CurrentImageFolder.SubDirectoryList != null) .CurrentSubDirectoryList = .CurrentImageFolder.SubDirectoryList;

            }
        }

        /// <summary>
        /// Reloads the pictures.
        /// </summary>
        /// <autogeneratedoc />
        internal void ReloadPictures()
        {
            if (CurrentSubFolder != null && CurrentSubFolder.ImageItems != null)
            {
                CurrentSubFolder.ImageItems.ReloadImageItems(CurrentSubFolder.Path);
                CurrentSubFolder.ImageItems = new ImageItemsCollection(currentSubFolder.ImageItems.SortList());
                ImageItem? imageItem = CurrentSubFolder.ImageItems.Find(i => i.ImageName == currentSubFolder.LastImageName);
                if (imageItem != null)
                {
                    CurrentImageItem = imageItem;
                    MainSupport.ScrollItemImagesIntoView(imageItem);
                }
            }
        }

        #endregion
    }
    /// <summary>
    /// An item that holds picture information
    /// </summary>
    /// <seealso cref="TaymadeEntities.Models.ModelBase" />
    /// <autogeneratedoc />
    public class ImageItem : ModelBase
    {
        private Avalonia.Media.Imaging.Bitmap? imageBMP;
        private bool? bMPVisible;
        private bool? selected;
        private string? imageName;

        public string? ImagePath { get; set; }

        public string? ImageName
        {
            get
            {
                if (string.IsNullOrEmpty(imageName))
                {
                    if (!string.IsNullOrEmpty(ImagePath))
                    { imageName = Path.GetFileNameWithoutExtension(ImagePath); }

                    else imageName = "--";
                }
                return imageName;
            }
            set
            {
                string oldvalue = imageName;
                this.RaiseAndSetIfChanged(ref imageName, value);

                // see if has changed
                if (oldvalue != imageName)
                {
                    string newPath = ImagePath.Replace(oldvalue, imageName);
                    File.Move(ImagePath, newPath);
                    ImagePath = newPath;

                }
            }
        }

        [NotMapped]
        public Avalonia.Media.Imaging.Bitmap? ImageBMP
        {
            get
            {
                if (imageBMP == null)
                {
                    Support.Support.SetImageBMP(ImagePath, out imageBMP);
                }

                BMPVisible = (imageBMP != null);

                return imageBMP;
            }
            set
            {
                imageBMP = value;
                BMPVisible = (imageBMP != null);
            }
        }

        [NotMapped]
        public bool? BMPVisible { get => bMPVisible; set => bMPVisible = value; }

        [NotMapped]
        public bool? Selected { get => selected; set => this.RaiseAndSetIfChanged(ref selected, value); }
    }

    //public class FolderProperties
    //{
    //    public FolderProperties(string? path)
    //    {
    //        if (!string.IsNullOrEmpty(path))
    //        {
    //            Path = path;
    //            Load();
    //        }
    //        else Save();
    //    }

    //    public FolderProperties()
    //    {

    //    }

    //    public void Load(string path = "")
    //    {
    //        if (string.IsNullOrEmpty(path)) path = PropertiesFileName();
    //        string json = string.Empty;

    //        if (File.Exists(path))
    //        {
    //            using StreamReader reader = new StreamReader(path);
    //            json = reader.ReadToEnd();

    //            FolderProperties? props = JsonConvert.DeserializeObject<FolderProperties>(json);

    //            if (props != null)
    //            {
    //                Speed = props.Speed;
    //                Path = props.Path;
    //                Comments = props.Comments;
    //                MovieId = props.MovieId;
    //            }
    //        }
    //    }

    //    public FolderProperties(double speed, string path)
    //    {
    //        Speed = speed;
    //        Path = path;

    //        if (!File.Exists(PropertiesFileName()))
    //        {
    //            this.Save();
    //        }
    //    }

    //    public string? Comments { get; set; } = "<comment>";

    //    public double? Speed { get; set; } = 5;

    //    public string? Path { get; set; }

    //    public int? MovieId { get; set; }

    //    #region Methods

    //    public string PropertiesFileName()
    //    {
    //        string returnVal = "";
    //        returnVal = Path + @"\Properties.json";

    //        return returnVal;
    //    }
    //    public void Save()
    //    {
    //        string json = JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);

    //        using System.IO.StreamWriter writer = new StreamWriter(PropertiesFileName(), false);
    //        writer.WriteLine(json);
    //        writer.Flush();
    //        writer.Close();
    //    }
    //    #endregion
    //}

    public class ImageChangedEventArgs : System.EventArgs
    {
        public int? ImagePosition { get; internal set; }

        public string? Action { get; internal set; }

        public ImageItem ImageItem { get; internal set; }
    }
}
