using TaymadeEntities.ViewModels;
using Avalonia.Threading;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using Avalonia.Media;

namespace TaymadeEntities.Models
{
    /// <summary>
    /// 
    /// </summary>
    /// <seealso cref="System.Collections.Generic.List&lt;TaymadeEntities.Models.ImageItem&gt;" />
    /// <autogeneratedoc />
    public class ImageItemsCollection : List<ImageItem>
    {
        /// <summary>
        /// The CST image list
        /// </summary>
        /// <autogeneratedoc />
        private const string cstImageList = "ImageList";

        int index = 0;

        public delegate void ImageChangedEventHandler(object sender, ImageChangedEventArgs e);

        public event ImageChangedEventHandler? ImageChanged;

        protected virtual void OnImageChanged(ImageChangedEventArgs e)
        {
            //Busy = false;
            ImageChangedEventHandler? handler = ImageChanged;
            handler?.Invoke(this, e);
        }

        private ImageChangedEventArgs args = new ImageChangedEventArgs() { Action = "", ImagePosition = 0 };
        private double? speed;
        //private FolderProperties properties;

        #region Constructors
        public ImageItemsCollection() { }

        public ImageItemsCollection(string folderPath, MovieImage parent)
        {
            Parent = parent;
            //Speed = Parent.Speed;
            folderPath = Support.Support.FixImagePath(folderPath);
            if (!string.IsNullOrEmpty(folderPath))
            {
                if (Parent.FolderType == cstImageList || Parent.FolderType == null)
                {
                    ReloadImageItems(folderPath);
                }
                else
                {
                    List<MovieImage> tempList = new List<MovieImage>();
                    // is a list of folder
                    folderPath = Support.Support.FixImagePath(folderPath).Trim();

                    if (folderPath.Contains(".."))
                    {
                        folderPath = folderPath.Substring(0, folderPath.Length - 2);
                    }

                    this.BuildSubDirectoryList(folderPath);
                }
            }
        }

        private void BuildSubDirectoryList(string folderPath)
        {
            List<string> dir = Directory.EnumerateDirectories(folderPath).ToList();
            if (Parent != null)
            {
                if (Parent.SubDirectoryList == null) Parent.SubDirectoryList = new ObservableCollection<MovieImage>();
                foreach (var item in dir)
                {
                    if (item != folderPath)
                    {
                        // see if already found
                        MovieImage? images = Parent.SubDirectoryList.Where(i => i.Path.ToLower() == item.ToLower()).FirstOrDefault();

                        if (images == null)
                        {
                            images = new MovieImage()
                            {
                                Path = item,
                                Name = Path.GetFileNameWithoutExtension(item),
                                Id = 0,
                                Speed = 5,
                                FolderType = cstImageList,
                                ParentId = Parent.Id
                            };

                            Parent.SubDirectoryList.Add(images);
                            images.Insert();
                        }
                    }
                }

                //if (tempList.Count > 0)   Parent.SubDirectoryList = new ObservableCollection<Images>(tempList);
            }
        }

        internal List<ImageItem> SortList()
        {
            List<ImageItem> tempList = this.OrderBy(i => i.ImageName).ToList();

            return tempList;
        }

        internal void ReloadImageItems(string folderPath)
        {
            folderPath = Support.Support.FixImagePath(folderPath);
            if (Directory.Exists(folderPath))
            {
                this.Clear();
                List<string> files = Directory
                            .EnumerateFiles(folderPath, "*.*", SearchOption.AllDirectories)
                            .Where(
                                s =>
                                    s.EndsWith(".JPG", StringComparison.OrdinalIgnoreCase)
                                    || s.EndsWith(".BMP", StringComparison.OrdinalIgnoreCase)
                                    || s.EndsWith(".PNG", StringComparison.OrdinalIgnoreCase)
                            ).ToList();
                int index = this.Count + 1;
                foreach (string file in files)
                {
                    // see if we have the item already
                    ImageItem? item = this.Find(i => i.ImagePath == file);
                    if (item == null)
                    {
                        item = new ImageItem() { ImagePath = file, Id = index };
                        this.Add(item);
                        index += 1;
                    }
                }

                // sort the list by image name
                List<ImageItem> tempList = this.OrderBy(i => i.ImageName).ToList();
                this.Clear();
                foreach (var item in tempList)
                {
                    this.Add(item);
                }
            }
        }

        public ImageItemsCollection(IEnumerable<ImageItem> collection) : base(collection)
        {
        }
        #endregion

        #region Properties

        public ImageSetViewModel ISVM { get; set; }

        public MovieImage Parent { get; set; }

        //public FolderProperties Properties
        //{
        //    get
        //    {
        //        if (properties == null)
        //        {
        //            properties = new FolderProperties(Parent.Path);
        //        }
        //        return properties;
        //    }

        //    set => properties = value;
        //}
        public int Index { get => index; set => index = value; }

        public bool IsPlaying { get; set; } = false;

        #endregion

        public double? Speed
        {
            get
            {
                if (Parent != null) speed = Parent.Speed;
                return speed;
            }

            set
            {

                speed = value;
                //if (Parent != null) Parent.Speed = value;
                //if (Properties != null)
                //{
                //    if (Properties.Speed != value && value != 5)
                //    {
                //        Properties.Speed = value;
                //        Properties.Save();
                //    }
                //}
            }
        }

        #region Methods

        public void DiscardBitmaps()
        {
            //foreach (ImageItem? item in this)
            //{
            //    if (item.ImageBMP != null) item.ImageBMP.Dispose();
            //    item.ImageBMP = null;
            //}
        }

        //private SolidColorBrush backgroundColor;
        public async void Play()
        {
            IsPlaying = !IsPlaying;
            if (Index >= 0 && Index < this.Count)
            {
                args.ImageItem = this[Index];
                if (IsPlaying)
                {
                    args.Action = "Pause";
                    ISVM.CurrentIcon = ISVM.PauseIcon;
                    ISVM.PlayPauseLabel = "Pause";
                    ISVM.backgroundColor = Avalonia.Media.Brushes.LightGreen;
                }
                else
                {
                    args.Action = "Play";
                    ISVM.CurrentIcon = ISVM.PlayIcon;
                    ISVM.PlayPauseLabel = "Play";
                    ISVM.backgroundColor = Avalonia.Media.Brushes.PaleGoldenrod;
                }
                args.ImagePosition = Index;

                this.PostButtonChanges();
            }
            OnImageChanged(args);
            if (IsPlaying)
            {
                while (Index < this.Count && IsPlaying)
                {
                    if (this.Speed == null) this.Speed = 5;
                    System.Threading.Thread.Sleep((int)(this.Speed.Value * 1000));
                    MoveNext();
                }
                if (index >= this.Count)
                {
                    args.Action = "Stopped";
                    Index = 0;
                    OnImageChanged(args);
                    ISVM.backgroundColor = Avalonia.Media.Brushes.LightGray;
                }
            }
        }

        private void PostButtonChanges()
        {
            Dispatcher.UIThread.Post(() =>
            {
                ISVM.PlayButton.ImageSource = ISVM.CurrentIcon;
                ISVM.PlayButton.LabelText = ISVM.PlayPauseLabel;
                ISVM.PlayButton.Background = ISVM.backgroundColor;
            });
        }

        internal void MoveNext()
        {
            string action = "Play";
            if (IsPlaying)
            {
                action = "Play";
            }
            else if (args.Action == "Stopped") action = "Step";
            Index += 1;
            if (Index < this.Count)
            {
                args.ImagePosition = Index;
                args.ImageItem = this[Index];
                args.Action = action;
                //MVVM.RootFolder.CurrentImageItem = this[Index];
                OnImageChanged(args);
            }

        }
        internal void MovePrev()
        {
            string action = "Play";

            if (IsPlaying)
            {
            }
            else if (args.Action == "Stopped") action = "Step";
            Index -= 1;
            if (Index > 0)
            {
                args.ImagePosition = Index;
                args.ImageItem = this[Index];
                args.Action = action;
                //MVVM.RootFolder.CurrentImageItem = this[Index];
                OnImageChanged(args);
            }
        }

        internal void StopPlaying()
        {
            if (IsPlaying)
            {
                Index = this.Count;
                IsPlaying = false;
                // chang Current icon to play and change playtext to play
                ISVM.CurrentIcon = ISVM.PlayIcon;
                ISVM.PlayPauseLabel = "Play";

                ISVM.PlayButton.ImageSource = ISVM.PlayIcon;
                ISVM.PlayButton.LabelText = "Play";
                ISVM.backgroundColor = new SolidColorBrush(Avalonia.Media.Colors.LightGray);

                System.Threading.Thread.Sleep(100);

                this.PostButtonChanges();
            }
        }

        #endregion
    }
}
