using Avalonia.Controls;
using DocumentFormat.OpenXml.Presentation;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml.Vml.Spreadsheet;
using DynamicData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.Extensions.Configuration;
using Newtonsoft;
using Newtonsoft.Json;
//using static TaymadeEntities.Support.MissingFileFinder;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ReactiveUI;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Xml;
using TaymadeEntities.Models;
using TaymadeEntities.Support;
using TaymadeEntities.ViewModels;

namespace TaymadeEntities.Models
{

    public class FrameSet :ModelBase
    {
        private bool hasMovie = false;
        private string? moviePath;

        [JsonIgnore()]
        public int Id { get; set; }
        
        [JsonProperty(PropertyName = "Index")]
        public int Index { get; set; }

        [JsonProperty(PropertyName = "StartImage")]
        
        public int StartImage { get; set; }

        [JsonProperty(PropertyName = "StartImageName")]
        public string? StartImageName { get; set; }


        [JsonProperty(PropertyName = "MoviePath")]
        public string? MoviePath
        {
            get => moviePath;
            set
            { 
                this.RaiseAndSetIfChanged(ref moviePath, value);
                
            }
        }

        public int FrameSetHeaderId { get; set; }

        [JsonProperty(PropertyName = "EndImage")]
        public int EndImage { get; set; }

        [JsonProperty(PropertyName = "FrameRate")]
        public double FrameRate { get; set; } = 1.0;

        [JsonProperty(PropertyName = "HasMovie")]
        public bool HasMovie
        {
            get => hasMovie;
            set
            { 
                this.RaiseAndSetIfChanged(ref hasMovie, value);
            }
        }


        [JsonIgnore()]
        public FrameSetHeader? FrameSetHeader { get; internal set; }


        internal FrameSet Clone()
        {
            FrameSet clone = new FrameSet()
            {
                Id = this.Id,
                StartImage = this.StartImage,
                EndImage = this.EndImage,
                StartImageName = this.StartImageName,
                Index = this.Index,
                FrameRate = this.FrameRate,
                HasMovie = this.HasMovie,
                MoviePath = this.MoviePath
            };
            return clone;

        }

        internal void Delete()
        {
            DataController.MovieController.DeleteFrameSet(this);
        }

        internal void Save()
        {
            DataController.MovieController.UpdateFrameSet(this);
        }
    }

    public class ImageChangedEventArgs : System.EventArgs
    {

        #region Public Properties

        public string? Action { get; internal set; }
        public ImageItem ImageItem { get; internal set; }
        public int? ImagePosition { get; internal set; }

        #endregion Public Properties

    }

    /// <summary>
    /// An item that holds picture information
    /// </summary>
    /// <seealso cref="TaymadeEntities.Models.ModelBase" />
    /// <autogeneratedoc />
    public class ImageItem : ModelBase
    {

        #region Private Fields

        private bool? bMPVisible;
        private Avalonia.Media.Imaging.Bitmap? imageBMP;
        private string? imageName;
        private bool? selected;
        private int frameSetIndex = 1;

        #endregion Private Fields

        #region Public Properties

        [NotMapped]
        public bool? BMPVisible { get => bMPVisible; set => bMPVisible = value; }

        [NotMapped]
        public Avalonia.Media.Imaging.Bitmap? ImageBMP
        {
            get
            {
                if (imageBMP == null)
                {
                    Support.Support.SetImageBMP(ImagePath, out imageBMP);
                }

                BMPVisible = (imageBMP != null);

                return imageBMP;
            }
            set
            {
                imageBMP = value;
                BMPVisible = (imageBMP != null);
            }
        }

        public string? ImageName
        {
            get
            {
                if (string.IsNullOrEmpty(imageName))
                {
                    if (!string.IsNullOrEmpty(ImagePath))
                    { imageName = Path.GetFileNameWithoutExtension(ImagePath); }
                    else imageName = "--";
                }
                return imageName;
            }
            set
            {
                string oldvalue = imageName;
                this.RaiseAndSetIfChanged(ref imageName, value);
                if (value == null) return;
                // see if has changed
                if (oldvalue != null && oldvalue != imageName)
                {
                    string newPath = ImagePath.Replace(oldvalue, imageName);
                    File.Move(ImagePath, newPath);
                    ImagePath = newPath;
                }
            }
        }

        public int FrameSetIndex
        {
            get => frameSetIndex;
            set => this.RaiseAndSetIfChanged(ref frameSetIndex, value);
        }
        public string? ImagePath { get; set; }
        [NotMapped]
        public bool? Selected { get => selected; set => this.RaiseAndSetIfChanged(ref selected, value); }

        #endregion Public Properties

        #region Public Methods

        public void ReloadImage()
        {
            if (!string.IsNullOrEmpty(ImagePath))
            {
                Support.Support.SetImageBMP(ImagePath, out imageBMP);
            }
            this.RaisePropertyChanged(nameof(ImageBMP));
        }

        #endregion Public Methods

    }


    /// <summary>
    ///
    /// </summary>
    /// <seealso cref="TaymadeEntities.Models.ModelBase" />
    /// <autogeneratedoc />
    public class MovieImage : ModelBase
    {

        #region Private Fields

        private const string cstImageList = "ImageList";

        private bool commandIsVisible = false;
        //private FolderProperties properties;
        private string? comments = null;

        private string? folderType;
        private ImageItemsCollection? imageItems;
        private string? info;
        private int? movieId;
        private Movies? movies;
        /// <summary>
        /// The name
        /// </summary>
        /// <autogeneratedoc />
        private string? name;

        /// <summary>
        /// The path
        /// </summary>
        /// <autogeneratedoc />
        private string? path;

        private string playButtonContent = "Play";
        private bool? selected;

        /// <summary>
        /// The speed
        /// </summary>
        /// <autogeneratedoc />
        private double? speed;
        private ObservableCollection<MovieImage> subDirectoryList;
        //private List<FrameSet>? frameSetList;
        private FrameSet currentFrameSet;

        #endregion Private Fields

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="Images"/> class.
        /// </summary>
        /// <autogeneratedoc />
        public MovieImage()
        {
            PlayButtonContent = "Play";
            PropertyChanged += Images_PropertyChanged;
            //FrameSetlist = new List<FrameSet>();
            FrameSet frameSet = new FrameSet()
            {
                Index = 1,
                StartImage = 1
            };

        }

        #endregion Public Constructors

        #region Public Properties

        [NotMapped]
        public bool CommandIsVisible { get => commandIsVisible; set => this.RaiseAndSetIfChanged(ref commandIsVisible, value); }

        public string? Comments
        {
            get
            {
                return comments;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref comments, value);
            }
        }

        public string? FolderType
        {
            get => folderType;
            set => this.RaiseAndSetIfChanged(ref folderType, value);
        }

        [NotMapped]

        public FrameSetHeader? FrameSetHeader
        {
            get
            {
                if (frameSetHeader == null)
                {
                    frameSetHeader = new FrameSetHeader();
                    frameSetHeader.FrameSetList = new List<FrameSet>();
                }
                return frameSetHeader;
            }
            set => this.RaiseAndSetIfChanged(ref frameSetHeader, value);
        }

        //[NotMapped]
        //public List<FrameSet>? FrameSetlist
        //{
        //    get
        //    {
        //        FromJson();
        //        return frameSetList;
        //    }

        //    set
        //    {
        //        this.RaiseAndSetIfChanged(ref frameSetList, value);
        //        if (value != null)
        //        {
        //            Json = ToJson();
        //        }
        //    }
        //}

        [NotMapped]
        public ImageItemsCollection? ImageItems
        {
            get
            {
                if (imageItems == null)
                {
                    if (this.FolderType == null) FolderType = cstImageList;
                    imageItems = new ImageItemsCollection(Path, this);
                    ;
                    //imageItems.ImageChanged += ImageItems_PropertyChanged;
                    if (speed == null) speed = 5;
                    //if (!string.IsNullOrEmpty(path))
                    //    Properties = new FolderProperties(Path);
                }
                return imageItems;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref imageItems, value);
                if (value != null && value.Count > 0)
                {
                }
            }
        }

        [NotMapped]
        public string? Info { get => info; set => this.RaiseAndSetIfChanged(ref info, value); }

        public string? Json { get; set; }
        public int? LastId { get; set; }

        public string? LastImageName { get; set; }

        public int? MovieId
        {
            get
            {
                if (movieId == null)
                { }
                else

                {
                    Movies = DataController.SandboxEntities.Movies.Find(movieId);
                }

                return movieId;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref movieId, value);
                if (FolderType == cstImageList && value != null)
                {
                    //Properties.MovieId = movieId;

                    if (Id == 0) this.Insert(); else this.Save();
                }
            }
        }

        [NotMapped]
        public Movies? Movies
        {
            get => movies;
            set
            {
                this.RaiseAndSetIfChanged(ref movies, value);

                if (value != null)
                {
                    movieId = value.Id;
                }
                else
                {
                    movieId = null;
                }
            }
        }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>
        /// The name.
        /// </value>
        /// <autogeneratedoc />
        public string? Name
        {
            get => name;
            set
            {
                string oldName = name;
                this.RaiseAndSetIfChanged(ref name, value);

                if (FolderType == cstImageList)
                {
                    // if last character of path = . or .. it is a parent folder;

                    string dir = System.IO.Path.GetDirectoryName(Path);
                    int len = dir.Length;
                    string pathFolder = Path.Substring(len + 1);
                    if (pathFolder == "." || pathFolder == "..")
                    {
                        // new folder add name to folder
                        Path = pathFolder + Name;
                        if (Directory.Exists(Path))
                        {
                        }
                        else
                        {
                            Directory.CreateDirectory(Path);
                        }
                        this.ImageItems.Clear();
                        this.ImageItems.ReloadImageItems(value);
                    }
                    else
                    {
                        // changing the name
                        string newPath = dir + @"\" + name;
                        if (!Directory.Exists(newPath) && Directory.Exists(Path))
                        {
                            // we can move
                            if (Path.ToLower() != newPath.ToLower())
                                Directory.Move(Path, newPath);
                            else Directory.CreateDirectory(Path);
                            this.ImageItems.Clear();
                            this.ImageItems.ReloadImageItems(value);
                        }

                        if (path != newPath)
                        {
                            Path = newPath;
                            Save();
                        }
                    }
                }
            }
        }

        public int? ParentId { get; set; }

        /// <summary>
        /// Gets or sets the path.
        /// </summary>
        /// <value>
        /// The path.
        /// </value>
        /// <autogeneratedoc />
        public string? Path
        {
            get => path;
            set
            {
                string? oldPath = path;
                this.RaiseAndSetIfChanged(ref path, value);
                if (!string.IsNullOrEmpty(value) && !string.IsNullOrEmpty(oldPath) &&
                    oldPath.ToLower() != value.ToLower() && ImageItems != null)
                {
                    this.ImageItems.Clear();
                    this.ImageItems.ReloadImageItems(value);
                }
            }
        }

        //public MainWindowViewModel MVVM { get; internal set; }
        [NotMapped]
        public string PlayButtonContent
        {
            get => playButtonContent; set
            {
                this.RaiseAndSetIfChanged(ref playButtonContent, value);
            }
        }

        [NotMapped]
        public bool? Selected { get => selected; set => this.RaiseAndSetIfChanged(ref selected, value); }

        /// <summary>
        /// Gets or sets the speed.
        /// </summary>
        /// <value>
        /// The speed.
        /// </value>
        /// <autogeneratedoc />
        public double? Speed
        {
            get
            {
                return speed;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref speed, value);

                if (ImageItems != null)
                {
                    imageItems.Speed = value;
                }
            }
        }

        [NotMapped]
        public ObservableCollection<MovieImage> SubDirectoryList
        {
            get
            {
                if (subDirectoryList == null) subDirectoryList = new ObservableCollection<MovieImage>();
                if (subDirectoryList.Count == 0)
                {
                    if (Id > 0)
                    {
                        List<MovieImage>? tempList = DataController.MovieController.GetMovieImagesById(this.Id);
                        //.MovieImage.Where(i => i.ParentId == Id).OrderBy(x => x.Name).ToList();
                        if (tempList != null)
                        {
                            subDirectoryList = new ObservableCollection<MovieImage>(tempList);
                        }
                    }
                }

                return subDirectoryList;
            }

            set => this.RaiseAndSetIfChanged(ref subDirectoryList, value);
        }

        [NotMapped]
        public FrameSet CurrentFrameSet
        {
            get
            {
                if (currentFrameSet != null)
                {
                    //string? moviePath = GenerateMovieFrameSetName();
                    //currentFrameSet.HasMovie = File.Exists(moviePath);
                    //this.RaisePropertyChanged(nameof(currentFrameSet.HasMovie));
                }
                return currentFrameSet;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref currentFrameSet, value);
                if (value != null)
                {
                    string? moviePath = GenerateMovieFrameSetName();
                    value.HasMovie = File.Exists(moviePath);
                    this.RaisePropertyChanged(nameof(value.HasMovie));
                }
            }
        }

        #endregion Public Properties

        #region Public Methods

        private  string? GenerateMovieFrameSetName()
        {
            MovieImage currentSubFolder = this;
            FrameSet currentFrameSet = currentSubFolder.CurrentFrameSet;
            string moviePath = "";
            if (currentFrameSet != null)
            {
                string frameSetName = "FrameSet" + currentFrameSet.Index.ToString("000").Trim();
                string outputDirectory = System.IO.Path.Combine(currentSubFolder.Path, frameSetName);
                string movieName = this.Name + ".mp4";
                moviePath = System.IO.Path.Combine(outputDirectory, movieName);
            }
            return moviePath;
        }
        public void Save()
        {
            if (Id == 0) Insert();
            try
            {
                this.Json = ToJson();

                DataController.MovieController.SaveMovieImage(this);
            }
            catch (Exception ex)
            {
                string msg = "error Saving movie Image : " + Id.ToString() + " : " + Name;
                //Support.Support.Logger.Error(ex, msg);

                MVMLogs logs = new MVMLogs(ex, "database", "Error", "Movie Images");
            }
        }

        internal bool jsonRead = false;
        private FrameSetHeader? frameSetHeader;

        internal void FromJson()
        {
            if (!string.IsNullOrEmpty(Json) && !jsonRead)
            {
                if (Json[0] == '[')
                {
                    List<FrameSet>? tempList = JsonConvert.DeserializeObject<List<FrameSet>>(Json);
                    if (tempList != null)
                    {
                        if (FrameSetHeader == null) FrameSetHeader = DataController.MovieController.GetFrameSetHeaderByMovieImageId(this.Id);
                        FrameSetHeader.FrameSetList = new List<FrameSet>(tempList);
                    }
                    jsonRead = true;
                }
                else
                {
                    FrameSetHeader? tempHeaader = JsonConvert.DeserializeObject<FrameSetHeader>(Json);
                    if (tempHeaader != null)
                    {
                        FrameSetHeader = tempHeaader;
                        //frameSetList = tempHeaader.FrameSetList;
                        FrameSetHeader.MovieImageId = this.Id;
                    }

                    FrameSetHeader = DataController.MovieController.GetFrameSetHeaderByMovieImageId(this.Id);
                    if (FrameSetHeader!= null && FrameSetHeader.Id > 0)
                    {
                        FrameSetHeader.FrameSetList = DataController.movieController.GetFrameSetsByHeaderId(FrameSetHeader.Id);
                        //frameSetList = FrameSetHeader.FrameSetList;
                    }
                }
            }
            else
            {
                //FrameSetHeader? tempHeaader = JsonConvert.DeserializeObject<FrameSetHeader>(Json);
                //if (tempHeaader != null)
                //{
                //    FrameSetHeader = tempHeaader;
                //    frameSetList = tempHeaader.FrameSetList;
                //    FrameSetHeader.MovieImageId = this.Id;
                //}

                FrameSetHeader = DataController.MovieController.GetFrameSetHeaderByMovieImageId(this.Id);
                if (FrameSetHeader != null && FrameSetHeader.Id > 0)
                {
                    FrameSetHeader.FrameSetList = DataController.movieController.GetFrameSetsByHeaderId(FrameSetHeader.Id);
                    //frameSetList = FrameSetHeader.FrameSetList;
                }
            }
        }

        private string? ToJson()
        {
            string json = string.Empty;
            if (FrameSetHeader != null && FolderType == cstImageList)
            {
                FrameSetHeader = DataController.MovieController.GetFrameSetHeaderByMovieImageId(this.Id);
                if (FrameSetHeader.MovieImageId == 0)
                    FrameSetHeader.MovieImageId = this.Id;
                else
                {
                    FrameSetHeader = DataController.MovieController.GetFrameSetHeaderByMovieImageId(this.Id);
                }

                if (FrameSetHeader.Id == 0)
                {
                    DataController.MovieController.InsertFrameSetHeader(FrameSetHeader);
                    FrameSetHeader.FrameSetList = new List<FrameSet>();
                    FrameSet frameSet = FrameSetHeader.CreateFrameSet(this.ImageItems.Count);
                    FrameSetHeader.FrameSetList.Add(frameSet);
                }
                else
                {
                    DataController.MovieController.UpdateFrameSetHeader(FrameSetHeader);
                    FrameSetHeader.FrameSetList = DataController.movieController.GetFrameSetsByHeaderId(FrameSetHeader.Id);
                }
                //json = JsonConvert.SerializeObject(FrameSetHeader);
            }

            foreach (var item in FrameSetHeader.FrameSetList)
            {
                item.FrameSetHeaderId = FrameSetHeader.Id;
                DataController.MovieController.UpdateFrameSet(item);
            }

            //json = JsonConvert.SerializeObject(FrameSetlist);
            return json;
        }

        #endregion Public Methods

        #region Internal Methods

        internal void Delete()
        {
            DataController.MovieController.DeleteMovieImage(this);
        }

        internal void Insert()
        {
            if (Id == 0)
            {
                DataController.MovieController.AddMovieImage(this);
            }
        }

        #endregion Internal Methods

        #region Private Methods

        private void Images_PropertyChanged(object? sender, PropertyChangedEventArgs e)
        {
            //this.Save();
        }

        #endregion Private Methods
    }

    public class RootFolder : MovieImage
    {

        #region Private Fields

        private MovieImage? currentImageItem;
        private ImageItem? currentImageItem1;
        private Movies currentMovie;
        private ObservableCollection<MovieImage>? currentSubDirectoryList;
        private MovieImage? currentSubFolder;

        private bool hasMovieEntity = false;

        private bool hasMp4;

        private string movieInfo = string.Empty;
        private bool multiSelect = false;

        #endregion Private Fields

        #region Public Constructors

        public RootFolder()
        {
            this.BuildSubFolders();
        }

        #endregion Public Constructors

        #region Public Properties

        /// <summary>
        /// Gets or sets the current image folder.
        /// </summary>
        /// <value>
        /// The current image folder.
        /// </value>
        /// <autogeneratedoc />
        public Models.MovieImage CurrentImageFolder
        {
            get
            {
                return currentImageItem;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref currentImageItem, value);
                if (value != null)
                {
                    if (this.LastId != value.Id)
                    {
                        this.LastId = value.Id;
                        // CurrentImageFolder.ImageItems.ImageChanged += ImageItems_ImageChanged;
                        this.Save();
                    }
                }
            }
        }

        /// <summary>
        /// Gets or sets the current image item.
        /// </summary>
        /// <value>
        /// The current image item.
        /// </value>
        /// <autogeneratedoc />
        public ImageItem? CurrentImageItem
        {
            get => currentImageItem1;
            set
            {
                if (currentImageItem1 != null && MultiSelect == false) currentImageItem1.Selected = false;
                this.RaiseAndSetIfChanged(ref currentImageItem1, value);
                if (value != null)
                {
                    value.Selected = true;
                    if (CurrentSubFolder != null && !ImageItems.IsPlaying)
                    {
                        if (CurrentSubFolder.LastImageName != value.ImageName)
                        {
                            CurrentSubFolder.LastImageName = value.ImageName;
                            CurrentSubFolder.Save();
                        }

                        if (CurrentSubFolder.FrameSetHeader != null
                            && CurrentSubFolder.FrameSetHeader.FrameSetList != null)
                        {
                            var frameSet = CurrentSubFolder.FrameSetHeader.FrameSetList.Where(f => f.Index == currentImageItem1.FrameSetIndex).FirstOrDefault();
                            CurrentSubFolder.CurrentFrameSet = frameSet;
                        }
                    }
                }
            }
        }

        public Movies CurrentMovie
        {
            get => currentMovie;
            set => this.RaiseAndSetIfChanged(ref currentMovie, value);
        }

        public ObservableCollection<MovieImage> CurrentSubDirectoryList
        {
            get
            {
                if (currentSubDirectoryList == null)
                {
                    currentSubDirectoryList = new ObservableCollection<MovieImage>();
                }
                return new ObservableCollection<MovieImage>(currentSubDirectoryList.OrderBy(x => x.Name));
            }

            set => this.RaiseAndSetIfChanged(ref currentSubDirectoryList, value);
        }

        /// <summary>
        /// Gets or sets the current sub folder.
        /// </summary>
        /// <value>
        /// The current sub folder.
        /// </value>
        /// <autogeneratedoc />
        public MovieImage? CurrentSubFolder
        {
            get => currentSubFolder;
            set
            {
                this.RaiseAndSetIfChanged(ref currentSubFolder, value);
                if (currentSubFolder != null && value != null)
                {
                    currentSubFolder.ImageItems.ImageChanged += ImageItems_ImageChanged;

                    if (CurrentImageFolder != null)
                    {
                        if (CurrentImageFolder.LastId != value.Id)
                        {
                            CurrentImageFolder.LastId = value.Id;
                            CurrentImageFolder.Save();
                            if (currentSubFolder.ImageItems != null && currentSubFolder.ImageItems.Count > 0)
                            {
                                if (!string.IsNullOrEmpty(currentSubFolder.LastImageName))
                                {
                                    CurrentImageItem = currentSubFolder.ImageItems.Where(n => n.ImageName == currentSubFolder.LastImageName).FirstOrDefault();
                                }
                                else
                                    CurrentImageItem = currentSubFolder.ImageItems.FirstOrDefault();
                            }
                        }
                    }

                    if (CurrentSubFolder.FrameSetHeader != null && CurrentSubFolder.FrameSetHeader.FrameSetList != null)
                    {
                        int index = 0;
                        foreach (var item in CurrentSubFolder.FrameSetHeader.FrameSetList)
                        {

                            if (item.EndImage == 0) item.EndImage = CurrentSubFolder.ImageItems.Count;
                            for (int i = 0; i < item.EndImage - item.StartImage; i++)
                            {
                                if (index < CurrentSubFolder.ImageItems.Count)
                                {
                                    var imageitem = CurrentSubFolder.ImageItems[index];
                                    imageitem.FrameSetIndex = item.Index;
                                }
                                index += 1;
                            }
                        }

                    }
                }
            }
        }

        public bool HasMovieEntity
        {
            get
            {
                return hasMovieEntity;
            }
            set => this.RaiseAndSetIfChanged(ref hasMovieEntity, value);
        }

        public bool HasTempMP4
        {
            get
            {
                // getTemporaryFolder for image files
                string outputfile = OutputMoviePath();
                hasMp4 = File.Exists(outputfile);
                HasMovieEntity = hasMp4;
                return hasMp4;
            }
            set
            {
                this.RaiseAndSetIfChanged(ref hasMp4, value);
            }
        }

        public string MovieInfo
        {
            get
            {
                return movieInfo;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref movieInfo, value);
            }
        }

        public MovieViewModelBase MVVM { get; set; }
        public bool MultiSelect
        {
            get => multiSelect;
            set => this.RaiseAndSetIfChanged(ref multiSelect, value);
        }

        #endregion Public Properties

        #region Public Methods

        public void BuildSubFolders()
        {
            MovieImage? images = DataController.MovieController.GetMovieImagesByFolder("Root")?.FirstOrDefault();

            //.MovieImage.Where(i => i.FolderType == "Root").FirstOrDefault();
            // get subfolders
            if (images != null)
            {
                LastId = images.LastId;
                Id = images.Id;
                FolderType = images.FolderType;

                // get an ordered list of sub folders
                List<MovieImage>? movieImages = DataController.MovieController.GetMovieImagesById(Id);
                if (movieImages != null)
                {
                    SubDirectoryList = new ObservableCollection<MovieImage>(movieImages);
                    //DataController.MovieImageEntity.MovieImage.Where(i => i.ParentId == Id).OrderBy(d => d.Name.ToLower()).ToList());

                    if (LastId != null)
                    {
                        // get an ordered list of images
                        images = SubDirectoryList.Where(f => f.Id == LastId).OrderBy(i => i.Name).FirstOrDefault();
                        if (images != null)
                        {
                            CurrentImageFolder = images;
                            // see if we can find sub folder
                            if (CurrentImageFolder.LastId != null)
                            {
                                images = CurrentImageFolder.SubDirectoryList.Where(f => f.Id == CurrentImageFolder.LastId).FirstOrDefault();
                                CurrentSubFolder = images;

                                if (images != null && images.ImageItems.Count > 0 && !string.IsNullOrEmpty(images.LastImageName))
                                {
                                    CurrentImageItem = images.ImageItems.Where(it => it.ImageName == images.LastImageName).FirstOrDefault();
                                    //    MainSupport.ScrollItemImagesIntoView(CurrentImageItem);
                                }
                            }
                        }
                    }
                }
                else CurrentImageFolder = SubDirectoryList.FirstOrDefault();
            }
        }
        public void DoDeletePicture()
        {
            if (CurrentImageItem != null)
            {
                try
                {
                    Avalonia.Threading.Dispatcher.UIThread.Post(() =>
                {
                    File.Delete(CurrentImageItem.ImagePath);
                    int idx = CurrentSubFolder.ImageItems.IndexOf(CurrentImageItem);
                    CurrentSubFolder.ImageItems.Remove(CurrentImageItem);

                    if (idx > -1 && idx < CurrentSubFolder.ImageItems.Count)
                    {
                        CurrentImageItem = CurrentSubFolder.ImageItems[idx];
                        CurrentImageItem.Selected = true;
                    }
                    else
                    {
                        CurrentImageItem = CurrentSubFolder.ImageItems[idx - 1];
                        CurrentImageItem.Selected = true;
                    }
                });
                }
                catch (Exception ex)
                {
                    // throw;
                }
            }
        }

        public Movies? HasMovie()
        {
            string outputDirectory = CurrentSubFolder.Path + @"\";
            string outputfile = outputDirectory + System.IO.Path.GetFileNameWithoutExtension(CurrentSubFolder.Path) + ".mp4";

            string movieName = System.IO.Path.GetFileNameWithoutExtension(outputfile);
            Movies? movies = DataController.SandboxEntities.Movies.Where(m => m.MovieName == movieName && m.FilmGroup.ToLower().Contains("image")).FirstOrDefault();
            Movies = movies;
            HasMovieEntity = (movies != null);
            return movies;
        }

        public void ImageFolderSelectionChanged(object? e)
        {
            //if (CurrentImageFolder != null && CurrentImageFolder.ImageItems != null)
            //CurrentImageFolder.ImageItems.DiscardBitmaps();

            CurrentImageFolder = e as MovieImage;

            if (CurrentImageFolder != null && CurrentImageFolder.ImageItems.Count > 0)
            {
                if (!string.IsNullOrEmpty(CurrentImageFolder.LastImageName))
                {
                    CurrentImageItem = CurrentImageFolder.ImageItems.Find(i => i.ImageName == CurrentImageFolder.LastImageName);
                }
                else
                    CurrentImageItem = CurrentImageFolder.ImageItems.FirstOrDefault();
                CurrentImageFolder.Info = "Images/Folders : " + CurrentImageFolder.ImageItems.Count.ToString();
            }

            if (CurrentImageFolder.SubDirectoryList != null)
            {
                CurrentSubDirectoryList = new ObservableCollection<MovieImage>(CurrentImageFolder.SubDirectoryList.OrderBy(x => x.Name));
                CurrentSubFolder = CurrentImageFolder.SubDirectoryList.Where(f => f.Id == CurrentImageFolder.LastId).FirstOrDefault();
            }
            else

                CurrentSubFolder = null;
        }

        public string MoviePath()
        {
            string outputFileName = CurrentSubFolder.Path + @"\" + System.IO.Path.GetFileNameWithoutExtension(CurrentSubFolder.Path) + ".mp4";
            return outputFileName;
        }

        public string OutputMoviePath()
        {
            string outputFileName = TempDirectory() + @"\" + System.IO.Path.GetFileNameWithoutExtension(CurrentSubFolder.Path) + ".mp4";
            return outputFileName;
        }

        /// <summary>
        /// Reloads the pictures.
        /// </summary>
        /// <autogeneratedoc />
        public void ReloadPictures()
        {
            if (CurrentSubFolder != null && CurrentSubFolder.ImageItems != null)
            {
                CurrentSubFolder.ImageItems.ReloadImageItems(CurrentSubFolder.Path);
                CurrentSubFolder.ImageItems = new ImageItemsCollection(currentSubFolder.ImageItems.SortList());
                int index = 1;
                foreach (var item in currentSubFolder.ImageItems)
                {
                    item.Id = index;
                    index += 1;
                }
                ImageItem? imageItem = CurrentSubFolder.ImageItems.Find(i => i.ImageName == currentSubFolder.LastImageName);
                if (imageItem != null)
                {
                    CurrentImageItem = imageItem;
                    //   MainSupport.ScrollItemImagesIntoView(imageItem);
                }

                SetImagesFrameSetIndex();
            }
        }

        public void SetImagesFrameSetIndex()
        {
            if (CurrentSubFolder.FrameSetHeader != null && CurrentSubFolder.FrameSetHeader.FrameSetList != null)
            {
                // sort FrameSetlist by Index

                CurrentSubFolder.FrameSetHeader.FrameSetList = CurrentSubFolder.FrameSetHeader.FrameSetList.OrderBy(f => f.Index).ToList();
                //int indexer = 1;
                foreach (FrameSet frameSet in CurrentSubFolder.FrameSetHeader.FrameSetList)
                {
                    //frameSet.Index = indexer;
                    //indexer += 1;
                    for (int i = frameSet.StartImage - 1; i < CurrentSubFolder.ImageItems.Count; i++)
                    {
                        var item = CurrentSubFolder.ImageItems[i];
                        item.FrameSetIndex = frameSet.Index;
                    }
                }

            }
        }

        //public DataGrid DgItemImages { get; internal set; }
        public void SubSelectionChanged(MovieViewModelBase? mvvm, object? e)
        {
            if (mvvm != null && e != null)
            {
                CurrentSubFolder = e as MovieImage;
                //.CurrentSubFolder.Properties.Load();

                if (CurrentSubFolder != null)
                {
                    CurrentImageFolder.LastId = CurrentSubFolder.Id;
                    CurrentImageFolder.Save();

                    if (CurrentSubFolder.ImageItems.Count > 0)
                    {
                        if (!string.IsNullOrEmpty(CurrentSubFolder.LastImageName))
                        {
                            CurrentImageItem = CurrentSubFolder.ImageItems.Find(i => i.ImageName == CurrentSubFolder.LastImageName);
                        }
                        else
                            CurrentImageItem = CurrentSubFolder.ImageItems.FirstOrDefault();
                        if (CurrentImageItem != null) CurrentImageItem.Selected = true;
                        CurrentImageFolder.Info = "Images : " + CurrentSubFolder.ImageItems.Count.ToString();

                        HasTempMP4 = false;
                        HasMovieEntity = false;
                        Movies? movie = HasMovie();

                        mvvm.HasMovie = movie != null;
                        MVVM = mvvm;
                        CurrentMovie = movie;

                        if (movie != null)
                        {
                            CurrentSubFolder.Movies = movie;
                            CurrentSubFolder.MovieId = movie.Id;
                            HasMovieEntity = true;
                            MovieInfo = movie.ToString();
                        }
                        else
                        {
                            CurrentSubFolder.Movies = null;
                            MovieInfo = "No Movie Found";
                        }

                        string outputDirectory = CurrentSubFolder.Path + @"\temp\";
                        string outputfile = outputDirectory + System.IO.Path.GetFileNameWithoutExtension(CurrentSubFolder.Path) + ".mp4";
                    }
                }
                //if (.CurrentImageFolder.SubDirectoryList != null) .CurrentSubDirectoryList = .CurrentImageFolder.SubDirectoryList;
            }
        }

        public string TempDirectory(string addName = "temp")
        {
            if (currentSubFolder != null && !string.IsNullOrEmpty(CurrentSubFolder.Path))
            {
                string outputDirectory = System.IO.Path.Combine(CurrentSubFolder.Path, addName);
                return outputDirectory;
            }
            else return "";
        }

        #endregion Public Methods

        #region Private Methods

        private void ImageItems_ImageChanged(object sender, ImageChangedEventArgs e)
        {
            if (e.Action == "Play")
            {
                CurrentImageItem = e.ImageItem;
            }
        }

        #endregion Private Methods
    }
    //public class FolderProperties
    //{
    //    public FolderProperties(string? path)
    //    {
    //        if (!string.IsNullOrEmpty(path))
    //        {
    //            Path = path;
    //            Load();
    //        }
    //        else Save();
    //    }

    //    public FolderProperties()
    //    {
    //    }

    //    public void Load(string path = "")
    //    {
    //        if (string.IsNullOrEmpty(path)) path = PropertiesFileName();
    //        string json = string.Empty;

    //        if (File.Exists(path))
    //        {
    //            using StreamReader reader = new StreamReader(path);
    //            json = reader.ReadToEnd();

    //            FolderProperties? props = JsonConvert.DeserializeObject<FolderProperties>(json);

    //            if (props != null)
    //            {
    //                Speed = props.Speed;
    //                Path = props.Path;
    //                Comments = props.Comments;
    //                MovieId = props.MovieId;
    //            }
    //        }
    //    }

    //    public FolderProperties(double speed, string path)
    //    {
    //        Speed = speed;
    //        Path = path;

    //        if (!File.Exists(PropertiesFileName()))
    //        {
    //            this.Save();
    //        }
    //    }

    //    public string? Comments { get; set; } = "<comment>";

    //    public double? Speed { get; set; } = 5;

    //    public string? Path { get; set; }

    //    public int? MovieId { get; set; }

    //    #region Methods

    //    public string PropertiesFileName()
    //    {
    //        string returnVal = "";
    //        returnVal = Path + @"\Properties.json";

    //        return returnVal;
    //    }
    //    public void Save()
    //    {
    //        string json = JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);

    //        using System.IO.StreamWriter writer = new StreamWriter(PropertiesFileName(), false);
    //        writer.WriteLine(json);
    //        writer.Flush();
    //        writer.Close();
    //    }
    //    #endregion
    //}
}