//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaymadeEntities.Models
{
    using NLog;
    using ReactiveUI;
    using System;
    using System.Collections.ObjectModel;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using Avalonia.Metadata;
    using System.Diagnostics;


    /// <summary>
    /// Defines the <see cref="Movies" />.
    /// </summary>
    [MetadataType(typeof(MovieMetaData))]

    public partial class Movies : ModelBase, IDisposable
    {

        //private static Logger logger = LogManager.GetCurrentClassLogger();

        #region Private Fields

        /// <summary>
        /// Defines the added.
        /// </summary>
        private DateTime? added = DateTime.MinValue;

        /// <summary>
        /// Defines the addedOn.
        /// </summary>
        private string? addedOn;

        /// <summary>
        /// Defines the bookmarks.
        /// </summary>
        private ObservableCollection<Bookmark>? bookmarks;

        /// <summary>
        /// Defines the casts.
        /// </summary>
        private ICollection<Cast>? casts;

        private Director? director;

        private int? directorID;

        private bool dirty = false;

        private bool disposedValue;

        /// <summary>
        /// Defines the durationSeconds.
        /// </summary>
        private int? durationSeconds;

        private Bookmark? endBookmark;

        /// <summary>
        /// Defines the episode.
        /// </summary>
        private int? episode;

        /// <summary>
        /// Defines the episodeEntity.
        /// </summary>
        private TVEpisode? episodeEntity;

        private int? episodeNumber;

        /// <summary>
        /// Defines the filmGroup.
        /// </summary>
        private string? filmGroup;

        /// <summary>
        /// Defines the hasChapters.
        /// </summary>
        private bool? hasChapters;

        /// <summary>
        /// Defines the hasEpisodes.
        /// </summary>
        private bool? hasEpisodes;

        private bool? hasSeason;

        private bool? hasSeries;

        private int id;

        /// <summary>
        /// Defines the imagePath.
        /// </summary>
        private string? imagePath;

        /// <summary>
        /// Defines the imagesCount.
        /// </summary>
        private int? imagesCount;

        /// <summary>
        /// Defines the iMDBID.
        /// </summary>
        private string? iMDBID;

        /// <summary>
        /// Defines the info.
        /// </summary>
        private string? info;

        private bool isLoaded = false;

        private string? json;

        /// <summary>
        /// Defines the link1.
        /// </summary>
        private int? link1;

        private bool loaded = false;

        /// <summary>
        /// Defines the modifiedOn.
        /// </summary>
        private DateTime? modifiedOn = DateTime.MinValue;

        private ObservableCollection<MovieGenre>? movieGenres;

        /// <summary>
        /// Defines the movieName.
        /// </summary>
        private string? movieName;

        /// <summary>
        /// Defines the moviePath.
        /// </summary>
        private string? moviePath;

        /// <summary>
        /// Defines the path.
        /// </summary>
        private string? path;

        /// <summary>
        /// Defines the plexKey.
        /// </summary>
        private string? plexKey;

        /// <summary>
        /// Defines the primaryFilmGroup.
        /// </summary>
        private string? primaryFilmGroup;

        /// <summary>
        /// Defines the progress.
        /// </summary>
        private int? progress;

        /// <summary>
        /// Defines the season.
        /// </summary>
        private int? season;

        /// <summary>
        /// Defines the seasonEntity.
        /// </summary>
        private Season? seasonEntity;

        private string? seasonNo = null;

        private bool selected;

        /// <summary>
        /// Defines the series.
        /// </summary>
        private int? series;

        private Bookmark? startBookmark;

        /// <summary>
        /// Defines the tMDBID.
        /// </summary>
        private int? tMDBID;

        /// <summary>
        /// Defines the tVEpisodes.
        /// </summary>
        private List<TVEpisode>? tVEpisodes;

        /// <summary>
        /// Defines the wIKIPageID.
        /// </summary>
        private string? wIKIPageID;

        /// <summary>
        /// Defines the year.
        /// </summary>
        private int? year;

        #endregion Private Fields

        #region Public Constructors

        public Movies(string moviePath)
        {
            this.MoviePath = moviePath;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="Movies"/> class.
        /// </summary>
        public Movies()
        {
            //this.Movies1 = new HashSet<Movies>();
            this.Bookmarks = new ObservableCollection<Bookmark>();
            this.Casts = new HashSet<Cast>();



            this.PropertyChanged += Movies_PropertyChanged;

            this.StartBookmark = new Bookmark() { Name = "Start", Time = 0, Type = "Special" };
            this.EndBookmark = new Bookmark() { Name = "End", Time = DurationSeconds, Type = "Special" };
        }

        #endregion Public Constructors

        #region Public Properties

        /// <summary>
        /// Gets or sets the Added.
        /// </summary>
        public System.DateTime? Added
        {
            get => added;
            set
            {
                if (value != null)
                    this.RaiseAndSetIfChanged(ref added, value);
            }
        }

        /// <summary>
        /// Gets or sets the AddedOn.
        /// </summary>
        [NotMapped]
        public string AddedOn
        {
            get
            {
                if (Added != null) { addedOn = Added.Value.ToString("dd-MMM-yyyy"); }
                return addedOn;
            }

            set
            {
                addedOn = value;

                if (DateTime.TryParse(addedOn, out DateTime dt))
                {
                    Added = dt;
                }
            }
        }

        /// <summary>
        /// Gets or sets the Bookmarks.
        /// </summary>
        public ObservableCollection<Bookmark>? Bookmarks
        {
            get => bookmarks;
            set
            {
                this.RaiseAndSetIfChanged(ref bookmarks, value);

            }
        }

        /// <summary>
        /// Gets or sets the Casts.
        /// </summary>
        [NotMapped]
        public ICollection<Cast>? Casts
        {
            get
            {
                if (casts == null || casts.Count == 0)
                {
                    casts = DataController.CastController.GetCastsByMovieId(this.Id).ToList();
                    foreach (var item in casts)
                    {
                        if (item.Actor == null && item.ActorId != null)
                        {
                            item.Actor = DataController.SandboxEntities.Actors.Find(item.ActorId);
                        }
                    }
                }
                return casts;
            }

            set => this.RaiseAndSetIfChanged(ref casts, value);
        }

        /// <summary>
        /// Gets or sets the Director.
        /// </summary>
        [NotMapped]
        public virtual Director? Director 
        {
            get => director; 
            set => this.RaiseAndSetIfChanged(ref director, value); 
        }

        /// <summary>
        /// Gets or sets the DirectorID.
        /// </summary>
        public int? DirectorID 
        { 
            get => directorID; 
            set => this.RaiseAndSetIfChanged(ref directorID, value); 
        }

        [NotMapped]

        public bool Dirty 
        { 
            get => dirty; 
            set => dirty = value; 
        }

        /// <summary>
        /// Gets or sets the DurationSeconds.
        /// </summary>
        public Nullable<int> DurationSeconds
        {
            get
            {
                if (durationSeconds == null || durationSeconds == 0)
                {
                    SetError("Duration:Must be greater than Zero");
                    if (durationSeconds == null) durationSeconds = 0;
                }

                return durationSeconds;
            }

            set
            {
                if (value != null)
                {
                    this.RaiseAndSetIfChanged(ref durationSeconds, value);
                    MovieDuration = SetMovieDuration(value);
                    if (EndBookmark != null) EndBookmark.Time = value;
                    //this.SetPercentUnmarked();
                }
                //else
                //{
                //    SetError("Duration:Must be greater than Zero");
                //}
            }
        }

        [NotMapped]
        public Bookmark? EndBookmark 
        { 
            get => endBookmark; 
            set => this.RaiseAndSetIfChanged(ref endBookmark, value); 
        }

        /// <summary>
        /// Gets or sets the Episode.
        /// </summary>
        public int? Episode
        {
            get => episode; set
            {
                this.RaiseAndSetIfChanged(ref episode, value);

                if (value != null)
                {
                    if (EpisodeEntity == null)
                    {
                        GetEpisodeEntity();
                    }

                    if (EpisodeEntity != null)
                    {
                        EpisodeNumber = EpisodeEntity.EpisodeNumber;
                    }

                }
            }
        }

        /// <summary>
        /// Gets or sets the EpisodeEntity.
        /// </summary>
        [NotMapped]

        public TVEpisode? EpisodeEntity
        {
            get
            {
                if (episodeEntity == null && (Episode != null && Episode > 0))
                {
                    episodeEntity = DataController.MovieController.GetTVEpisodeById(Episode);
                    this.RaisePropertyChanged(nameof(EpisodeEntity));
                    this.RaisePropertyChanged(nameof(EpisodeNumber));
                }

                return episodeEntity;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref episodeEntity, value);

                this.HasEpisodes = (value != null);
                if (value != null)
                {
                    Episode = value.Id;
                    EpisodeNumber = value.EpisodeNumber;
                }
            }
        }

        [NotMapped]
        public int? EpisodeNumber
        {
            get
            {
                if (episodeNumber == null)
                {
                    if (EpisodeEntity != null)
                    { episodeNumber = EpisodeEntity.EpisodeNumber; }
                    else if (Episode != null)
                    {
                        //EpisodeEntity = DataController.SandboxEntities.TVEpisodes.Find(Episode).FirstOrDefault();
                    }

                }
                //this.RaisePropertyChanged(nameof(EpisodeNumber));
                return episodeNumber;
            }

            set => this.RaiseAndSetIfChanged(ref episodeNumber, value);
        }

        /// <summary>
        /// Gets or sets the FilmGroup.
        /// </summary>
        public string? FilmGroup
        {
            get
            {
                if (string.IsNullOrEmpty(filmGroup)) filmGroup = "NONE";
                return filmGroup;
            }

            set => this.RaiseAndSetIfChanged(ref filmGroup, value);
        }

        /// <summary>
        /// Gets or sets the h.
        /// </summary>
        public bool? h { get; set; }

        /// <summary>
        /// Gets or sets the HasChapters.
        /// </summary>
        public bool? HasChapters 
        {
            get => hasChapters;
            set => this.RaiseAndSetIfChanged(ref hasChapters, value); 
        }

        /// <summary>
        /// Gets or sets the HasEpisodes.
        /// </summary>
        public bool? HasEpisodes
        { 
            get => hasEpisodes; 
            set => this.RaiseAndSetIfChanged(ref hasEpisodes, value);
        }

        [NotMapped]
        public bool? HasSeason
        {
            get => hasSeason;
            set => this.RaiseAndSetIfChanged(ref hasSeason, value);
        }

        [NotMapped]
        public bool? HasSeries
        {
            get => hasSeries;
            set => this.RaiseAndSetIfChanged(ref hasSeries, value);
        }

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        public new int Id
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the ImagePath.
        /// </summary>
        public string? ImagePath
        {
            get
            {
                if (!string.IsNullOrEmpty(imagePath) && imagePath.Contains("T:\\", StringComparison.CurrentCultureIgnoreCase))
                {
                    imagePath = imagePath.Replace("T:\\", @"K:\TD1\", StringComparison.CurrentCultureIgnoreCase);
                }
                return imagePath;
            }

            set
            {
                string tempPath = Support.Support.FixPathBack(value);
                this.RaiseAndSetIfChanged(ref imagePath, tempPath);
            }
        }

        /// <summary>
        /// Gets or sets the ImagesCount.
        /// </summary>
        public int? ImagesCount
        {
            get
            {
                if (imagesCount == null || imagesCount == 0)
                {
                    if (Bookmarks != null && Bookmarks.Count > 0)
                    {
                        imagesCount = Bookmarks.Count;
                    }

                }

                return imagesCount;
            }

            set
            {
                if (value != null && value > 0)
                {
                    this.RaiseAndSetIfChanged(ref imagesCount, value);
                    this.SetPercentUnmarked();
                }

            }
        }

        /// <summary>
        /// Gets or sets the IMDBID.
        /// </summary>
        public string? IMDBID 
        {
            get => iMDBID; 
            set => this.RaiseAndSetIfChanged(ref iMDBID, value); 
        }

        /// <summary>
        /// Gets or sets the Info.
        /// </summary>
        public string? Info 
        { 
            get => info; 
            set => this.RaiseAndSetIfChanged(ref info, value); 
        }

        [NotMapped]
        public bool IsSelected 
        { 
            get => selected; 
            set => this.RaiseAndSetIfChanged(ref selected, value); 
        }

        public string? Json 
        { 
            get => json; 
            set => this.RaiseAndSetIfChanged(ref json, value); 
        }

        /// <summary>
        /// Gets or sets the link.
        /// </summary>
        public int? link 
        {
            get => link1; 
            set => this.RaiseAndSetIfChanged(ref link1, value); 
        }

        public bool IsLoaded { get => isLoaded; }

        [NotMapped]
        public bool Loaded
        {
            get => loaded;
            set
            {
                this.RaiseAndSetIfChanged(ref loaded, value);
                if (value)
                {
                    if (!IsLoaded)
                    {
                        LoadChildren();
                        Debug.WriteLine(Id.ToString());
                        isLoaded = true;
                    }
                    // build properties if not already loaded;
                }
            }
        }

        /// <summary>
        /// Gets or sets the ModifiedOn.
        /// </summary>
        public Nullable<System.DateTime> ModifiedOn
        {
            get => modifiedOn;

            set
            {
                if (value != null)
                    this.RaiseAndSetIfChanged(ref modifiedOn, value);
            }
        }

        /// <summary>
        /// Gets or sets the movie genres.
        /// </summary>
        /// <value>
        /// The movie genres.
        /// </value>
        /// <autogeneratedoc />
        public ObservableCollection<MovieGenre>? MovieGenres
        {
            get
            {
                if (movieGenres == null || movieGenres.Count == 0)
                {
                    movieGenres = new System.Collections.ObjectModel.ObservableCollection<MovieGenre>(
                        DataController.SandboxEntities.MovieGenre.ToList().Where(mg => mg.MovieId == Id).OrderBy(o => o.Genre).ToList()
                        );
                    // if (notBuilt && movieGenres.Count == 0) this.BuildGenreList();
                }
                return movieGenres;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref movieGenres, value);
                this.RaisePropertyChanged(nameof(MovieGenres));
            }
        }

        /// <summary>
        /// Gets or sets the MovieName.
        /// </summary>
        public string? MovieName
        {
            get
            {
                if (string.IsNullOrEmpty(movieName))
                {
                    movieName = "Blank";
                }
                return movieName;
            }

            set
            {
                if (!string.IsNullOrEmpty(value))
                    this.RaiseAndSetIfChanged(ref movieName, value);
            }
        }

        /// <summary>
        /// Gets or sets the MoviePath.
        /// </summary>
        public string? MoviePath
        {
            get
            {
                if (!string.IsNullOrEmpty(moviePath) && moviePath.Contains("T:\\", StringComparison.CurrentCultureIgnoreCase))
                {
                    moviePath = moviePath.Replace("T:\\", @"K:\TD1\", StringComparison.CurrentCultureIgnoreCase);
                }
                return moviePath;
            }

            set
            {
                string tempPath = Support.Support.FixPathBack(value);
                this.RaiseAndSetIfChanged(ref moviePath, tempPath);
            }
        }

        /// <summary>
        /// Gets or sets the Path.
        /// </summary>
        public string? Path
        {
            get => path;

            set
            {
                string tempPath = Support.Support.FixPathBack(value);
                this.RaiseAndSetIfChanged(ref path, tempPath);
            }
        }

        /// <summary>
        /// Gets or sets the PlexKey.
        /// </summary>
        public string? PlexKey 
        { 
            get => plexKey; 
            set => this.RaiseAndSetIfChanged(ref plexKey, value);
        }

        /// <summary>
        /// Gets or sets the PrimaryFilmGroup.
        /// </summary>
        public string? PrimaryFilmGroup 
        {
            get => primaryFilmGroup; 
            set => this.RaiseAndSetIfChanged(ref primaryFilmGroup, value); 
        }

        /// <summary>
        /// Gets or sets the Progress.
        /// </summary>
        public int? Progress 
        { 
            get => progress; 
            set => this.RaiseAndSetIfChanged(ref progress, value); 
        }

        /// <summary>
        /// Gets or sets the Season.
        /// </summary>
        public int? Season
        {
            get
            {
                if (season == null) return 0;
                else
                {
                    return season;
                }
            }

            set
            {
                this.RaiseAndSetIfChanged(ref season, value);
                if (value != null && value > 0)
                {
                    SeasonEntity = DataController.SandboxEntities.Seasons.Find(value);
                    if (SeasonEntity != null &&
                        (SeasonEntity.TVEpisodes == null
                        || SeasonEntity.TVEpisodes.Count == 0))
                    {
                        SeasonEntity.TVEpisodes = new ObservableCollection<TVEpisode>(DataController.SandboxEntities.TVEpisodes.Where(t => t.SeasonID == SeasonEntity.Id).ToList());
                        this.RaisePropertyChanged(nameof(SeasonEntity.TVEpisodes));

                    }
                    this.RaisePropertyChanged(nameof(SeasonEntity));
                }
            }
        }

        [NotMapped]
        public string? SeasonNo
        {
            get
            {
                if (seasonNo == null)
                {
                    if (Season != null)
                    {
                        if (SeasonEntity == null) SeasonEntity = DataController.MovieController.GetSeasonById(Season);
                        if (SeasonEntity != null) seasonNo = SeasonEntity.SeasonNo?.ToString();
                        else seasonNo = "-";
                    }
                    return seasonNo;
                }
                else return seasonNo;
            }
            
        }

        /// <summary>
        /// Gets or sets the Series.
        /// </summary>
        public int? Series
        {
            get
            {
                if (series == null) series = 2; // indicates it is not in a series;
                return series;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref series, value);
                if (value != null && value > 0)
                {
                    if (SeriesEntity == null)
                    {
                        SeriesEntity = DataController.MovieController.GetSeriesById(value.Value);
                    }

                    if (SeriesEntity != null && (SeriesEntity.Seasons == null || SeriesEntity.Seasons.Count == 0))
                    {
                        SeriesEntity.Seasons = new ObservableCollection<Season>(DataController.SandboxEntities.Seasons.Where(s => s.Series == SeriesEntity.Id).ToList());
                    }
                    this.RaisePropertyChanged(nameof(SeriesEntity));
                    this.RaisePropertyChanged(nameof(SeriesEntity.Seasons));
                }
            }
        }

        [NotMapped]
        public Bookmark? StartBookmark 
        { 
            get => startBookmark; 
            set => this.RaiseAndSetIfChanged(ref startBookmark, value); 
        }

        
        /// <summary>
        /// Gets or sets the TMDBID.
        /// </summary>
        public int? TMDBID 
        {
            get => tMDBID; 
            set => this.RaiseAndSetIfChanged(ref tMDBID, value); 
        }

        /// <summary>
        /// Gets or sets the WIKIPageID.
        /// </summary>
        public string? WIKIPageID 
        { 
            get => wIKIPageID; 
            set => this.RaiseAndSetIfChanged(ref wIKIPageID, value); 
        }

       
        /// <summary>
        /// Gets or sets the Year.
        /// </summary>
        public int? Year
        {
            get
            {
                if (year == 0) year = null;
                return year;
            }

            set => this.RaiseAndSetIfChanged(ref year, value);
        }

        #endregion Public Properties

        #region Public Methods

        //public void Dispose()
        //{
        //    // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
        //    Dispose(disposing: true);
        //    GC.SuppressFinalize(this);
        //}

        // add a ToString override to return the MovieName and Year
        public override string ToString()
        {
            return $"{MovieName} ({Year}) Runtime {MovieDuration.ToString()}";
        }

        #endregion Public Methods

        #region Protected Methods

        protected new virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    imageBMP?.Dispose();
                    // TODO: dispose managed state (managed objects)
                }
                
                disposedValue = true;
            }
        }

        #endregion Protected Methods

        #region Private Methods

        private void GetEpisodeEntity()
        {
            EpisodeEntity = DataController.MovieController.GetTVEpisodeById(Episode);
            this.RaisePropertyChanged("EpisodeEntity");
        }

        private void Movies_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            string name = e.PropertyName;

            if (!(name == "link" || name == "ModifiedOn" || name == "ErrorText" || name == "BackColour" || name == "PercentUnBookmarked"
                || name == "Bookmarks" || name == "EpisodeEntity" || name == "SeasonEntity" || name == "SeriesEntity" || name == "Casts" || name == "Added" || name == "MovieDuration"))
            {
                Dirty = true;
                if (!string.IsNullOrEmpty(ChangedFields)) ChangedFields += ",";
                ChangedFields += name;
            }
        }

        #endregion Private Methods
       
    }
}
