using AvalonMVVM.Support;
using DocumentFormat.OpenXml.Presentation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;
using System.Xml;
using Newtonsoft.Json;
using ReactiveUI;
using System.Runtime.Serialization;

namespace AvalonMVVM.Models
{
    /// <summary>
    /// A class that gives adaptable extensions to a Movie Object
    /// </summary>
    /// <autogeneratedoc />
    [DataContract]
    public class MovieExtn :ReactiveObject
    {
        private int rating;
        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="MovieExtn"/> class.
        /// </summary>
        /// <autogeneratedoc />
        public MovieExtn()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MovieExtn"/> class.
        /// </summary>
        /// <param name="json">The json.</param>
        /// <autogeneratedoc />
        public MovieExtn(string json)
        {
            if (!string.IsNullOrEmpty(json))
            {
                Deserialize(json);
            }
        }

        #endregion Public Constructors

        #region Public Properties

        [JsonIgnore]
        internal Movies Parent { get; set; }

        /// <summary>
        /// Gets or sets the rating.
        /// </summary>
        /// <value>
        /// The rating.
        /// </value>
        /// <autogeneratedoc />
        [DataMember]
        public int Rating
        {
            get => rating; set
            {
                this.RaiseAndSetIfChanged(ref rating, value);
               // rating =  value;
                if (Parent != null) { Parent.Dirty = true; }
            }
        }

        #endregion Public Properties

        #region Public Methods

        /// <summary>
        /// The Deserialize
        /// </summary>
        /// <param name="xml">The <see cref="string"/></param>
        public void Deserialize(string xml)
        {
            if (!string.IsNullOrEmpty(xml))
            {
                MovieExtn? temp = JsonConvert.DeserializeObject<MovieExtn>(xml);
                if (temp != null)
                    this.Rating = temp.Rating;
            }
        }

        /// <summary>
        /// The Serialise
        /// </summary>
        /// <returns>The <see cref="string"/></returns>
        public string Serialise()
        {
            string retValue = "";

            retValue = JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);

            return retValue;
        }

        #endregion Public Methods
    }
}