using TaymadeEntities.Support;
using Microsoft.EntityFrameworkCore;
using ReactiveUI;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TaymadeEntities.Models
{
    public class MovieGenre : ModelBase
    {
        #region Private Fields

        private PhraseEntry? mainGenreEntity;
        private Movies? movies;
        private PhraseEntry? subGenreEntity;

        #endregion Private Fields

        #region Public Properties

        /// <summary>
        /// Gets or sets the genre.
        /// </summary>
        /// <value>
        /// The genre.
        /// </value>
        /// <autogeneratedoc />
        public string? Genre { get; set; }

        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>
        /// The identifier.
        /// </value>
        /// <autogeneratedoc />
        //public int Id { get; set; }

        [NotMapped]
        public PhraseEntry? MainGenreEntity
        {
            get
            {
                if (mainGenreEntity == null && !string.IsNullOrEmpty(Genre))
                {
                    try
                    {
                        mainGenreEntity = DataController.PhrasesController.GetByCompKey(1,Genre);
                        //mainGenreEntity = DataController.SandboxEntities.PhraseEntry.Where(p => p.PhraseID == 1 && p.COMPKEY == Genre).FirstOrDefault();
                    }
                    catch (Exception)
                    {

                    }
                }

                return mainGenreEntity;
            }
            set => mainGenreEntity = value;
        }

        /// <summary>
        /// Gets or sets the movie identifier.
        /// </summary>
        /// <value>
        /// The movie identifier.
        /// </value>
        /// <autogeneratedoc />
        [ForeignKey(nameof(MovieId))]
        public int MovieId { get; set; }

        /// <summary>
        /// Gets or sets the Movies.
        /// </summary>
        [NotMapped]
        public Movies? Movies { get => movies; set => this.RaiseAndSetIfChanged(ref movies, value); }

        /// <summary>
        /// Gets or sets the sub genre.
        /// </summary>
        /// <value>
        /// The sub genre.
        /// </value>
        /// <autogeneratedoc />
        public string? SubGenre { get; set; }
        [NotMapped]
        public PhraseEntry? SubGenreEntity
        {
            get
            {
                if (subGenreEntity == null && !string.IsNullOrEmpty(SubGenre))
                {
                    try
                    {
                        subGenreEntity = DataController.PhrasesController.GetByCompKey(9,SubGenre);
                        //subGenreEntity = DataController.SandboxEntities.PhraseEntry.Where(p => p.PhraseID == 9 && p.COMPKEY == SubGenre).FirstOrDefault();
                    }
                    catch (Exception)
                    {
                    }
                }
                return subGenreEntity;
            }

            set => subGenreEntity = value;
        }

        [NotMapped]
        public string Description { get { return this.ToString(); } }

        #endregion Public Properties

        #region Public Methods

        /// <summary>
        /// Converts to string.
        /// </summary>
        /// <returns>
        /// A <see cref="System.String" /> that represents this instance.
        /// </returns>
        /// <autogeneratedoc />
        public override string ToString()
        {
            if (SubGenreEntity != null)
            {
                return SubGenreEntity.ToString();
            }

            else if (MainGenreEntity != null)
            {
                return MainGenreEntity.ToString();
            }
            else return Genre;
        }

        #endregion Public Methods

        #region Internal Methods

        /// <summary>
        ///  Delete Entity from database
        /// </summary>
        public void Delete()
        {
            this.Movies = null;
            //var local = DataController.SandboxEntities.Set<MovieGenre>().Local.FirstOrDefault(entry => entry.Id.Equals(Id));

            //// check if local is not null
            //DataController.SandboxEntities.MovieGenre.Attach(this);
            //DataController.SandboxEntities.MovieGenre.Remove(this);
            //DataController.SandboxEntities.SaveChanges();
            DataController.MovieGenreController.Delete(this.Id);
        }

        /// <summary>
        /// Add a new Cast entity into database 
        /// </summary>
        public void Insert()
        {

            try
            {
                if (this.Id < 10 && this.MovieId > 0)
                {
                    MovieGenre? temp = DataController.MovieGenreController.CreateMovieGenre(this.MovieId, this.Genre, this.SubGenre);
                    this.Id = temp.Id;
                }
            }
            catch (Exception ex)
            {
                string error = ex.Message;
                //throw;
            }
        }

        /// <summary>
        /// The Save.
        /// </summary>
        public void Save()
        {
            try
            {
                bool succes = DataController.MovieGenreController.Update(this);

                //var local = DataController.SandboxEntities.Set<MovieGenre>().Local.FirstOrDefault(entry => entry.Id.Equals(Id));

                //// check if local is not null 
                //if (local != null)
                //{
                //    // detach
                //    DataController.SandboxEntities.Entry(local).State = EntityState.Detached;
                //}
                //// set Modified flag in your entry
                //DataController.SandboxEntities.Entry(this).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                //DataController.SandboxEntities.SaveChanges();


            }
            catch (Exception)
            {
                // throw;
            }

        }

        public async Task<bool> SaveAsync()
        {
            bool success = false;
            try
            {
                // add a repository method
                var local = DataController.SandboxEntities.Set<MovieGenre>().Local.FirstOrDefault(entry => entry.Id.Equals(Id));

                // check if local is not null 
                if (local != null)
                {
                    // detach
                    DataController.SandboxEntities.Entry(local).State = EntityState.Detached;
                }
                // set Modified flag in your entry
                DataController.SandboxEntities.Entry(this).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                int result = await DataController.SandboxEntities.SaveChangesAsync();
                success = (result == 1);

            }
            catch (Exception)
            {
                // throw;
            }

            return success;

        }

        #endregion Internal Methods
    }
}


