//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaymadeEntities.Models
{
    using Microsoft.EntityFrameworkCore;
    using Support;
    using System;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using ReactiveUI;
    using TaymadeEntities.DBContext;

#nullable enable
    //using Microsoft.CodeAnalysis.CSharp.Syntax;

    /// <summary>
    /// Defines the <see cref="PhraseEntry" />.
    /// </summary>
    public partial class PhraseEntry : ReactiveObject
    {
        #region Fields

        /// <summary>
        /// Defines the link.
        /// </summary>
        private string? link;

        /// <summary>
        /// Defines the phraseInfo.
        /// </summary>
        private PhraseInfo? phraseInfo;
        private string? description;
        private PhraseHeader? phraseHeader;

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the COMPKEY.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public string? COMPKEY { get; set; }

        /// <summary>
        /// Gets or sets the DataType.
        /// </summary>
        public string? DataType { get; set; }

        /// <summary>
        /// Gets or sets the Description.
        /// </summary>
        public string? Description { get => description; set => this.RaiseAndSetIfChanged(ref description, value); }

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        public new string Id { get; set; }

        /// <summary>
        /// Gets or sets the Link.
        /// </summary>
        public string? Link { get => link; set => this.RaiseAndSetIfChanged(ref link, value); }

        /// <summary>
        /// Gets or sets the Order.
        /// </summary>
        public int? Order { get; set; }

        /// <summary>
        /// Gets or sets the PhraseID.
        /// </summary>
        public int PhraseID { get; set; }

        [NotMapped]
        public virtual PhraseHeader? PhraseHeader { get => phraseHeader; set => phraseHeader = value; }

        /// <summary>
        /// Gets or sets the PhraseInfo.
        /// </summary>
        [NotMapped]
        public PhraseInfo? PhraseInfo
        {
            get
            {
                if (phraseInfo == null)
                {
                    phraseInfo = new PhraseInfo(XML);

                }
                return phraseInfo;
            }
            set => phraseInfo = value;
        }

        /// <summary>
        /// Gets or sets the Searchable.
        /// </summary>
        public bool? Searchable { get; set; }

        /// <summary>
        /// Gets or sets the Sortable.
        /// </summary>
        public bool? Sortable { get; set; }

        /// <summary>
        /// Gets or sets the XML.
        /// </summary>
        public string? XML { get; set; }

        #endregion

        #region Methods

        /// <summary>
        /// The CreatePhrase.
        /// </summary>
        /// <returns>The <see cref="PhraseEntry"/>.</returns>
        public static PhraseEntry CreatePhrase()
        {
            PhraseEntry phrase = new PhraseEntry()
            {
                Description = "<New>",
                Id = "??",
                PhraseID = 1
            };
            if (phrase != null)
            {
                
            }

            return phrase;
        }

        /// <summary>
        /// The CreateSubPhrase.
        /// </summary>
        /// <param name="phraseId">The phraseId<see cref="string"/>.</param>
        /// <returns>The <see cref="PhraseEntry"/>.</returns>
        public static PhraseEntry CreateSubPhrase(string phraseId)
        {
            PhraseEntry phrase = new PhraseEntry()
            {
                Description = "<New>",
                Id = phraseId + "??",
                PhraseID = 9
            };

            return phrase;
        }

        /// <summary>
        /// The ToString.
        /// </summary>
        /// <returns>The <see cref="string"/>.</returns>
        public override string ToString()
        {
            //return base.ToString();
            {
                return Description;
            }
        }

        internal void Delete()
        {
            //DataController.SandboxEntities.PhraseEntry.Remove(this);
            //DataController.SandboxEntities.SaveChanges();

            // using stored procedures to ensure dependent entries in MovieGenre table are also deleted and subphrases in PhraseEntry. 
            DataController.SandboxEntities.DeletePhraseEntry(this.Id);

        }

        /// <summary>
        /// The Save.
        /// </summary>
        public void Save()
        {
            if (PhraseInfo != null)
            {
                XML = PhraseInfo.Serialise();
            }

            if (!string.IsNullOrEmpty(this.COMPKEY))
            {
                try
                {
                    var local = DataController.SandboxEntities.Set<PhraseEntry>().Local.FirstOrDefault(entry => entry.Id.Equals(Id));

                    // check if local is not null
                    if (local != null)
                    {
                        // detach
                        DataController.SandboxEntities.Entry(local).State = EntityState.Detached;
                    }
                    // set Modified flag in your entry
                    // ModifiedOn = DateTime.Now;
                    DataController.SandboxEntities.Entry(this).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                    DataController.SandboxEntities.SaveChanges();
                }
                catch (Exception)
                {

                }
            }
            else
            {
                if ( this.PhraseID == 1 && DataController.SandboxEntities.Entry(this).State == EntityState.Detached)
                {
                    DataController.SandboxEntities.PhraseEntry.Add(this);
                    DataController.SandboxEntities.SaveChanges();
                    DataController.SandboxEntities.Entry(this).ReloadEntity();
                }
                else
                {
                    DataController.SandboxEntities.PhraseEntry.Add(this);

                    DataController.SandboxEntities.SaveChanges();
                }
            }
        }

        #endregion
    }
}
