//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaymadeEntities.Models
{
    using TaymadeEntities.Support;
   // using CSharpFunctionalExtensions;
    using DocumentFormat.OpenXml.Office2010.Excel;
    using Microsoft.Data.SqlClient;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.ChangeTracking;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Defines the <see cref="SandboxStatic" />.
    /// </summary>
    public static class SandboxStatic
    {
        #region Methods

        /// <summary>
        /// The Reload.
        /// </summary>
        /// <param name="source">The source<see cref="CollectionEntry"/>.</param>
        public static void Reload(this CollectionEntry source)
        {
            if (source.CurrentValue != null)
            {
                foreach (var item in source.CurrentValue)
                    source.EntityEntry.Context.Entry(item).State = EntityState.Detached;
                source.CurrentValue = null;
            }
            source.IsLoaded = false;
            source.Load();
        }

        /// <summary>
        /// The ReloadEntity.
        /// </summary>
        /// <param name="source">The source<see cref="EntityEntry"/>.</param>
        public static void ReloadEntity(this EntityEntry source)
        {
            source.Reload();
        }



        #endregion
    }

    /// <summary>
    /// Defines the <see cref="sandboxEntities" />.
    /// </summary>
    public partial class sandboxEntities : DbContext
    {
        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="sandboxEntities"/> class.
        /// </summary>
        public sandboxEntities()
        {

            Database.SetCommandTimeout((int)TimeSpan.FromMinutes(5).TotalSeconds);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="sandboxEntities"/> class.
        /// </summary>
        /// <param name="options">The options<see cref="DbContextOptions"/>.</param>
        public sandboxEntities(DbContextOptions options) : base(options)
        {
        }

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the Actors.
        /// </summary>
        public virtual DbSet<Actor> Actors { get; set; }

        [NotMapped]
        public virtual DbSet<MovieIntResult> MovieIntResult { get; set; }

        public virtual DbSet<Album> Album { get; set; }

        public virtual DbSet<ArtistVideo> ArtistVideo { get; set; }
        /// <summary>
        /// Gets or sets the Author.
        /// </summary>
        public virtual DbSet<Author> Author { get; set; }

        public virtual DbSet<Bookmark> Bookmarks { get; set; }
        /// <summary>
        /// Gets or sets the Casts.
        /// </summary>
        public virtual DbSet<Cast> Casts { get; set; }

        public virtual DbSet<DownloadProperties> DownloadProperties { get; set; }

        /// <summary>
        /// Gets or sets the Directors.
        /// </summary>
        public virtual DbSet<Director> Directors { get; set; }

        /// <summary>Gets or sets the filter.</summary>
        /// <value>The filter.</value>
        public virtual DbSet<Filter> Filter { get; set; }

        /// <summary>
        /// Gets or sets the MapDrive.
        /// </summary>
        public virtual DbSet<MapDrive> MapDrive { get; set; }

        // public virtual DbSet<MovieImage> MovieImage { get; set; }
        /// <summary>
        /// Gets or sets the MappedDrives.
        /// </summary>
        public virtual DbSet<MappedDrives> MappedDrives { get; set; }

        public virtual DbSet<MovieAppProperties> MovieAppProperties { get; set; }
        // public virtual DbSet<MissingGenresMovies> MissingGenresMovies { get; set; }
        /// <summary>
        /// Gets or sets the movie genre.
        /// </summary>
        /// <value>
        /// The movie genre.
        /// </value>
        /// <autogeneratedoc />
        public virtual DbSet<MovieGenre> MovieGenre { get; set; }

        public virtual DbSet<MovieLanguage> MovieLanguage { get; set; }
        /// <summary>
        /// Gets or sets the MovieProperties.
        /// </summary>
        public virtual DbSet<MovieProperties> MovieProperties { get; set; }

        /// <summary>
        /// Gets or sets the Movies.
        /// </summary>
        public DbSet<Movies> Movies { get; set; }

        public virtual DbSet<MVMLogs> MVMLogs { get; set; }
        /// <summary>
        /// Gets or sets the PhraseEntry.
        /// </summary>
        public DbSet<PhraseEntry> PhraseEntry { get; set; }

        public DbSet<PhraseHeader> PhraseHeader { get; set; }

        public virtual DbSet<ProductionCompany> ProductionCompany { get; set; }
        public DbSet<ProductionCompanyMovie> ProductionCompanyMovie { get; set; }
        /// <summary>
        /// Gets or sets the Seasons.
        /// </summary>
        public virtual DbSet<Season> Seasons { get; set; }

        /// <summary>
        /// Gets or sets the Series.
        /// </summary>
        public virtual DbSet<Series> Series { get; set; }

        /// <summary>
        /// Gets or sets the Story.
        /// </summary>
        public DbSet<Story> Story { get; set; }



        public DbSet<StoryAuthor> StoryAuthor { get; set; }
        public virtual DbSet<StoryDictionary> StoryDictionary { get; set; }
        
        public virtual DbSet<StoryHeadings> StoryHeadings { get; set; }

        /// <summary>
        /// Gets or sets the StoryProperties.
        /// </summary>
        public virtual DbSet<StoryProperties> StoryProperties { get; set; }

        public virtual DbSet<StoryCast> StoryCast { get; set; }

        /// <summary>
        /// Gets or sets the StorySeries.
        /// </summary>
        public DbSet<StorySeries> StorySeries { get; set; }

        public virtual DbSet<StoryTransInfo> StoryTransInfo { get; set; }
        /// <summary>
        /// Gets or sets the TVEpisodes.
        /// </summary>
        public virtual DbSet<TVEpisode> TVEpisodes { get; set; }

        public virtual DbSet<UnboundGridData> UnboundGridData { get; set; }

        /// <summary>
        /// Gets or sets the WordHeadings.
        /// </summary>
        public DbSet<WordHeadings> WordHeadings { get; set; }

        #endregion

        #region Methods

        /// <summary>
        /// The DetachLocal.
        /// </summary>
        /// <typeparam name="T">.</typeparam>
        /// <param name="t">The t<see cref="T"/>.</param>
        /// <param name="Id">The Id<see cref="int?"/>.</param>
        public static void DetachLocal<T>(T t, int? Id) where T : ModelBase
        {
            var local = DataController.SandboxEntities.Set<T>().Local.FirstOrDefault(entry => entry.Id.Equals(Id));

            // check if local is not null 
            if (local != null)
            {
                // detach
                DataController.SandboxEntities.Entry(local).State = EntityState.Detached;
            }
        }

        public async Task ReloadIfModified<TEntity>(TEntity entityObject) where TEntity : class
        {
            var entry = Entry(entityObject);
            //if (entry.State != EntityState.Modified) return;
            await entry.ReloadAsync();
        }

        public StoryCast? CreateStoryCast(int StoryId, int CastId, string Codes, string Character, string Age)
        {
            var storyId = new SqlParameter("@StoryId", StoryId);
            var characterId = new SqlParameter("@Character", Character);
            var castId = new SqlParameter("@CastId", CastId);
            var age = new SqlParameter("@Age", Age);
            var codes = new SqlParameter("@Codes", Codes);
            int count = this.Database.ExecuteSqlRaw(" exec InsertStoryCast @StoryId, @Character, @Age, @Codes,@CastId"
                , storyId, characterId, age, codes, castId);

            if (count == 1)
            {
                var result = this.StoryCast.FromSql($"select * from StoryCast where pk = (select max(pk) from StoryCast)").FirstOrDefault();
                this.StoryCast.Attach(result);
                return result;
            }
            else return null;
        }

        /// <summary>
        /// The CreateBookmark.
        /// </summary>
        /// <param name="MovieId">The MovieId<see cref="int"/>.</param>
        /// <param name="time">The time<see cref="double"/>.</param>
        /// <param name="name">The name<see cref="string"/>.</param>
        /// <returns>The <see cref="Bookmark?"/>.</returns>
        public Bookmark? CreateBookmark(int MovieId, double time, string name = "<new>")
        {
            var id = new SqlParameter("@MovieId", MovieId);
            var ftime = new SqlParameter("@Time", time);

            int count = this.Database.ExecuteSqlRaw("exec InsertBookmark @MovieId, @Time", id, ftime);

            if (count == 1)
            {
                var result = this.Bookmarks.FromSql($"select * from bookmarks where id = (select max(id) from bookmarks)").FirstOrDefault();

                result.Name = name;
                this.Bookmarks.Attach(result);
                return result;
            }
            else
                return null;
        }

        /// <summary>
        /// The CreateMovie.
        /// </summary>
        /// <param name="name">The name<see cref="string"/>.</param>
        /// <param name="year">The year<see cref="int"/>.</param>
        /// <param name="path">The path<see cref="string"/>.</param>
        /// <param name="group">The group<see cref="string"/>.</param>
        /// <returns>The <see cref="Movies?"/>.</returns>
        public Movies? CreateMovie(string name, int year = 0, string path = "", string group = "PORN")
        {
            Movies result = null;

            var _name = new SqlParameter("@MovieName", name);
            var _year = new SqlParameter("@Year", year);
            var _path = new SqlParameter("@Path", path);
            var _group = new SqlParameter("@FilmGroup", group);

            int count = this.Database.ExecuteSqlRaw("exec CreateMinimalMovie @MovieName, @Year, @Path, @FilmGroup ", _name, _year, _path, _group);

            if (count == 1)
            {
                result = this.Movies.FromSql($"select * from Movies where id = (select max(id) from Movies)").AsNoTracking().FirstOrDefault();
                this.Movies.Attach(result);
            }
            return result;
        }

        public MovieGenre CreateMovieGenre(int movieId, string genre, string subGenre)
       {
            MovieGenre result = null;
            var _movieId = new SqlParameter("@MovieId", movieId);
            var _genre = new SqlParameter("@Genre", genre);
            //var _subGenre = new SqlParameter("@SubGenre", subGenre);
            int count = this.Database.ExecuteSqlRaw("exec CreateMovieGenre @MovieId, @Genre",
                _movieId, _genre);
            if (count == 1)
            {
                result = this.MovieGenre.FromSql($"select * from MovieGenre where id = (select max(id) from MovieGenre)").AsNoTracking().FirstOrDefault();
                if (result != null)
                {
                    result.SubGenre = subGenre;
                    result.Save();
                }
                this.MovieGenre.Attach(result);
            }
            return result;
        }

        /// <summary>
        /// The CreateSeries.
        /// </summary>
        /// <param name="SeriesName">The SeriesName<see cref="string"/>.</param>
        /// <returns>The <see cref="Series?"/>.</returns>
        public Series? CreateSeries(string SeriesName)
        {
            var id = new SqlParameter("@Name", SeriesName);

            int count = this.Database.ExecuteSqlRaw("exec CreateSeries");

            if (count == 1)
            {

                var result = this.Series.FromSql($"select * from series where id = (select max(id) from series)").FirstOrDefault();
                result.Name = SeriesName;
                this.Series.Attach(result);
                return result;
            }
            else
                return null;
        }

        public UnboundGridData? CreateUnbound(string fileName, long fileLength = 0,
            int durationSeconds = 0, string group = "", string name = "")
        {
            UnboundGridData? result = this.UnboundGridData.Where(u => u.FileName == fileName).FirstOrDefault();

            // should check for the presence of fileName before insert

            if (result == null)
            {

                var _fileName = new SqlParameter("@FileName", fileName);

                //result = this.UnboundGridData.FromSql($"select * from UnboundGridData where fileName = (select FileName from UnboundGridData where filename = @FileName)").AsNoTracking().FirstOrDefault();

                var _year = new SqlParameter("@FileLength", fileLength);
                var _path = new SqlParameter("@DurationSeconds", durationSeconds);
                var _group = new SqlParameter("@CreationTime", group);
                var _name = new SqlParameter("@Name", name);

                int count = this.Database.ExecuteSqlRaw("exec CreateUnboundGrid @FileName, @FileLength, @DurationSeconds, @CreationTime, @Name "
                    , _fileName, _year, _path, _group, _name);

                if (count == 1)
                {
                    result = this.UnboundGridData.FromSql($"select * from UnboundGridData where id = (select max(id) from UnboundGridData)").AsNoTracking().FirstOrDefault();
                    this.UnboundGridData.Attach(result);
                }
            }
            return result;
        }

        /// <summary>
        /// The DeleteMovie.
        /// </summary>
        /// <param name="Id">The Id<see cref="int"/>.</param>
        public void DeleteMovie(int Id)
        {
            if (Id != null)
            {
                var id = new SqlParameter("@MovieId", Id);
                this.Database.ExecuteSqlRaw(" exec DeleteMovie @MovieId", id);
            }
        }

        /// <summary>
        /// Deletes the phrase entry.
        /// </summary>
        /// <param name="CompKey">The comp key.</param>
        /// <autogeneratedoc />
        public void DeletePhraseEntry(string CompKey)
        {
            if (!string.IsNullOrEmpty(CompKey))
            {
                var compKey = new SqlParameter("@PhraseCompKey", CompKey);
                this.Database.ExecuteSqlRaw(" exec DeletePhraseEntry @PhraseCompKey", compKey);
            }
        }

        public void DeleteUnbound(int Id)
        {
            var id = new SqlParameter("@MovieId", Id);
            this.Database.ExecuteSqlRaw(" exec DeleteUnbound @MovieId", id);
        }

        public List<Movies>? GetMissingMovies()
        {
            List<Movies>? returnValue = this.Movies.FromSql($"Select * from VWUnGeredMovies").ToList();

            return returnValue;
        }

        /// <summary>
        /// The GetMovie.
        /// </summary>
        /// <param name="Id">The Id<see cref="int"/>.</param>
        /// <returns>The <see cref="Movies?"/>.</returns>
        public Movies? GetMovie(int Id)
        {
            var id = new SqlParameter("Id", Id);

            var result = this.Movies.FromSql($"select * from Movies where id = {id} ").FirstOrDefault();

            // var mySeason = this.Movies.FromSql($"select season from Movies where id = {id} ").FirstOrDefault();

            if (result != null)
            {
                // load sub entities 
                if (result.Series != null)
                {
                    var seriesId = new SqlParameter("Id", result.Series);
                    result.SeriesEntity = this.Series.FromSql($" select * from Series where id = {seriesId}").FirstOrDefault();
                }

                if (result.Season != null)
                {
                    var seriesId = new SqlParameter("Id", result.Season);
                    result.SeasonEntity = this.Seasons.FromSql($" select * from Season where id = {seriesId}").FirstOrDefault();
                }

                if (result.Episode != null)
                {
                    var seriesId = new SqlParameter("Id", result.Episode);
                    result.EpisodeEntity = this.TVEpisodes.FromSql($" select * from TvEpisode where id = {seriesId}").FirstOrDefault();
                }

                if (result.DirectorID != null)
                {
                    var seriesId = new SqlParameter("Id", result.DirectorID);
                    result.Director = this.Directors.FromSql($" select * from Director where id = {seriesId}").FirstOrDefault();
                }
            }

            return result;
        }

        public List<ProductionCompany> GetMovieProductionCompanies(int movieId)
        {
            //var id = new SqlParameter("MovieId", movieId);

            string id = movieId.ToString();

            var result = this.ProductionCompany.ToList();

            return result;
        }

        /// <summary>
        /// The GetMoviesbyBookmarkName.
        /// </summary>
        /// <param name="stub">The stub<see cref="string"/>.</param>
        /// <returns>The <see cref="List{Movies}"/>.</returns>
        public List<Movies> GetMoviesbyBookmarkName(string stub)
        {
            stub = '%' + stub.Trim() + '%';

            var retValue = this.Movies.FromSql($"GettMoviesByBookmark {stub}")
                      .ToList();

            return retValue;
        }

        public List<Movies> GetMoviesbyTitle(string stub)
        {
            if (!stub.Contains("%")) // if wild card not present then add wild cards
                stub = '%' + stub.Trim() + '%';

            var retValue = this.Movies.FromSql($"GetMoviesByTitle {stub}")
                      .ToList();

            return retValue;
        }

        /// <summary>
        /// MovieIntResult is a pseudo class to handle the return of a list of integers
        /// </summary>
        /// <param name="stub">The stub.</param>
        /// <returns></returns>
        /// <author>
        /// Doug Taylor - Taymade Software Services
        /// </author>
        /// <remarks>
        ///   <created> 18/02/2026 18/02/2026 </created>
        /// </remarks>
        public List<MovieIntResult> GetActorMovieIds(string stub)
        {
            if (!stub.Contains("%")) // if wild card not present then add wild cards
                stub = '%' + stub.Trim() + '%';

            var retValue = this.MovieIntResult.FromSql($"GetActorMovieIds {stub}").ToList();
                      

            return retValue;
        }


        public List<Movies>? GetMoviesByGenre(string genre, string subGenre = "")
        {
            //var genreType = genre;
            List<Movies>? returnValue = null;

            if (!string.IsNullOrEmpty(subGenre))
            {
                returnValue = this.Movies.FromSql($"Execute dbo.GetMoviesBySubGenre {subGenre}").ToList();
            }
            else
                returnValue = this.Movies.FromSql($"Execute dbo.GetMoviesByGenre {genre}").ToList();

            return returnValue;
        }

        /// <summary>
        /// Gets the moviesby information.
        /// </summary>
        /// <param name="stub">The stub.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        public List<Movies> GetMoviesbyInfo(string stub)
        {
            stub = '%' + stub.Trim() + '%';

            var retValue = this.Movies.FromSql($"GettMoviesByInfo {stub}")
                      .ToList();

            return retValue;
        }

        public StoryAuthor? GetStoryAuthor(int storyId, int authorId)
        {
            return this.StoryAuthor.Where(sa => sa.StoryId == storyId && sa.AuthorId == authorId).FirstOrDefault();
        }

        /// <summary>
        /// Inserts the story author.
        /// </summary>
        /// <param name="storyId">The story identifier.</param>
        /// <param name="authorId">The author identifier.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        public StoryAuthor? InsertStoryAuthor(int storyId, int authorId)
        {
            StoryAuthor? result = null;
            var _storyId = new SqlParameter("@StoryId", storyId);
            var _authorId = new SqlParameter("@AuthorId", authorId);
            int count = this.Database.ExecuteSqlRaw("exec InsertStoryAuthor @StoryId, @AuthorId", _storyId, _authorId);
            if (count == 1)
            {
                result = this.StoryAuthor.FromSql($"select * from StoryAuthor where id = (select max(id) from StoryAuthor)").AsNoTracking().FirstOrDefault();
                this.StoryAuthor.Attach(result);
            }
            return result;
        }
        public void MergeActors(int fromId, int toId)
        {
            var destId = new SqlParameter("@MergeDestination", toId);
            var sourceId = new SqlParameter("@MergeSource", fromId);
            this.Database.ExecuteSqlRaw(" exec MergeActor @MergeSource, @MergeDestination", sourceId, destId);

        }

        public bool UpdateStoryCast(StoryCast storyCast)
        {

            bool success = true;
            if (storyCast == null) return false;

            string codes = storyCast.Codes;
            if (storyCast.Codes != null && storyCast.Codes.Length > 1500) codes = codes.Substring(0, 1499);
            var _Pk = new SqlParameter("@Original_Pk", storyCast.Pk);
            var _Character = new SqlParameter("@Character", storyCast.Character);
            var _Age = new SqlParameter("@Age", storyCast.Age);
            var _Codes = new SqlParameter("@Codes", codes);
            var _CastId = new SqlParameter("@CastId", storyCast.CastId);
            int count = this.Database.ExecuteSqlRaw("exec UpdateStoryCodes @Character,@Age,@Codes,@CastId,@Original_Pk", _Character, _Age, _Codes, _CastId, _Pk);
            success = (count == 1);

            return success;
        }

        public bool UpdataStoryTransInfo(StoryTransInfo storyTransInfo)
        {
            bool success = true;
            if (storyTransInfo == null) return false;
            var _Id = new SqlParameter("@Id", storyTransInfo.Id);
            var _CurrentStoryId = new SqlParameter("@CurrentStoryId", storyTransInfo.CurrentStoryId);
            int count = this.Database.ExecuteSqlRaw("exec SaveCurrentStoryID  @CurrentStoryId", _CurrentStoryId);
            success = (count == 1);
            return success;
        }

        public bool UpdateMovie(Movies movie)
        {
            bool success = true;

            if (movie.MoviePath == null) movie.MoviePath = string.Empty;
            if (movie.MovieName == null) movie.MovieName = string.Empty;
            if (movie.ImagePath == null) movie.ImagePath = string.Empty;
            if (movie.DurationSeconds == null) movie.DurationSeconds = 0;

            var _Id = new SqlParameter("@Id", movie.Id);
            var _path = new SqlParameter("@MoviePath", movie.MoviePath);
            var _imagePath = new SqlParameter("@ImagePath", movie.ImagePath);
            var _novieName = new SqlParameter("@MovieName", movie.MovieName);
            var _duration = new SqlParameter("@Duration", movie.DurationSeconds);

            int count = this.Database.ExecuteSqlRaw("exec MovieUpdate @Id, @MoviePath, @ImagePath, @MovieName, @Duration ",
                _Id, _path, _imagePath, _novieName, _duration);

            success = (count == 1);
            return success;
        }
        /// <summary>
        /// Deletes the story.
        /// </summary>
        /// <param name="iD">The i d.</param>
        /// <autogeneratedoc />
        internal void DeleteStory(int iD)
        {
            var id = new SqlParameter("@Original_Id", iD);
            int rows = this.Database.ExecuteSqlRaw(" exec DeleteStory @Original_Id", id);
            if (rows == 1)
            {
                this.Story.Remove(this.Story.Where(s => s.Id == iD).FirstOrDefault());  
            }
        }

        /// <summary>
        /// Deletes the story dictionary.
        /// </summary>
        /// <param name="iD">The i d.</param>
        /// <autogeneratedoc />
        public bool DeleteStoryDictionary(int iD)
        {
            var id = new SqlParameter("@StoryId", iD);
            int result = this.Database.ExecuteSqlRaw(" exec DeleteStoryDictionary @StoryId", id);
            return (result == 1);
        }

        /// <summary>
        /// Deletes the word heading.
        /// </summary>
        /// <param name="iD">The i d.</param>
        /// <autogeneratedoc />
        internal void DeleteWordHeading(int iD)
        {
            var id = new SqlParameter("@HeadId", iD);
            this.Database.ExecuteSqlRaw(" exec DeleteWordHeading @HeadId", id);
        }

        /// <summary>
        /// The OnConfiguring.
        /// </summary>
        /// <param name="optionsBuilder">The optionsBuilder<see cref="DbContextOptionsBuilder"/>.</param>
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Data Source=TAYMADE-8\\sqlexpress;Initial Catalog=sandbox;Persist Security Info=True;User Id=sandbox;Password=sandbox;Encrypt=false");
            optionsBuilder.EnableSensitiveDataLogging();
        }

        /// <summary>
        /// The OnModelCreating.
        /// </summary>
        /// <param name="modelBuilder">The modelBuilder<see cref="ModelBuilder" />.</param>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Movies>().HasKey(m => m.Id);
            modelBuilder.Entity<Movies>().HasOne(s => s.SeriesEntity).WithMany(m => m.Movies).HasForeignKey(ms => ms.Series);
            modelBuilder.Entity<Movies>().HasMany("Bookmarks");

            modelBuilder.Entity<StoryDictionary>().HasKey(sd => sd.Id);

            modelBuilder.Entity<Filter>().HasKey(f => f.Id);
            //modelBuilder.Entity<MovieImage>().HasKey(mf => mf.Id);

            modelBuilder.Entity<Bookmark>().HasKey(b => b.Id);
            modelBuilder.Entity<Bookmark>().HasOne(b => b.Movies).WithMany(m => m.Bookmarks).HasForeignKey(ms => ms.MovieID);
            modelBuilder.Entity<Cast>().HasKey(c => c.Id);
            modelBuilder.Entity<Cast>().HasOne(m => m.Movies).WithMany(c => c.Casts).HasForeignKey(ca => ca.MovieID);
            modelBuilder.Entity<Cast>().HasOne(a => a.Actor).WithMany(ma => ma.Casts).HasForeignKey(c => c.ActorId);
            modelBuilder.Entity<Actor>().HasKey(a => a.Id);

            // add downloadProperties to model
            modelBuilder.Entity<DownloadProperties>().HasKey(dp => dp.Id);

            modelBuilder.Entity<StoryTransInfo>().HasKey(av => av.Id);

            modelBuilder.Entity<MapDrive>().HasKey(s => s.Id);

            //modelBuilder.Entity<Images>().HasKey(i => i.Id);

            modelBuilder.Entity<MovieAppProperties>().HasKey(s => s.Id);

            modelBuilder.Entity<MovieProperties>().HasKey(s => s.Id);

            //modelBuilder.Entity<MissingGenresMovies>().ToTable("Movies");
            // modelBuilder.Entity<MissingGenresMovies>().ToView("VWUnGeredMovies");

            modelBuilder.Entity<MappedDrives>().HasKey(s => s.Id);

            modelBuilder.Entity<MovieGenre>().HasKey(g => g.Id);
            modelBuilder.Entity<MovieGenre>().HasOne(m => m.Movies).WithMany(me => me.MovieGenres).HasForeignKey(g => g.MovieId);

            modelBuilder.Entity<MovieLanguage>().HasKey(s => s.Id);
            modelBuilder.Entity<MovieLanguage>().HasOne(m => m.Movie).WithMany(l => l.MovieLanguages).HasForeignKey(g => g.MovieId);

            modelBuilder.Entity<PhraseHeader>().HasKey(s => s.Id);
            modelBuilder.Entity<PhraseHeader>().HasMany(s => s.PhraseEntries).WithOne(p => p.PhraseHeader).HasForeignKey(p => p.PhraseID); modelBuilder.Entity<UnboundGridData>().HasKey(u => u.Id);
            // modelBuilder.Entity<MovieGenre>().HasOne(m => m.MainGenreEntity).f
            //modelBuilder.Entity<MovieGenre>().HasOne(m => m.Movies).WithMany(ms => ms.MovieGenres).HasForeignKey(c => c.Genre) ;

            modelBuilder.Entity<Series>().HasKey(s => s.Id);
            modelBuilder.Entity<Series>().HasMany(se => se.Seasons).WithOne(se => se.Series1);

            modelBuilder.Entity<Season>().HasKey(s => s.Id);
            modelBuilder.Entity<Season>().HasOne(s => s.Series1).WithMany(s => s.Seasons).HasForeignKey(se => se.Series);
            modelBuilder.Entity<Season>().HasMany(t => t.TVEpisodes).WithOne(s => s.Season).HasForeignKey(ts => ts.SeasonID);

            modelBuilder.Entity<TVEpisode>().HasKey(t => t.Id);

            modelBuilder.Entity<Director>().HasKey(d => d.Id);
            modelBuilder.Entity<Director>().HasMany(d => d.Movies).WithOne(m => m.Director).HasForeignKey(d => d.DirectorID);

            modelBuilder.Entity<Story>().HasKey(s => s.Id);
            modelBuilder.Entity<Story>().HasMany(s => s.WordHeadingList).WithOne(w => w.Story).HasForeignKey(s => s.StoryId);
            modelBuilder.Entity<Story>().HasOne(m => m.StorySeries).WithMany(c => c.StoryList).HasForeignKey(ca => ca.SeriesId);
            modelBuilder.Entity<Story>().HasOne(m => m.AuthorItem).WithMany(c => c.StoryList).HasForeignKey(ca => ca.IDAuthor);

            modelBuilder.Entity<WordHeadings>().HasKey(b => b.Id);

            modelBuilder.Entity<StorySeries>().HasKey(s => s.Id);

            modelBuilder.Entity<Author>().HasKey(a => a.Id);

            modelBuilder.Entity<StoryCast>().HasKey(s => s.Pk);

            modelBuilder.Entity<UnboundGridData>().HasKey(u => u.Id);
            // modelBuilder.Entity<UnboundGridData>().hasd

            modelBuilder.Entity<StoryHeadings>()
        .ToView("StoryHeadings")
        .HasNoKey();
            modelBuilder.Entity<ProductionCompany>().HasKey(p => p.Id);
            //modelBuilder.Entity<ProductionCompany>().HasMany(m => m.MovieList);

            //modelBuilder.Entity<ProductionCompanyMovie>().HasKey(p => p.Id);
            //modelBuilder.Entity<ProductionCompanyMovie>().HasOne(p => p.ProductionCompany).WithMany(m=>m.)
        }
        #endregion
    }
}
