//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaymadeEntities.Models
{
    using Microsoft.Office.Interop.Word;
    using ReactiveUI;
    using System;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    /// <summary>
    /// Defines the <see cref="Season" />.
    /// </summary>
    [Table("Season")]
    public partial class Season : ModelBase
    {
        #region Fields

        /// <summary>
        /// Defines the description.
        /// </summary>
        private string description;

        /// <summary>
        /// Defines the name.
        /// </summary>
        private string name;

        /// <summary>
        /// Defines the path.
        /// </summary>
        private string path;

        /// <summary>
        /// Defines the seasonNo.
        /// </summary>
        private int? seasonNo;

        /// <summary>
        /// Defines the series.
        /// </summary>
        private int? series;

        /// <summary>
        /// Defines the series1.
        /// </summary>
        private Series series1;

        /// <summary>
        /// Defines the showId.
        /// </summary>
        private int? showId;

        /// <summary>
        /// Defines the tMDBID.
        /// </summary>
        private int? tMDBID;

        /// <summary>
        /// Defines the tVEpisodes.
        /// </summary>
        private ObservableCollection<TVEpisode> tVEpisodes;

        /// <summary>
        /// Defines the year.
        /// </summary>
        private int? year;

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="Season"/> class.
        /// </summary>
        public Season()
        {
            this.TVEpisodes = new ObservableCollection<TVEpisode>();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Season"/> class.
        /// </summary>
        /// <param name="series">The series<see cref="Models.Series"/>.</param>
        public Season(Models.Series series)
        {
            this.TVEpisodes = new ObservableCollection<TVEpisode>();
            Series = series.Id;
            SeasonNo = series.Seasons.Count;
            ShowId = series.TMID;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Season"/> class.
        /// </summary>
        /// <param name="season">The season<see cref="Support.Season"/>.</param>
        public Season(Support.Season season)
        {
            this.TVEpisodes = new ObservableCollection<TVEpisode>();
            this.TMDBID = season.TMID;
            this.SeasonNo = season.SeasonNo;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the Description.
        /// </summary>
        public string? Description { get => description; set => this.RaiseAndSetIfChanged(ref description, value); }

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        [Key]
        public new int Id { get; set; }

        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        public string? Name { get => name; set => this.RaiseAndSetIfChanged(ref name, value); }

        /// <summary>
        /// Gets or sets the Path.
        /// </summary>
        public string Path { get => path; set => this.RaiseAndSetIfChanged(ref path, value); }

        /// <summary>
        /// Gets or sets the SeasonNo.
        /// </summary>
        public Nullable<int> SeasonNo { get => seasonNo; set => this.RaiseAndSetIfChanged(ref seasonNo, value); }

        /// <summary>
        /// Gets or sets the Series.
        /// </summary>
        [ForeignKey("FK_SeasonToSeries")]
        public Nullable<int> Series { get => series; set => this.RaiseAndSetIfChanged(ref series, value); }

        /// <summary>
        /// Gets or sets the Series1.
        /// </summary>
        [NotMapped]
        public virtual Series Series1 { get => series1; set => this.RaiseAndSetIfChanged(ref series1, value); }

        /// <summary>
        /// Gets or sets the ShowId.
        /// </summary>
        public Nullable<int> ShowId { get => showId; set => this.RaiseAndSetIfChanged(ref showId, value); }

        /// <summary>
        /// Gets or sets the TMDBID.
        /// </summary>
        public Nullable<int> TMDBID { get => tMDBID; set => this.RaiseAndSetIfChanged(ref tMDBID, value); }

        /// <summary>
        /// Gets or sets the TVEpisodes.
        /// </summary>
        public virtual ObservableCollection<TVEpisode> TVEpisodes
        {
            get
            {
                if (tVEpisodes == null || tVEpisodes.Count == 0)
                {
                    tVEpisodes = new ObservableCollection<TVEpisode>(DataController.SandboxEntities.TVEpisodes.Where(t => t.SeasonID == Id).ToList());
                }
                return tVEpisodes;
            }

            set => this.RaiseAndSetIfChanged(ref tVEpisodes, value);
        }

        /// <summary>
        /// Gets or sets the Year.
        /// </summary>
        public Nullable<int> Year { get => year; set => this.RaiseAndSetIfChanged(ref year, value); }

        #endregion

        public async static Task<Season> CreateNewSeasonForSeries(Series series, 
            Avalonia.Controls.Window? window = null)
        {
            Season newSeason = null;

            if (series == null) return null; // need a series to work 

            using TaymadeEntities.ViewModels.EntryDialogModel entryDialogModel =
                    new TaymadeEntities.ViewModels.EntryDialogModel(TaymadeEntities.ViewModels.EntryDialogModel.EntryType.Text);
            using TaymadeEntities.Dialogs.EntryDialog entryDialog = new TaymadeEntities.Dialogs.EntryDialog(entryDialogModel);

            using var _context = new TaymadeEntities.DBContext.SandboxEntities();
            {
                newSeason = new Season()
                {
                    Series = series.Id,
                    ShowId = series.TMID
                };

                entryDialog.Title = "Get Season Name";
                entryDialog.entryText.Text = "<new season name>";

                if (window == null) window = Support.Support.GetMainWindow() as Avalonia.Controls.Window;

                DialogResultButton result = await entryDialog.ShowDialog<DialogResultButton>(window);
                if (result != null && result.Result == DialogResultButton.ResultType.Ok)
                {
                    newSeason.Name = result.Parameter;
                }
                newSeason.SeasonNo = series.Seasons.Count + 1;
                _context.Seasons.Add(newSeason);
                _context.SaveChanges();
            }

            return newSeason;
        }

        public async static Task<Season> AddSeasonToMovie(int id, Avalonia.Controls.Window? window = null)
        {
            Season newSeason = null;

            using TaymadeEntities.ViewModels.EntryDialogModel entryDialogModel =
                    new TaymadeEntities.ViewModels.EntryDialogModel(TaymadeEntities.ViewModels.EntryDialogModel.EntryType.List);
            using TaymadeEntities.Dialogs.EntryDialog entryDialog = new TaymadeEntities.Dialogs.EntryDialog(entryDialogModel);

            using var _context = new TaymadeEntities.DBContext.SandboxEntities();
            {
                Movies? movie = _context.Movies.Find(id);
                if (movie != null)
                {
                    // check we have a Series essential 

                    if (movie.Series == null)
                    {
                        // get Series
                        Series tempSeries = await Models.Series.AddSeriesToMovie(movie.Id);
                        if (tempSeries == null) return null;
                        // set series value
                        movie.Series = tempSeries.Id;
                        _context.SaveChanges();
                        movie.SeriesEntity = tempSeries;
                    }

                    if (movie.SeriesEntity != null &&
                        (movie.SeriesEntity.Seasons == null || movie.SeriesEntity.Seasons.Count == 0))
                    {
                        movie.SeriesEntity.Seasons = DataController.MovieController.GetSeasonsBySeriesID(movie.Series.Value);
                    }

                    entryDialog.Title = "Set Season Value";
                    entryDialogModel.ItemList = movie.SeriesEntity.Seasons;

                    if (window == null) window = Support.Support.GetMainWindow() as Avalonia.Controls.Window;

                    DialogResultButton result = await entryDialog.ShowDialog<DialogResultButton>(window);
                    if (result != null && result.Result == DialogResultButton.ResultType.Ok)
                    {
                        Season? series = result.ListValue as Season;
                        newSeason = series;
                        if (series != null)
                        {
                            movie.Season = series.Id;
                            _context.SaveChanges();
                        }
                    }
                }
            }
            return newSeason;
        }
    }
}
