//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonMVVM.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    /// <summary>
    /// Defines the <see cref="Series" />.
    /// </summary>
    public partial class Series : ModelBase,IObservable<Series>
    {
        #region Fields

        /// <summary>
        /// Defines the intro.
        /// </summary>
        private int? intro;

        /// <summary>
        /// Defines the name.
        /// </summary>
        private string name;

        /// <summary>
        /// Defines the overview.
        /// </summary>
        private string overview;

        /// <summary>
        /// Defines the path.
        /// </summary>
        private string path;

        /// <summary>
        /// Defines the seasons.
        /// </summary>
        private ObservableCollection<Season> seasons;

        /// <summary>
        /// Defines the tMID.
        /// </summary>
        private int tMID;

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="Series"/> class.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Series()
        {
            this.Movies = new HashSet<Movies>();
            this.Seasons = new ObservableCollection<Season>();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Series"/> class.
        /// </summary>
        /// <param name="seriesId">The seriesId<see cref="int?"/>.</param>
        public Series(int? seriesId)
        {
            this.Movies = new HashSet<Movies>();
            this.Seasons = new ObservableCollection<Season>();

            if (seriesId == 2 || seriesId == null)
            {

            }
            else
            {
                this.Movies = new HashSet<Movies>();
                this.seasons = new ObservableCollection<Season>();
            }

            Series series = DataController.SandboxEntities.Series.Find(seriesId);

            if (series != null)
            {
                Id = series.Id;
                Name = series.Name;
                this.Intro = series.Intro;
                this.TMID = series.TMID;
                this.Overview = series.Overview;
                this.Outro = series.Outro;
                this.Path = series.Path;
                Seasons = new ObservableCollection<Season>(DataController.SandboxEntities.Seasons.Where(se => se.Series == Id).OrderBy(s => s.SeasonNo).ToList());
                // Seasons = setemp;
            }
        }

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        [Key]
        public new int Id { get; set; }

        /// <summary>
        /// Gets or sets the Intro.
        /// </summary>
        public Nullable<int> Intro { get => intro; set => intro = value; }

        /// <summary>
        /// Gets or sets the Movies.
        /// </summary>
        [NotMapped]
        public virtual ICollection<Movies> Movies { get; set; }

        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        public string Name { get => name; set => name = value; }

        /// <summary>
        /// Gets or sets the Outro.
        /// </summary>
        public Nullable<int> Outro { get; set; }

        /// <summary>
        /// Gets or sets the Overview.
        /// </summary>
        public string Overview { get => overview; set => overview = value; }

        /// <summary>
        /// Gets or sets the Path.
        /// </summary>
        public string Path { get => path; set => path = value; }

        /// <summary>
        /// Gets or sets the Seasons.
        /// </summary>
        [NotMapped]
        public virtual ObservableCollection<Season> Seasons
        {
            get
            {
                if (seasons == null || seasons.Count ==0)
                {
                    List<Season> tempList = DataController.SandboxEntities.Seasons.Where(s =>  s.Series.Value == this.Id).ToList();
                    seasons = new ObservableCollection<Season>(tempList);
                }
                return seasons;
            }

            set
            {
                seasons = value;
            }
        }

        /// <summary>
        /// Gets or sets the TMID.
        /// </summary>
        public int TMID { get => tMID; set => tMID = value; }

        IDisposable IObservable<Series>.Subscribe(IObserver<Series> observer)
        {
            // No observable sequence implemented, so return a dummy disposable.
            // This prevents the CS0161 error by ensuring all code paths return a value.
            return System.Reactive.Disposables.Disposable.Empty;
        }

        #endregion
    }
}
