using Avalonia.Logging;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace TaymadeEntities.Models
{
    /// <summary>
    /// Holds Dictionary items for the Story
    /// </summary>
    /// <autogeneratedoc />
    public class StoryDictionary
    {
        #region Public Properties

        public string? DictionaryText { get; set; }
        public int Id { get; set; }
        public int StoryId { get; set; }

        #endregion Public Properties

        #region Public Fields

        public string DictionaryPath = @"K:\Drive_I\Stories\CurrentStory.dic";

        #endregion Public Fields

        #region Constructors

        public StoryDictionary()
        {
        }

        public StoryDictionary(int storyId)
        {
            StoryId = storyId;
            // get the data from database
            StoryDictionary? temp = DataController.SandboxEntities.StoryDictionary.Where(sd => sd.StoryId == storyId).FirstOrDefault();

            // if the temp is not null, set the properties
            if (temp != null)
            {
                Id = temp.Id;
                DictionaryText = temp.DictionaryText;
            }
            else
            {
                // If no dictionary exists for the story, initialize with an empty string
                DictionaryText = string.Empty;
            }
        }

        #endregion Constructors

        #region Public Methods

        public void CreateCustomDictionary()

        {
            // Create a new dictionary file for the current story writing the contents of the dictionary field into the file one line at a time.
            // Create a text file using the DictionaryPath
            using (System.IO.StreamWriter file = new System.IO.StreamWriter(Support.Support.FixImagePath(DictionaryPath)))
            {
                // Check if Dictionary is not null or empty
                if (!string.IsNullOrEmpty(DictionaryText))
                {
                    // Split the dictionary string by commas and write each word to the file
                    foreach (var word in DictionaryText.Split(','))
                    {
                        file.WriteLine(word.Trim());
                    }
                }
                file.Flush();
                file.Close();
            }
        }

        /// <summary>
        /// Deletes this instance.
        /// </summary>
        /// <returns></returns>
        /// <autogeneratedoc />
        public bool Delete()
        {
            // Delete the current story dictionary from the database using the procedure in Sand=boxEntities
            bool result = DataController.SandboxEntities.DeleteStoryDictionary(StoryId);
            // remove from local database if the value exists


            return result;
        }

        /// <summary>
        /// Inserts this instance.
        /// </summary>
        /// <autogeneratedoc />
        public void Insert()
        {
            try
            {


                // check if the current story dictionary already exists in the database
                var existing = DataController.SandboxEntities.StoryDictionary.AsNoTracking().FirstOrDefault(entry => entry.Id.Equals(Id));
                if (existing != null)
                {
                    // If it exists, update it instead
                    Update();
                    return;
                }
                else
                {
                    // Ensure the Id is set to 0 so that EF Core treats this as a new entity
                    Id = 0;
                    // Insert the current story dictionary into the database
                    DataController.SandboxEntities.StoryDictionary.Add(this);
                    DataController.SandboxEntities.SaveChanges();
                }
            }
            catch (Exception ex)
            {

                string error = ex.ToString();
                // should log this message
                Support.Support.Logger.Error($"Error in Word processing: {error}");

            }
        }

        /// <summary>
        /// Loads the dictionary.
        /// </summary>
        /// <autogeneratedoc />
        public void LoadDictionary()
        {
            // Load the dictionary from the file into the DictionaryText property
            if (System.IO.File.Exists(DictionaryPath))
            {
                DictionaryText = System.IO.File.ReadAllText(DictionaryPath);

                // if dictionarytext not null or empty convert newline or cr to commas
                if (!string.IsNullOrEmpty(DictionaryText))
                {
                    DictionaryText = DictionaryText.Replace(Environment.NewLine, ",").Replace("\r", ",").Replace("\n", ",");
                    // remove text Doug and Taylor irrespective of case
                    DictionaryText = System.Text.RegularExpressions.Regex.Replace(DictionaryText, "Doug", "", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
                    DictionaryText = System.Text.RegularExpressions.Regex.Replace(DictionaryText, "Taylor", "", System.Text.RegularExpressions.RegexOptions.IgnoreCase);

                    // remove any double commas
                    DictionaryText = DictionaryText.Replace(",,", ",");

                    // Remove any leading commas
                    if (DictionaryText.StartsWith(","))
                    {
                        DictionaryText = DictionaryText.TrimStart(',');
                    }

                    // Remove any trailing commas
                    if (DictionaryText.EndsWith(","))
                    {
                        DictionaryText = DictionaryText.TrimEnd(',');
                    }

                    // replace doubled commas with a single comma
                    DictionaryText = DictionaryText.Replace(",,", ",");

                    // trim any leading or trailing whitespace
                    DictionaryText = DictionaryText.Trim();

                    // split string into array and sort alphabetically and remove duplicates then reform string
                    var words = DictionaryText.Split(',').Select(w => w.Trim()).Where(w => !string.IsNullOrEmpty(w)).Distinct().OrderBy(w => w);
                    DictionaryText = string.Join(",", words);
                    DictionaryText = DictionaryText.Trim();

                    // save back to database if there is anything to save or delete if empty
                    if (!string.IsNullOrEmpty(DictionaryText))
                        Update();
                    else
                        this.Delete();
                }
                else
                {
                    // Database entry needs to be deleted
                    Delete();
                }
            }
            else
            {
                DictionaryText = string.Empty; // If the file does not exist, set to empty
            }
        }

        /// <summary>
        /// Updates this instance.
        /// </summary>
        /// <autogeneratedoc />
        public void Update()
        {
            try
            {
                // Check if the current story dictionary exists in the database
                var existing = DataController.SandboxEntities.StoryDictionary.AsNoTracking().FirstOrDefault(entry => entry.Id.Equals(Id));
                if (existing == null)
                {
                    // If it does not exist, insert it
                    Insert();
                    return;
                }
                // If it exists, update the existing entry
                // Update the current story dictionary in the database
                var local = DataController.SandboxEntities.Set<StoryDictionary>().Local.FirstOrDefault(entry => entry.Id.Equals(Id));

                // check if local is not null
                if (local != null)
                {
                    // detach
                    DataController.SandboxEntities.Entry(local).State = EntityState.Detached;
                }
                DataController.SandboxEntities.StoryDictionary.Update(this);
                DataController.SandboxEntities.SaveChanges();
            }
            catch (Exception ex)
            {
                // Log the exception
                Console.WriteLine($"An error occurred while checking for existing StoryDictionary: {ex.Message}");
                throw; // Re-throw the exception after logging it
            }

        }

        #endregion Public Methods
    }
}