//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace TaymadeEntities.Models
{
    public class StoryAuthor
    {
        private Author author;
        private int rowschanged;

        public int Id { get; set; }

        public int StoryId { get; set; }
        
        public int AuthorId { get; set; }

        [NotMapped]
        public Author? Author
        {
            get
            {
                if (author == null)
                {
                    author = DataController.AuthorList.Where(a => a.Id == this.AuthorId).FirstOrDefault();
                }
                return author;
            }

            set => author = value;
        }

        /// <summary>
        /// Inserts this instance.
        /// </summary>
        /// <autogeneratedoc />
        public void Insert()
        {
            DataController.SandboxEntities.StoryAuthor.Add(this);
            rowschanged = DataController.SandboxEntities.SaveChanges();
        }

        /// <summary>
        /// Saves this instance. If Id is 0, it will insert a new record. If Id is not 0, it will update the record.
        /// </summary>
        /// <autogeneratedoc />
        internal void Save()
        {
            var local = DataController.SandboxEntities.Set<StoryAuthor>().Local.FirstOrDefault(entry => entry.Id.Equals(Id));

            // an Id of 0 indicates a new record
            if (Id == 0)
            {
                DataController.SandboxEntities.StoryAuthor.Add(this);
                rowschanged = DataController.SandboxEntities.SaveChanges();
            }
            else // updating an existing record
            {
                // check if local is not null
                if (local != null)
                {
                    // detach
                    DataController.SandboxEntities.Entry(local).State = EntityState.Detached;
                }
                DataController.SandboxEntities.Entry(this).State = EntityState.Modified;
                rowschanged = DataController.SandboxEntities.SaveChanges();

            }

            // check if local is not null
            if (local != null)
            {
                // detach
                DataController.SandboxEntities.Entry(local).State = EntityState.Detached;
            }
      }
    }
}