//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonMVVM.Models
{
    using ReactiveUI;
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.CompilerServices;

    /// <summary>
    /// Defines the <see cref="TVEpisode" />.
    /// </summary>
    [Table("TVEpisode")]
    public partial class TVEpisode : ModelBase
    {
        #region Fields

        /// <summary>
        /// Defines the airDate.
        /// </summary>
        private DateTime? airDate;

        /// <summary>
        /// Defines the movieId.
        /// </summary>
        private int? movieId;
        private int? episodeNumber;

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="TVEpisode"/> class.
        /// </summary>
        public TVEpisode()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TVEpisode"/> class.
        /// </summary>
        /// <param name="season">The season<see cref="Models.Season"/>.</param>
        public TVEpisode(Models.Season season)
        {
            this.Season = season;
            this.SeasonID = season.Id;
            this.SeasonNumber = season.SeasonNo;
            this.ShowID = season.ShowId;
        }

        #endregion

        #region Events

        /// <summary>
        /// Defines the PropertyChanged.
        /// </summary>
        //public event PropertyChangedEventHandler PropertyChanged;

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the AirDate.
        /// </summary>
        public System.DateTime? AirDate
        {
            get => airDate; set
            {
                //if (airDate != value)
                //{
                    this.RaiseAndSetIfChanged(ref airDate, value);
                   // NotifyPropertyChanged();
                //}
            }
        }

        /// <summary>
        /// Gets or sets the EpisodeNumber.
        /// </summary>
        public int? EpisodeNumber { get => episodeNumber; set =>this.RaiseAndSetIfChanged(ref episodeNumber, value); }

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        [Key]
       // public int Id { get; set; }

        /// <summary>
        /// Gets or sets the Movie.
        /// </summary>
        [NotMapped]
        public virtual Movies? Movie { get; set; }

        /// <summary>
        /// Gets or sets the MovieId.
        /// </summary>
        public int? MovieId { get => movieId; set => this.RaiseAndSetIfChanged(ref movieId, value); }

        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the Overview.
        /// </summary>
        public string? Overview { get; set; }

        /// <summary>
        /// Gets the Runtime.
        /// </summary>
        [NotMapped]
        public string? Runtime
        {
            get
            {
                string retValue = "??";

                if (this.MovieId != null && this.MovieId > 0)
                {
                    if (Movie == null)
                    {
                        Movie = DataController.SandboxEntities.Movies.Find(MovieId.Value);
                    }

                    if (Movie != null && Movie.DurationSeconds != null)
                    {
                        TimeSpan ts = TimeSpan.FromSeconds(Movie.DurationSeconds.Value);

                        retValue = ts.ToString();
                    }
                }

                return retValue;
            }
        }

        /// <summary>
        /// Gets or sets the Season.
        /// </summary>
        [NotMapped]
        public virtual Season? Season { get; set; }

        /// <summary>
        /// Gets or sets the SeasonID.
        /// </summary>
        [ForeignKey("FK_TVEpisode_ToSeason")]
        public int? SeasonID { get; set; }

        /// <summary>
        /// Gets or sets the SeasonNumber.
        /// </summary>
        public int? SeasonNumber { get; set; }

        /// <summary>
        /// Gets or sets the ShowID.
        /// </summary>
        public int? ShowID { get; set; }

        /// <summary>
        /// Gets or sets the TMID.
        /// </summary>
        public int? TMID { get; set; }

        #endregion

        #region Methods
        
        #endregion
    }
}
