//-----------------------------------------------------------------------
// <copyright file="UnboundGridData.cs" company="Taymade Software Services">
//     Copyright (c) Taymade Software Services. All rights reserved.
// </copyright>
// <created>04/12/2021 10:47:45 04/12/2021 10:47:45 </created>
// <author>Doug Taylor</author>
//-----------------------------------------------------------------------

namespace TaymadeEntities.Models
{
    using Microsoft.EntityFrameworkCore;
    using ReactiveUI;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    /// <summary>
    /// Defines the <see cref="UnboundGridData" />.
    /// </summary>
    [PrimaryKey("Id")]
    public class UnboundGridData : ReactiveObject
    {
        #region Fields

        private int? durationSeconds;

        private long? fileLength;

        /// <summary>
        /// Defines the fileName.
        /// </summary>
        private string? fileName;
        private bool hasTMIDB;
        private TimeSpan movieDuration;
        private string? overview;
        private bool? selected;
        private int? tIMDB;
        private int? year;
        private string? name;

        public UnboundGridData()
        {
            IsSelected = false;
        }


        #endregion

        #region Properties


        /// <summary>
        /// Gets or sets the CreationTime.
        /// </summary>
        public string CreationTime { get; set; } = string.Empty;

        public string? Name
        {
            get
            {
                if (string.IsNullOrEmpty(name) || !string.IsNullOrEmpty(FileName))
                    return System.IO.Path.GetFileName(FileName);
                return name;
            }

            set => this.RaiseAndSetIfChanged(ref name, value);
        }

        public Nullable<int> DurationSeconds
        {
            get
            {
                if (durationSeconds == null || durationSeconds == 0)
                {
                    //      SetError("Duration:Must be greater than Zero");
                    if (durationSeconds == null) durationSeconds = 0;
                }

                return durationSeconds;
            }

            set
            {
                if (value != null)
                {
                    this.RaiseAndSetIfChanged(ref durationSeconds, value);
                    MovieDuration = Support.Support.SetMovieDuration(value);
                    Save();
                    //this.SetPercentUnmarked();
                }

            }
        }

        [NotMapped]
        public string? FilePath { get; set; }

        /// <summary>
        /// Gets or sets the FileInfo.
        /// </summary>
        [NotMapped]
        public System.IO.FileInfo? FileInfo { get; set; }

        /// <summary>
        /// Gets the file length mb.
        /// </summary>
        /// <value>
        /// The file length mb.
        /// </value>
        /// <autogeneratedoc />
        public long FileLengthMB
        {
            get
            {
                if (fileLength.Value == 0)
                    Support.DownloadSupport.GetFileInfo(this);
                return fileLength.Value / 1024 / 1024;
            }
        }

        public string DisplayFileLengthMB
        {
            get
            {
                if (fileLength == 0)
                    Support.DownloadSupport.GetFileInfo(this);
                return $"{FileLengthMB} MB";
            }
        }

        /// <summary>
        /// Gets or sets the FileLength.
        /// </summary>
        public long? FileLength
        {
            get
            {
                if (fileLength == null) fileLength = 0;


                if (fileLength == 0)
                    Support.DownloadSupport.GetFileInfo(this);
                return fileLength;
            }

            set
            {
                this.RaiseAndSetIfChanged(ref fileLength, value);
                this.RaisePropertyChanged(nameof(FileLengthMB));
                this.RaisePropertyChanged(nameof(DisplayFileLengthMB));
            }
        }

        /// <summary>
        /// Gets or sets the FileName.
        /// </summary>
        public string? FileName
        {
            get => fileName;
            set
            {
                this.RaiseAndSetIfChanged(ref fileName, value);
                //Save();
            }
        }

        /// <summary>
        /// Gets or sets the Folder.
        /// </summary>
        [NotMapped]
        public string Folder { get; set; } = string.Empty;

        [NotMapped]
        public bool HasTMIDB
        {
            get
            {
                hasTMIDB = (TIMDB != null);
                return hasTMIDB;
            }

            set => hasTMIDB = value;
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [NotMapped]
        public bool? IsSelected { get => selected; set => this.RaiseAndSetIfChanged(ref selected, value); }

        [NotMapped]
        public TimeSpan MovieDuration
        {
            get
            {
                SetMovieDurationValue();
                return movieDuration;
            }

            set =>
                //movieDuration = value;
                this.RaiseAndSetIfChanged(ref movieDuration, value);
        }

        /// <summary>
        /// Gets or sets the MovieId.
        /// </summary>
        [NotMapped]
        public int MovieId { get; set; }

        /// <summary>
        /// Gets the Name.
        /// </summary>



        public string? Overview { get => overview; set => this.RaiseAndSetIfChanged(ref overview, value); }
        public int? TIMDB { get => tIMDB; set => this.RaiseAndSetIfChanged(ref tIMDB, value); }
        public int? Year { get => year; set => this.RaiseAndSetIfChanged(ref year, value); }
        public void SetMovieDurationValue()
        {
            if (movieDuration == TimeSpan.MinValue && DurationSeconds != null)
            {
                MovieDuration = Support.Support.SetMovieDuration(DurationSeconds);

                //this.RaiseAndSetIfChanged(ref movieDuration, value);
            }
            else if ((int)movieDuration.TotalSeconds != DurationSeconds && DurationSeconds != null)
            {
                MovieDuration = Support.Support.SetMovieDuration(DurationSeconds);
                // this.RaiseAndSetIfChanged(ref movieDuration, value);
                // this.RaisePropertyChanged("MovieDuration");
            }
            else if (movieDuration == TimeSpan.MinValue)
            {
                MovieDuration = Support.Support.SetMovieDuration(0);
                //movieDuration = TimeSpan.FromSeconds((Double)0);
            }
        }
        #endregion

        #region Methods

        public bool Insert()
        {
            bool success = false;
            if (this.Id <= 0 && !string.IsNullOrEmpty(FileName))  // new entity so save to get id for new entity
            {
                try
                {
                    // insert by a stored procedure to get the id of the new entity
                    UnboundGridData? temp = DataController.SandboxEntities.CreateUnbound(FileName, FileLength.Value, DurationSeconds.Value, CreationTime, Name);
                    if (temp != null)
                    {
                        this.Id = temp.Id;
                    }
                    else
                        temp = DataController.SandboxEntities.UnboundGridData.Where(u => u.FileName.ToLower() == FileName.ToLower()).FirstOrDefault();
                    success = true;
                }
                catch (Exception ex)
                {
                    success = false;
                    //throw;
                }
                return success;
            }
            else
                return this.Save();

        }

        #region Internal Methods

        public bool Delete()
        {
            bool success = true;
            try
            {

                DataController.SandboxEntities.DeleteUnbound(this.Id);
                //DataController.SandboxEntities.SaveChanges();
            }
            catch (Exception ex)
            {
                success = false;
                //throw;
            }
            return success;
        }

        public static UnboundGridData Create(string folderPath, string fileName, string sep = "\\")
        {
            UnboundGridData unboundGridData = new UnboundGridData();
            unboundGridData.Folder = folderPath;
            string dataFileName = folderPath + sep + fileName;
            unboundGridData.FileName = dataFileName;
            unboundGridData.Name = fileName.Trim();
            unboundGridData.FilePath = dataFileName;

            System.IO.FileInfo fileInfo = new System.IO.FileInfo(dataFileName);
            unboundGridData.FileLength = fileInfo.Length;
            unboundGridData.CreationTime = fileInfo.CreationTime.ToString("yyyy/MM/dd HH:mm");
            unboundGridData.FileInfo = fileInfo;
            unboundGridData.Insert();
            if (unboundGridData.Id > 0) unboundGridData.Save();

            return unboundGridData;
        }
        public bool Save()
        {

            bool success = false;
            try
            {
                if (Id == 0)
                {
                    success = Insert();
                }


                if (Id > 0 && !string.IsNullOrEmpty(FileName))
                {
                    //EntityState state = DataController.SandboxEntities.Entry(this).State;

                    //var local = DataController.SandboxEntities.Set<UnboundGridData>().Local.FirstOrDefault(entry => entry.Id.Equals(Id));

                    //// check if local is not null
                    //if (local != null)
                    //{
                    //    // detach
                    //    DataController.SandboxEntities.Entry(local).State = EntityState.Detached;
                    //}
                    // set Modified flag in your entry
                    //DataController.SandboxEntities.Entry(this).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                    success = DataController.UnboundController.Update(this);
                   
                }
            }
            catch (Exception ex)
            {
                string msg = "error Saving movie : " + Id.ToString() + " : " + Name;
                Support.Support.Logger.Error(ex, msg);

                MVMLogs logs = new MVMLogs(ex, "database", "Error", "Downloads");
                success = false;
            }

            return success;
            #endregion
        }

        public void Refresh()
        {
            // read file data and update filelength etc
            Support.DownloadSupport.GetFileInfo(this);

        }

        #endregion Internal Methods
    }
    /// <summary>
    /// Defines the <see cref="UnboundGridDataCollection" />.
    /// </summary>
    public class UnboundGridDataCollection : List<UnboundGridData>
    {
        #region Fields

        /// <summary>
        /// Defines the creationCol.
        /// </summary>
        private int creationCol = 3;

        /// <summary>
        /// Defines the fileLengthCol.
        /// </summary>
        private int fileLengthCol = 2;

        /// <summary>
        /// Defines the fileNameCol.
        /// </summary>
        private int fileNameCol = 1;

        /// <summary>
        /// Defines the folderDirection.
        /// </summary>
        private int folderDirection = 0;

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="UnboundGridDataCollection"/> class.
        /// </summary>
        public UnboundGridDataCollection()
        {
            List<UnboundGridData> unbounds = DataController.SandboxEntities.UnboundGridData.ToList();

            foreach (var item in unbounds)
            {
                Add(item);
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UnboundGridDataCollection"/> class.
        /// </summary>
        /// <param name="list">The list<see cref="List{UnboundGridData}"/>.</param>
        public UnboundGridDataCollection(List<UnboundGridData> list)
        {
            foreach (var item in list)
            {
                Add(item);
            }
        }

        public UnboundGridDataCollection(IEnumerable<UnboundGridData> collection) : base(collection)
        {
        }

        #endregion

        #region Methods

        /// <summary>
        /// The SortByColumn.
        /// </summary>
        /// <param name="column">The column<see cref="int"/>.</param>
        /// <param name="direction">The direction<see cref="ListSortDirection"/>.</param>
        public void SortByColumn(int column, ListSortDirection direction)
        {
            if (column == folderDirection)
            {
                if (direction == ListSortDirection.Ascending)
                    Sort((x, y) => x.Folder.CompareTo(y.Folder));
                if (direction == ListSortDirection.Descending)
                    Sort((x, y) => y.Folder.CompareTo(x.Folder));
            }
            else if (column == fileNameCol)
            {
                if (direction == ListSortDirection.Ascending)
                    Sort((x, y) => x.FileName!.CompareTo(y.FileName));
                if (direction == ListSortDirection.Descending)
                    Sort((x, y) => y.FileName!.CompareTo(x.FileName));
            }
            else if (column == fileLengthCol)
            {
                if (direction == ListSortDirection.Ascending)
                    Sort((x, y) => x.FileLength.Value.CompareTo(y.FileLength.Value));
                if (direction == ListSortDirection.Descending)
                    Sort((x, y) => y.FileLength.Value.CompareTo(x.FileLength.Value));
            }
            else if (column == creationCol)
            {
                if (direction == ListSortDirection.Ascending)
                    Sort((x, y) => x.CreationTime.CompareTo(y.CreationTime));
                if (direction == ListSortDirection.Descending)
                    Sort((x, y) => y.CreationTime.CompareTo(x.CreationTime));
            }
        }

        /// <summary>
        /// The SortByColumn.
        /// </summary>
        /// <param name="column">The column<see cref="string"/>.</param>
        /// <param name="direction">The direction<see cref="int"/>.</param>
        public void SortByColumn(string column, int direction)
        {
            int SortColumn = 0;
            if (column == "File Length") SortColumn = 2;
            else if (column == "Name") SortColumn = 1;

            else if (column == "Creation Time") SortColumn = 3;

            ListSortDirection sortDirection = ListSortDirection.Ascending;
            if (direction < 1) sortDirection = ListSortDirection.Descending;

            SortByColumn(SortColumn, sortDirection);
        }

        #endregion
    }
}
