//-----------------------------------------------------------------------
// <copyright file="WordHeadings.cs" company="Taymade Software Services">
//     Copyright (c) Taymade Software Services. All rights reserved.
// </copyright>
// <created>14/07/2022 21:08:32 14/07/2022 21:08:32 </created>
// <author>Doug Taylor</author> 
//-----------------------------------------------------------------------

using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace TaymadeEntities.Models
{
    //using TaymadeEntities.Support;
    using SupportCore;
    using Microsoft.EntityFrameworkCore;
    using ReactiveUI;
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using SupportCore.Word;


    public class StoryHeadings
    {
        public StoryHeadings()
        {
        }

        //public WordHeadingFlat(WordHeadings heading)
        //{
        //    if (heading.HeadingLevel == 0)
        //    {
        //        Section = heading.HeadingText;
        //        // see if there are children
        //    } 
        //    else if (heading.HeadingLevel == 1)
        //    {
        //        Heading1 = heading.HeadingText;
        //    }
        //    else if (heading.HeadingLevel == 2)
        //    {
        //        Heading2 = heading.HeadingText;
        //    }
        //    else if (heading.HeadingLevel == 3)
        //    {
        //        Heading3 = heading.HeadingText;
        //    }

        //}


        public string? Section { get; set; } = "";
        public string? SectionId { get; set; } = "";
        public string? Heading1 { get; set; } = "";
        public string? Heading2 { get; set; } = "";
        public string? Heading3 { get; set; } = "";
        public int? StoryId { get; set; }
        public int? SectionLevel { get; set; }
        public int? HeadingLevel { get; set; }

    }


    /// <summary>
    /// Defines the <see cref="WordHeadings" />.
    /// </summary>
    public class WordHeadings : ModelBase
    {
        #region Fields

        private bool hasChildren;

        private ObservableCollection<WordHeadings> heading2s = [];

        /// <summary>
        /// Defines the headingLevel.
        /// </summary>
        private int? headingLevel;

        /// <summary>
        /// Defines the headingText.
        /// </summary>
        private string? headingText;

        private int pageNumber = 0;

        /// <summary>
        /// Defines the storyId.
        /// </summary>
        private int storyId;

        /// <summary>
        /// Defines the stringId.
        /// </summary>
        private string? stringId;
        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="WordHeadings"/> class.
        /// </summary>
        public WordHeadings()
        {
        }

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the children.
        /// </summary>
        /// <value>
        /// The children.
        /// </value>
        /// <autogeneratedoc />
        [NotMapped]
        public ObservableCollection<WordHeadings> Children
        {
            get => heading2s;
            set => heading2s = value;
        }

        [NotMapped]
        public bool HasChildren { get { return Children.Count > 0; } internal set => hasChildren = value; }

        /// <summary>
        /// Gets or sets the HeadingLevel.
        /// </summary>
        public int? HeadingLevel { get => headingLevel; set => this.RaiseAndSetIfChanged(ref headingLevel, value); }

        /// <summary>
        /// Gets or sets the HeadingText.
        /// </summary>
        public string? HeadingText { get => headingText; set => this.RaiseAndSetIfChanged(ref headingText, value); }

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        [Key]
        public new int Id { get; set; }

        [NotMapped]
        public bool IsExpanded { get; internal set; }

        public int PageNumber { get => pageNumber; set => this.RaiseAndSetIfChanged(ref pageNumber, value); }
        public int ParentId { get; set; }
        /// <summary>
        /// Gets or sets the Story.
        /// </summary>
        public Story? Story { get; set; }

        /// <summary>
        /// Gets or sets the StoryId.
        /// </summary>
        public int StoryId { get => storyId; set => this.RaiseAndSetIfChanged(ref storyId, value); }

        /// <summary>
        /// Gets or sets the StringId.
        /// </summary>
        public string? StringId { get => stringId; set => this.RaiseAndSetIfChanged(ref stringId, value); }
        #endregion

        #region Methods

        public static string Heading1ID(string chapId)
        {
            //construct the string id
            string stringId = string.Empty;
            if (int.TryParse(chapId, out int sectNum))
            {
                stringId = Heading1ID(sectNum);
            }
            return stringId;
        }

        public static string Heading1ID(int chapNum)
        {
            string stringId = "heading1_";
            return stringId += chapNum.ToString("00");
        }

        public static string Heading2ID(string chapId, string head2Num)
        {
            //construct the string id
            string stringId = "heading2_";
            if (int.TryParse(chapId, out int sectNum))
            {
                stringId += sectNum.ToString("00");

                // add in section 2 pos 
                if (int.TryParse(head2Num, out int head2NumInt))
                {
                    stringId += "_" + head2NumInt.ToString("00");
                }
            }
            return stringId;
        }

        public static string SectionID(int sectNum)
        {
            //construct the string id

            string StringId = "Sect_" + sectNum.ToString("00");
            return StringId;

        }

        public OpenXMLBreak ToBreak(string stringId)
        {
            int sectID = int.Parse(stringId.Substring(5));

            return ToBreak(sectID);
        }

        public OpenXMLBreak ToBreak(int sectID)
        {
            OpenXMLBreak openXMLBreak = new OpenXMLBreak();
            openXMLBreak.BreakID = sectID;
            openXMLBreak.StringId = "sect_" + sectID.ToString().Trim();
            return openXMLBreak;

        }

        internal static Comparison<WordHeadings?> SortAscending<T>(Func<WordHeadings, T> selector)
        {
            return (x, y) =>
            {
                if (x is null && y is null)
                    return 0;
                else if (x is null)
                    return -1;
                else if (y is null)
                    return 1;
                //if (x.is == y.IsDirectory)
                //    return Comparer<T>.Default.Compare(selector(x), selector(y));
                //else if (x.IsDirectory)
                //    return -1;
                else
                    return 1;
            };
        }

        internal static Comparison<WordHeadings?> SortDescending<T>(Func<WordHeadings, T> selector)
        {
            return (x, y) =>
            {
                if (x is null && y is null)
                    return 0;
                else if (x is null)
                    return 1;
                else if (y is null)
                    return -1;
                else
                    return 1;
            };
        }
        /// <summary>
        /// Deletes this instance.
        /// </summary>
        /// <autogeneratedoc />
        public void Delete()
        {
            DataController.SandboxEntities.DeleteWordHeading(Id);
        }

        /// <summary>
        /// The Insert.
        /// </summary>
        public void Insert()
        {
            try
            {
                bool success = DataController.StoryController.AddWordHeading(this);
                //DataController.SandboxEntities.WordHeadings.Add(this);
                //DataController.SandboxEntities.SaveChanges();

            }
            catch (Exception ex)
            {
                string error = ex.Message;

            }
        }

        /// <summary>
        /// Updates this instance.
        /// </summary>
        /// <autogeneratedoc />
        public void Update()
        {
            try
            {
                // ensure headingText length < 200
                if (HeadingText != null && HeadingText.Length > 200)
                {
                    HeadingText = HeadingText.Substring(0, 200);
                }

                DataController.StoryController.UpdateWordHeading(this);
                
                //DataController.SandboxEntities.WordHeadings.Update(this);
                //DataController.SandboxEntities.SaveChanges();
            }
            catch (Exception ex)
            {

                string error = ex.Message;
            }

        }

        internal void Save()
        {
            Update();
        }
        #endregion
    }

    /// <summary>
    /// Collection of WordHeadings
    /// </summary>
    /// <seealso cref="System.Collections.ObjectModel.ObservableCollection&lt;TaymadeEntities.Models.WordHeadings&gt;" />
    /// <autogeneratedoc />
    public class WordheadingsCollection : ObservableCollection<WordHeadings>
    {
        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="WordheadingsCollection"/> class.
        /// </summary>
        /// <autogeneratedoc />
        public WordheadingsCollection()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WordheadingsCollection"/> class.
        /// </summary>
        /// <param name="collection">The collection from which the elements are copied.</param>
        /// <autogeneratedoc />
        public WordheadingsCollection(IEnumerable<WordHeadings> collection) : base(collection)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WordheadingsCollection"/> class.
        /// </summary>
        /// <param name="collection">The collection.</param>
        /// <exception cref="System.InvalidOperationException">Collection contains items that are not of type WordHeading1.</exception>
        /// <autogeneratedoc />
        public WordheadingsCollection(List<WordHeadings> collection)
        {
            foreach (var item in collection)
            {
                if (item is WordHeadings heading1)
                {

                    this.Add(heading1);
                }
                else if (item is WordHeadings wordHeadings)
                {
                    WordHeadings temp = new WordHeadings
                    {
                        HeadingText = wordHeadings.HeadingText,
                        HeadingLevel = wordHeadings.HeadingLevel,
                        Id = wordHeadings.Id,
                        PageNumber = wordHeadings.PageNumber,
                        StoryId = wordHeadings.StoryId,
                        StringId = wordHeadings.StringId
                    };
                    this.Add(temp);
                }

                else
                {
                    // Handle the case where the item is not a WordHeading1
                    // You might want to log this or throw an exception
                    throw new InvalidOperationException("Collection contains items that are not of type WordHeading1.");
                }
            }
        }

        #endregion Public Constructors

        #region Public Properties

        /// <summary>
        /// Gets the hierarchical list.
        /// </summary>
        /// <value>
        /// The hierarchical list.
        /// </value>
        /// <autogeneratedoc />
        public ObservableCollection<WordHeadings> HierarchicalList
        {
            get
            {
                ObservableCollection<WordHeadings> hierarchicalList = new ObservableCollection<WordHeadings>();

                // Get list of heading_level 0 then go through list and find children
                var heading1s = this.Where(x => x.HeadingLevel == 0).Distinct( new WordHeadingsComparer()).OrderBy(x => x.StringId).ToList();
                foreach (var heading1 in heading1s)
                {
                    // Add the heading1 to the hierarchical list
                    hierarchicalList.Add(heading1);
                    this.GetChildren(heading1);
                }
                return hierarchicalList;
            }
        }

        #endregion Public Properties


        #region Private Methods

        /// <summary>
        /// Gets the children.
        /// </summary>
        /// <param name="heading1">The heading1.</param>
        /// <autogeneratedoc />
        private void GetChildren(WordHeadings heading1)
        {
            if (heading1 != null && heading1.HeadingLevel < 3 && heading1.ParentId >0)
            {
                int currentHeadingLevel = heading1.HeadingLevel.Value;
                // Ensure Children is initialized, if not clear it
                if (heading1.Children == null)
                {
                    heading1.Children = new ObservableCollection<WordHeadings>();
                } else heading1.Children.Clear();

                // Find all children of this heading1, sorted by StringId
                var children = this.Where(x => x.ParentId == heading1.Id  && x.HeadingLevel == currentHeadingLevel+1).OrderBy(x => x.StringId).Distinct(new WordHeadingsComparer()).ToList();
                // If there are children, add them to the hierarchical list
                if (children.Any())
                {
                    foreach (var child in children)
                    {
                        heading1.Children.Add(child);
                        // Recursively get children of this child
                        if (child.HeadingLevel < 3)
                        {
                            this.GetChildren(child);
                        }
                    }
                }
            }
        }

        #endregion Private Methods
    }

 
    //    public ObservableCollection<WordHeadings> Heading2s { get; set; } = new ObservableCollection<WordHeadings>();
    //}
    /// <summary>
    /// Compares two <see cref="WordHeadings"/> objects for equality based on their StringId and HeadingLevel.
    /// </summary>
    /// <seealso cref="System.Collections.Generic.IEqualityComparer&lt;TaymadeEntities.Models.WordHeadings&gt;" />
    /// <autogeneratedoc />
    public class WordHeadingsComparer : IEqualityComparer<WordHeadings>
    {
        #region Public Methods

        public bool Equals(WordHeadings? x, WordHeadings? y)
        {
            if (x == null 
                || y == null
                || string.IsNullOrEmpty(x.StringId) 
                || string.IsNullOrEmpty(y.StringId)) return false;
            return x.StringId == y.StringId && x.HeadingLevel == y.HeadingLevel;
        }
        public int GetHashCode(WordHeadings obj)
        {
            //Check whether the object is null
            if (Object.ReferenceEquals(obj, null)) return 0;

            // check headingtext is not null
            if (string.IsNullOrEmpty(obj.HeadingText)) return 0;

            return obj.HeadingText.GetHashCode() ^ obj.HeadingLevel.GetHashCode();
        }

        #endregion Public Methods
    }

}